package com.hand.hec.bpm.dto;
/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;
import uncertain.composite.DynamicObject;

/**
 * @author xxx@hand-china.com
 */

@ExtensionAttribute(disable = true)
@Table(name = "bpm_dynamic_data_line")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class DynamicDataLine extends BaseDTO {
    public static final String FIELD_DATA_LINE_ID = "dataLineId";
    public static final String FIELD_DOC_HEADER_ID = "docHeaderId";
    public static final String FIELD_BUSINESS_CATEGORY = "businessCategory";
    public static final String FIELD_DOC_ID = "docId";
    public static final String FIELD_PARENT_BUSINESS_CATEGORY = "parentBusinessCategory";
    public static final String FIELD_PARENT_DOC_ID = "parentDocId";
    public static final String FIELD_N001 = "n001";
    public static final String FIELD_N002 = "n002";
    public static final String FIELD_N003 = "n003";
    public static final String FIELD_N004 = "n004";
    public static final String FIELD_N005 = "n005";
    public static final String FIELD_N006 = "n006";
    public static final String FIELD_N007 = "n007";
    public static final String FIELD_N008 = "n008";
    public static final String FIELD_N009 = "n009";
    public static final String FIELD_N010 = "n010";
    public static final String FIELD_N011 = "n011";
    public static final String FIELD_N012 = "n012";
    public static final String FIELD_N013 = "n013";
    public static final String FIELD_N014 = "n014";
    public static final String FIELD_N015 = "n015";
    public static final String FIELD_N016 = "n016";
    public static final String FIELD_N017 = "n017";
    public static final String FIELD_N018 = "n018";
    public static final String FIELD_N019 = "n019";
    public static final String FIELD_N020 = "n020";
    public static final String FIELD_N021 = "n021";
    public static final String FIELD_N022 = "n022";
    public static final String FIELD_N023 = "n023";
    public static final String FIELD_N024 = "n024";
    public static final String FIELD_N025 = "n025";
    public static final String FIELD_N026 = "n026";
    public static final String FIELD_N027 = "n027";
    public static final String FIELD_N028 = "n028";
    public static final String FIELD_N029 = "n029";
    public static final String FIELD_N030 = "n030";
    public static final String FIELD_N031 = "n031";
    public static final String FIELD_N032 = "n032";
    public static final String FIELD_N033 = "n033";
    public static final String FIELD_N034 = "n034";
    public static final String FIELD_N035 = "n035";
    public static final String FIELD_N036 = "n036";
    public static final String FIELD_N037 = "n037";
    public static final String FIELD_N038 = "n038";
    public static final String FIELD_N039 = "n039";
    public static final String FIELD_N040 = "n040";
    public static final String FIELD_N041 = "n041";
    public static final String FIELD_N042 = "n042";
    public static final String FIELD_N043 = "n043";
    public static final String FIELD_N044 = "n044";
    public static final String FIELD_N045 = "n045";
    public static final String FIELD_N046 = "n046";
    public static final String FIELD_N047 = "n047";
    public static final String FIELD_N048 = "n048";
    public static final String FIELD_N049 = "n049";
    public static final String FIELD_N050 = "n050";
    public static final String FIELD_N051 = "n051";
    public static final String FIELD_N052 = "n052";
    public static final String FIELD_N053 = "n053";
    public static final String FIELD_N054 = "n054";
    public static final String FIELD_N055 = "n055";
    public static final String FIELD_N056 = "n056";
    public static final String FIELD_N057 = "n057";
    public static final String FIELD_N058 = "n058";
    public static final String FIELD_N059 = "n059";
    public static final String FIELD_N060 = "n060";
    public static final String FIELD_N061 = "n061";
    public static final String FIELD_N062 = "n062";
    public static final String FIELD_N063 = "n063";
    public static final String FIELD_N064 = "n064";
    public static final String FIELD_N065 = "n065";
    public static final String FIELD_N066 = "n066";
    public static final String FIELD_N067 = "n067";
    public static final String FIELD_N068 = "n068";
    public static final String FIELD_N069 = "n069";
    public static final String FIELD_N070 = "n070";
    public static final String FIELD_N071 = "n071";
    public static final String FIELD_N072 = "n072";
    public static final String FIELD_N073 = "n073";
    public static final String FIELD_N074 = "n074";
    public static final String FIELD_N075 = "n075";
    public static final String FIELD_N076 = "n076";
    public static final String FIELD_N077 = "n077";
    public static final String FIELD_N078 = "n078";
    public static final String FIELD_N079 = "n079";
    public static final String FIELD_N080 = "n080";
    public static final String FIELD_C001 = "c001";
    public static final String FIELD_C002 = "c002";
    public static final String FIELD_C003 = "c003";
    public static final String FIELD_C004 = "c004";
    public static final String FIELD_C005 = "c005";
    public static final String FIELD_C006 = "c006";
    public static final String FIELD_C007 = "c007";
    public static final String FIELD_C008 = "c008";
    public static final String FIELD_C009 = "c009";
    public static final String FIELD_C010 = "c010";
    public static final String FIELD_C011 = "c011";
    public static final String FIELD_C012 = "c012";
    public static final String FIELD_C013 = "c013";
    public static final String FIELD_C014 = "c014";
    public static final String FIELD_C015 = "c015";
    public static final String FIELD_C016 = "c016";
    public static final String FIELD_C017 = "c017";
    public static final String FIELD_C018 = "c018";
    public static final String FIELD_C019 = "c019";
    public static final String FIELD_C020 = "c020";
    public static final String FIELD_C021 = "c021";
    public static final String FIELD_C022 = "c022";
    public static final String FIELD_C023 = "c023";
    public static final String FIELD_C024 = "c024";
    public static final String FIELD_C025 = "c025";
    public static final String FIELD_C026 = "c026";
    public static final String FIELD_C027 = "c027";
    public static final String FIELD_C028 = "c028";
    public static final String FIELD_C029 = "c029";
    public static final String FIELD_C030 = "c030";
    public static final String FIELD_C031 = "c031";
    public static final String FIELD_C032 = "c032";
    public static final String FIELD_C033 = "c033";
    public static final String FIELD_C034 = "c034";
    public static final String FIELD_C035 = "c035";
    public static final String FIELD_C036 = "c036";
    public static final String FIELD_C037 = "c037";
    public static final String FIELD_C038 = "c038";
    public static final String FIELD_C039 = "c039";
    public static final String FIELD_C040 = "c040";
    public static final String FIELD_C041 = "c041";
    public static final String FIELD_C042 = "c042";
    public static final String FIELD_C043 = "c043";
    public static final String FIELD_C044 = "c044";
    public static final String FIELD_C045 = "c045";
    public static final String FIELD_C046 = "c046";
    public static final String FIELD_C047 = "c047";
    public static final String FIELD_C048 = "c048";
    public static final String FIELD_C049 = "c049";
    public static final String FIELD_C050 = "c050";
    public static final String FIELD_C051 = "c051";
    public static final String FIELD_C052 = "c052";
    public static final String FIELD_C053 = "c053";
    public static final String FIELD_C054 = "c054";
    public static final String FIELD_C055 = "c055";
    public static final String FIELD_C056 = "c056";
    public static final String FIELD_C057 = "c057";
    public static final String FIELD_C058 = "c058";
    public static final String FIELD_C059 = "c059";
    public static final String FIELD_C060 = "c060";
    public static final String FIELD_C061 = "c061";
    public static final String FIELD_C062 = "c062";
    public static final String FIELD_C063 = "c063";
    public static final String FIELD_C064 = "c064";
    public static final String FIELD_C065 = "c065";
    public static final String FIELD_C066 = "c066";
    public static final String FIELD_C067 = "c067";
    public static final String FIELD_C068 = "c068";
    public static final String FIELD_C069 = "c069";
    public static final String FIELD_C070 = "c070";
    public static final String FIELD_C071 = "c071";
    public static final String FIELD_C072 = "c072";
    public static final String FIELD_C073 = "c073";
    public static final String FIELD_C074 = "c074";
    public static final String FIELD_C075 = "c075";
    public static final String FIELD_C076 = "c076";
    public static final String FIELD_C077 = "c077";
    public static final String FIELD_C078 = "c078";
    public static final String FIELD_C079 = "c079";
    public static final String FIELD_C080 = "c080";
    public static final String FIELD_C081 = "c081";
    public static final String FIELD_C082 = "c082";
    public static final String FIELD_C083 = "c083";
    public static final String FIELD_C084 = "c084";
    public static final String FIELD_C085 = "c085";
    public static final String FIELD_C086 = "c086";
    public static final String FIELD_C087 = "c087";
    public static final String FIELD_C088 = "c088";
    public static final String FIELD_C089 = "c089";
    public static final String FIELD_C090 = "c090";
    public static final String FIELD_C091 = "c091";
    public static final String FIELD_C092 = "c092";
    public static final String FIELD_C093 = "c093";
    public static final String FIELD_C094 = "c094";
    public static final String FIELD_C095 = "c095";
    public static final String FIELD_C096 = "c096";
    public static final String FIELD_C097 = "c097";
    public static final String FIELD_C098 = "c098";
    public static final String FIELD_C099 = "c099";
    public static final String FIELD_C100 = "c100";
    public static final String FIELD_D001 = "d001";
    public static final String FIELD_D002 = "d002";
    public static final String FIELD_D003 = "d003";
    public static final String FIELD_D004 = "d004";
    public static final String FIELD_D005 = "d005";
    public static final String FIELD_D006 = "d006";
    public static final String FIELD_D007 = "d007";
    public static final String FIELD_D008 = "d008";
    public static final String FIELD_D009 = "d009";
    public static final String FIELD_D010 = "d010";
    public static final String FIELD_D011 = "d011";
    public static final String FIELD_D012 = "d012";
    public static final String FIELD_D013 = "d013";
    public static final String FIELD_D014 = "d014";
    public static final String FIELD_D015 = "d015";
    public static final String FIELD_D016 = "d016";
    public static final String FIELD_D017 = "d017";
    public static final String FIELD_D018 = "d018";
    public static final String FIELD_D019 = "d019";
    public static final String FIELD_D020 = "d020";
    public static final String FIELD_D021 = "d021";
    public static final String FIELD_D022 = "d022";
    public static final String FIELD_D023 = "d023";
    public static final String FIELD_D024 = "d024";
    public static final String FIELD_D025 = "d025";
    public static final String FIELD_D026 = "d026";
    public static final String FIELD_D027 = "d027";
    public static final String FIELD_D028 = "d028";
    public static final String FIELD_D029 = "d029";
    public static final String FIELD_D030 = "d030";
    public static final String FIELD_D031 = "d031";
    public static final String FIELD_D032 = "d032";
    public static final String FIELD_D033 = "d033";
    public static final String FIELD_D034 = "d034";
    public static final String FIELD_D035 = "d035";
    public static final String FIELD_D036 = "d036";
    public static final String FIELD_D037 = "d037";
    public static final String FIELD_D038 = "d038";
    public static final String FIELD_D039 = "d039";
    public static final String FIELD_D040 = "d040";
    public static final String FIELD_D041 = "d041";
    public static final String FIELD_D042 = "d042";
    public static final String FIELD_D043 = "d043";
    public static final String FIELD_D044 = "d044";
    public static final String FIELD_D045 = "d045";
    public static final String FIELD_D046 = "d046";
    public static final String FIELD_D047 = "d047";
    public static final String FIELD_D048 = "d048";
    public static final String FIELD_D049 = "d049";
    public static final String FIELD_D050 = "d050";
    public static final String FIELD_CLOB001 = "clob001";
    public static final String FIELD_CLOB002 = "clob002";
    public static final String FIELD_CLOB003 = "clob003";
    public static final String FIELD_CLOB004 = "clob004";
    public static final String FIELD_CLOB005 = "clob005";
    public static final String FIELD_CLOB006 = "clob006";
    public static final String FIELD_CLOB007 = "clob007";
    public static final String FIELD_CLOB008 = "clob008";
    public static final String FIELD_CLOB009 = "clob009";
    public static final String FIELD_CLOB010 = "clob010";
    public static final String FIELD_TRANSACTION_DATE = "transactionDate";
    public static final String FIELD_PERIOD_NAME = "periodName";
    public static final String FIELD_CURRENCY_CODE = "currencyCode";
    public static final String FIELD_CURRENCY_NAME = "currencyName";
    public static final String FIELD_EXCHANGE_RATE_TYPE = "exchangeRateType";
    public static final String FIELD_EXCHANGE_RATE_TYPE_NAME = "exchangeRateTypeName";
    public static final String FIELD_EXCHANGE_RATE = "exchangeRate";
    public static final String FIELD_PRICE = "price";
    public static final String FIELD_QUANTITY = "quantity";
    public static final String FIELD_AMOUNT = "amount";
    public static final String FIELD_FUNCTIONAL_AMOUNT = "functionalAmount";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_COMPANY_NAME = "companyName";
    public static final String FIELD_UNIT_ID = "unitId";
    public static final String FIELD_UNIT_NAME = "unitName";
    public static final String FIELD_POSITION_ID = "positionId";
    public static final String FIELD_POSITION_NAME = "positionName";
    public static final String FIELD_EMPLOYEE_ID = "employeeId";
    public static final String FIELD_EMPLOYEE_NAME = "employeeName";
    public static final String FIELD_SET_OF_BOOKS_ID = "setOfBooksId";
    public static final String FIELD_SET_OF_BOOKS_NAME = "setOfBooksName";
    public static final String FIELD_ACCOUNTING_ENTITY_ID = "accountingEntityId";
    public static final String FIELD_ACCOUNTING_ENTITY_NAME = "accountingEntityName";
    public static final String FIELD_RESP_CENTER_ID = "respCenterId";
    public static final String FIELD_RESP_CENTER_NAME = "respCenterName";
    public static final String FIELD_ACCOUNT_ID = "accountId";
    public static final String FIELD_ACCOUNT_NAME = "accountName";
    public static final String FIELD_PAYEE_CATEGORY = "payeeCategory";
    public static final String FIELD_PAYEE_CATEGORY_NAME = "payeeCategoryName";
    public static final String FIELD_PAYEE_ID = "payeeId";
    public static final String FIELD_PAYEE_NAME = "payeeName";
    public static final String FIELD_BANK_ACCOUNT_ID = "bankAccountId";
    public static final String FIELD_BANK_ACCOUNT_NUMBER = "bankAccountNumber";
    public static final String FIELD_BANK_ACCOUNT_NAME = "bankAccountName";


    /**
     * 行ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long dataLineId;

    /**
     * BPM单据ID
     */
    @Where
    private Long docHeaderId;

    /**
     * 业务类别
     */
    @NotEmpty
    @Length(max = 30)
    @Where

    private String businessCategory;
    /**
     * 单据ID
     */
    @Where
    private Long docId;
    /**
     * 父业务类别
     */
    @Where

    private String parentBusinessCategory;
    /**
     * 父单据ID
     */
    @Where
    private Long parentDocId;


    private Date transactionDate;
    private String periodName;
    private String currencyCode;
    private String currencyName;
    private String exchangeRateType;
    private String exchangeRateTypeName;
    private BigDecimal exchangeRate;
    private BigDecimal price;
    private BigDecimal quantity;
    private BigDecimal amount;
    private BigDecimal functionalAmount;
    private Long companyId;
    private String companyName;
    private Long unitId;
    private String unitName;
    private Long positionId;
    private String positionName;
    private Long employeeId;
    private String employeeName;
    private Long setOfBooksId;
    private String setOfBooksName;
    private Long accountingEntityId;
    private String accountingEntityName;
    private Long respCenterId;
    private String respCenterName;
    private Long accountId;
    private String accountName;
    private String payeeCategory;
    private String payeeCategoryName;
    private Long payeeId;
    private String payeeName;
    private Long bankAccountId;
    private String bankAccountNumber;
    private String bankAccountName;



    private BigDecimal n001;


    private BigDecimal n002;


    private BigDecimal n003;


    private BigDecimal n004;


    private BigDecimal n005;


    private BigDecimal n006;


    private BigDecimal n007;


    private BigDecimal n008;


    private BigDecimal n009;


    private BigDecimal n010;


    private BigDecimal n011;


    private BigDecimal n012;


    private BigDecimal n013;


    private BigDecimal n014;


    private BigDecimal n015;


    private BigDecimal n016;


    private BigDecimal n017;


    private BigDecimal n018;


    private BigDecimal n019;


    private BigDecimal n020;


    private BigDecimal n021;


    private BigDecimal n022;


    private BigDecimal n023;


    private BigDecimal n024;


    private BigDecimal n025;


    private BigDecimal n026;


    private BigDecimal n027;


    private BigDecimal n028;


    private BigDecimal n029;


    private BigDecimal n030;


    private BigDecimal n031;


    private BigDecimal n032;


    private BigDecimal n033;


    private BigDecimal n034;


    private BigDecimal n035;


    private BigDecimal n036;


    private BigDecimal n037;


    private BigDecimal n038;


    private BigDecimal n039;


    private BigDecimal n040;


    private BigDecimal n041;


    private BigDecimal n042;


    private BigDecimal n043;


    private BigDecimal n044;


    private BigDecimal n045;


    private BigDecimal n046;


    private BigDecimal n047;


    private BigDecimal n048;


    private BigDecimal n049;


    private BigDecimal n050;


    private BigDecimal n051;


    private BigDecimal n052;


    private BigDecimal n053;


    private BigDecimal n054;


    private BigDecimal n055;


    private BigDecimal n056;


    private BigDecimal n057;


    private BigDecimal n058;


    private BigDecimal n059;


    private BigDecimal n060;


    private BigDecimal n061;


    private BigDecimal n062;


    private BigDecimal n063;


    private BigDecimal n064;


    private BigDecimal n065;


    private BigDecimal n066;


    private BigDecimal n067;


    private BigDecimal n068;


    private BigDecimal n069;


    private BigDecimal n070;


    private BigDecimal n071;


    private BigDecimal n072;


    private BigDecimal n073;


    private BigDecimal n074;


    private BigDecimal n075;


    private BigDecimal n076;


    private BigDecimal n077;


    private BigDecimal n078;


    private BigDecimal n079;


    private BigDecimal n080;

    @Length(max = 2000)

    private String c001;
    @Length(max = 2000)

    private String c002;
    @Length(max = 2000)

    private String c003;
    @Length(max = 2000)

    private String c004;
    @Length(max = 2000)

    private String c005;
    @Length(max = 2000)

    private String c006;
    @Length(max = 2000)

    private String c007;
    @Length(max = 2000)

    private String c008;
    @Length(max = 2000)

    private String c009;
    @Length(max = 2000)

    private String c010;
    @Length(max = 2000)

    private String c011;
    @Length(max = 2000)

    private String c012;
    @Length(max = 2000)

    private String c013;
    @Length(max = 2000)

    private String c014;
    @Length(max = 2000)

    private String c015;
    @Length(max = 2000)

    private String c016;
    @Length(max = 2000)

    private String c017;
    @Length(max = 2000)

    private String c018;
    @Length(max = 2000)

    private String c019;
    @Length(max = 2000)

    private String c020;
    @Length(max = 2000)

    private String c021;
    @Length(max = 2000)

    private String c022;
    @Length(max = 2000)

    private String c023;
    @Length(max = 2000)

    private String c024;
    @Length(max = 2000)

    private String c025;
    @Length(max = 2000)

    private String c026;
    @Length(max = 2000)

    private String c027;
    @Length(max = 2000)

    private String c028;
    @Length(max = 2000)

    private String c029;
    @Length(max = 2000)

    private String c030;
    @Length(max = 2000)

    private String c031;
    @Length(max = 2000)

    private String c032;
    @Length(max = 2000)

    private String c033;
    @Length(max = 2000)

    private String c034;
    @Length(max = 2000)

    private String c035;
    @Length(max = 2000)

    private String c036;
    @Length(max = 2000)

    private String c037;
    @Length(max = 2000)

    private String c038;
    @Length(max = 2000)

    private String c039;
    @Length(max = 2000)

    private String c040;
    @Length(max = 2000)

    private String c041;
    @Length(max = 2000)

    private String c042;
    @Length(max = 2000)

    private String c043;
    @Length(max = 2000)

    private String c044;
    @Length(max = 2000)

    private String c045;
    @Length(max = 2000)

    private String c046;
    @Length(max = 2000)

    private String c047;
    @Length(max = 2000)

    private String c048;
    @Length(max = 2000)

    private String c049;
    @Length(max = 2000)

    private String c050;
    @Length(max = 2000)

    private String c051;
    @Length(max = 2000)

    private String c052;
    @Length(max = 2000)

    private String c053;
    @Length(max = 2000)

    private String c054;
    @Length(max = 2000)

    private String c055;
    @Length(max = 2000)

    private String c056;
    @Length(max = 2000)

    private String c057;
    @Length(max = 2000)

    private String c058;
    @Length(max = 2000)

    private String c059;
    @Length(max = 2000)

    private String c060;
    @Length(max = 2000)

    private String c061;
    @Length(max = 2000)

    private String c062;
    @Length(max = 2000)

    private String c063;
    @Length(max = 2000)

    private String c064;
    @Length(max = 2000)

    private String c065;
    @Length(max = 2000)

    private String c066;
    @Length(max = 2000)

    private String c067;
    @Length(max = 2000)

    private String c068;
    @Length(max = 2000)

    private String c069;
    @Length(max = 2000)

    private String c070;
    @Length(max = 2000)

    private String c071;
    @Length(max = 2000)

    private String c072;
    @Length(max = 2000)

    private String c073;
    @Length(max = 2000)

    private String c074;
    @Length(max = 2000)

    private String c075;
    @Length(max = 2000)

    private String c076;
    @Length(max = 2000)

    private String c077;
    @Length(max = 2000)

    private String c078;
    @Length(max = 2000)

    private String c079;
    @Length(max = 2000)

    private String c080;
    @Length(max = 2000)

    private String c081;
    @Length(max = 2000)

    private String c082;
    @Length(max = 2000)

    private String c083;
    @Length(max = 2000)

    private String c084;
    @Length(max = 2000)

    private String c085;
    @Length(max = 2000)

    private String c086;
    @Length(max = 2000)

    private String c087;
    @Length(max = 2000)

    private String c088;
    @Length(max = 2000)

    private String c089;
    @Length(max = 2000)

    private String c090;
    @Length(max = 2000)

    private String c091;
    @Length(max = 2000)

    private String c092;
    @Length(max = 2000)

    private String c093;
    @Length(max = 2000)

    private String c094;
    @Length(max = 2000)

    private String c095;
    @Length(max = 2000)

    private String c096;
    @Length(max = 2000)

    private String c097;
    @Length(max = 2000)

    private String c098;
    @Length(max = 2000)

    private String c099;
    @Length(max = 2000)

    private String c100;
    @Length(max = 2000)

    private Date d001;

    private Date d002;

    private Date d003;

    private Date d004;

    private Date d005;

    private Date d006;

    private Date d007;

    private Date d008;

    private Date d009;

    private Date d010;

    private Date d011;

    private Date d012;

    private Date d013;

    private Date d014;

    private Date d015;

    private Date d016;

    private Date d017;

    private Date d018;

    private Date d019;

    private Date d020;

    private Date d021;

    private Date d022;

    private Date d023;

    private Date d024;

    private Date d025;

    private Date d026;

    private Date d027;

    private Date d028;

    private Date d029;

    private Date d030;

    private Date d031;

    private Date d032;

    private Date d033;

    private Date d034;

    private Date d035;

    private Date d036;

    private Date d037;

    private Date d038;

    private Date d039;

    private Date d040;

    private Date d041;

    private Date d042;

    private Date d043;

    private Date d044;

    private Date d045;

    private Date d046;

    private Date d047;

    private Date d048;

    private Date d049;

    private Date d050;

    @Length(max = 2147483647)

    private String clob001;
    @Length(max = 2147483647)

    private String clob002;
    @Length(max = 2147483647)

    private String clob003;
    @Length(max = 2147483647)

    private String clob004;
    @Length(max = 2147483647)

    private String clob005;
    @Length(max = 2147483647)

    private String clob006;
    @Length(max = 2147483647)

    private String clob007;
    @Length(max = 2147483647)

    private String clob008;
    @Length(max = 2147483647)

    private String clob009;
    @Length(max = 2147483647)

    private String clob010;
}
