package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * @author hao.zhou@hand-china.com
 */


@ExtensionAttribute(disable = true)
@Table(name = "bpm_js_template")
public class JsTemplate extends BaseDTO {

    public static final String JS_TYPE_SUM_GRID_NUM = "SUM_GRID_NUM";
    public static final String JS_TYPE_CHANGE_READONLY = "CHANGE_READONLY";
    public static final String JS_TYPE_CHANGE_REQUIRED = "CHANGE_REQUIRED";
    public static final String JS_TYPE_CHANGE_CLEAR = "CHANGE_CLEAR";
    public static final String JS_TYPE_CHANGE_HIDDEN = "CHANGE_HIDDEN";
    public static final String JS_TYPE_CHANGE_LAYOUT_HIDDEN = "CHANGE_LAYOUT_HIDDEN";
    public static final String JS_TYPE_CHANGE_LOV_PARA = "CHANGE_LOV_PARA";
    public static final String JS_TYPE_CHANGE_GRID_COL_HIDE_SHOW = "CHANGE_GRID_COL_HIDE_SHOW";
    public static final String JS_TYPE_LOAD_READONLY = "LOAD_READONLY";
    public static final String JS_TYPE_LOAD_REQUIRED = "LOAD_REQUIRED";
    public static final String JS_TYPE_LOAD_CLEAR = "LOAD_CLEAR";
    public static final String JS_TYPE_LOAD_HIDDEN = "LOAD_HIDDEN";
    public static final String JS_TYPE_LOAD_LAYOUT_HIDDEN = "LOAD_LAYOUT_HIDDEN";
    public static final String JS_TYPE_LOAD_LOV_PARA = "LOAD_LOV_PARA";
    public static final String JS_TYPE_LOAD_GRID_COL_HIDE_SHOW = "LOAD_GRID_COL_HIDE_SHOW";
    public static final String JS_TYPE_CELL_CLICK_LOV_PARA = "CELL_CLICK_LOV_PARA";
    public static final String JS_TYPE_CHANGE_FORMULA = "CHANGE_FORMULA";

    public static final String FIELD_JS_TEMPLATE_ID = "jsTemplateId";
    public static final String FIELD_JS_TEMPLATE_CODE = "jsTemplateCode";
    public static final String FIELD_JS_TEMPLATE_DESC = "jsTemplateDesc";
    public static final String FIELD_JS_CONTENT = "jsContent";

    /**
     * 模板ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long jsTemplateId;

    /**
     * 模板代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where
    private String jsTemplateCode;

    /**
     * 模板描述
     */
    @NotEmpty
    @Length(max = 240)
    private String jsTemplateDesc;

    /**
     * 模板内容
     */
    @Length(max = 2147483647)
    private String jsContent;


    public void setJsTemplateId(Long jsTemplateId) {
        this.jsTemplateId = jsTemplateId;
    }

    public Long getJsTemplateId() {
        return jsTemplateId;
    }

    public void setJsTemplateCode(String jsTemplateCode) {
        this.jsTemplateCode = jsTemplateCode;
    }

    public String getJsTemplateCode() {
        return jsTemplateCode;
    }

    public void setJsTemplateDesc(String jsTemplateDesc) {
        this.jsTemplateDesc = jsTemplateDesc;
    }

    public String getJsTemplateDesc() {
        return jsTemplateDesc;
    }

    public void setJsContent(String jsContent) {
        this.jsContent = jsContent;
    }

    public String getJsContent() {
        return jsContent;
    }

}
