package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_group_field")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class PageGroupField extends BaseDTO {

    public static final String FIELD_FIELD_ID = "fieldId";
    public static final String FIELD_ENTITY_ID = "entityId";
    public static final String FIELD_ORDER_NUM = "orderNum";
    public static final String FIELD_BUSINESS_CATEGORY = "businessCategory";
    public static final String FIELD_TABLE_NAME = "tableName";
    public static final String FIELD_FIELD_NAME = "fieldName";
    public static final String FIELD_DATA_TYPE = "dataType";
    public static final String FIELD_FIELD_DESC = "fieldDesc";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_LOGIC_TYPE = "logicType";
    public static final String FIELD_LOGIC_BELONG_FIELD_ID = "logicBelongFieldId";
    public static final String FIELD_LOGIC_BELONG_FIELD_ID_DESC = "logicBelongFieldDesc";
    public static final String FIELD_QUERY_FLAG = "queryFlag";
    public static final String FIELD_QUERY_TYPE = "queryType";

    /**
     * 字段ID，主键
     */
    @Id
    @GeneratedValue
    @Where
    private Long fieldId;

    /**
     * 所属页面组
     */
    @Where
    private Long entityId;

    /**
     * 序号
     */
    private Long orderNum;

    /**
     * 业务类别
     */
    @Length(max = 200)
    private String businessCategory;

    /**
     * 映射表
     */
    @NotEmpty
    @Length(max = 200)
    private String tableName;

    /**
     * 映射字段
     */
    @NotEmpty
    @Length(max = 200)
    private String fieldName;

    /**
     * 数据类型
     */
    @NotEmpty
    @Length(max = 200)
    private String dataType;

    /**
     * 字段描述
     */
    @Length(max = 200)
    private String fieldDesc;

    /**
     * 启用标志
     */
    @Length(max = 200)
    private String enabledFlag;

    /**
     * 逻辑类型
     */
    @Length(max = 200)
    @Where
    private String logicType;

    /**
     * 查询标志
     */
    @Where
    private String queryFlag;

    /**
     * 查询类型
     */
    @Where
    private String queryType;

    /**
     * 逻辑归属字段
     */
    @Where
    @JoinTable(name = "logicBelongJoin", joinMultiLanguageTable = false, target = PageGroupField.class,
                    type = JoinType.LEFT, on = {@JoinOn(joinField = PageGroupField.FIELD_FIELD_ID)})
    private Long logicBelongFieldId;

    /**
     * 逻辑归属字段描述
     */
    @Length(max = 200)
    @Transient
    @JoinColumn(joinName = "logicBelongJoin", field = PageGroupField.FIELD_FIELD_DESC)
    private String logicBelongFieldDesc;
}
