package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_lov_map")
public class PageTagLovMap extends BaseDTO {

    public static final String FIELD_MAP_ID = "mapId";
    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_MAP_SEQUENCE = "mapSequence";
    public static final String FIELD_FROM_FIELD = "fromField";
    public static final String FIELD_TO_FIELD = "toField";


    @Id
    @GeneratedValue
    @Where
    private Long mapId;//映射ID

    @Where
    private Long tagId;//标签ID

    private Long mapSequence;//映射顺序

    @Length(max = 23)
    private String fromField;//映射从

    @Length(max = 23)
    private String toField;//映射到


    public void setMapId(Long mapId) {
        this.mapId = mapId;
    }

    public Long getMapId() {
        return mapId;
    }

    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setMapSequence(Long mapSequence) {
        this.mapSequence = mapSequence;
    }

    public Long getMapSequence() {
        return mapSequence;
    }

    public void setFromField(String fromField) {
        this.fromField = fromField;
    }

    public String getFromField() {
        return fromField;
    }

    public void setToField(String toField) {
        this.toField = toField;
    }

    public String getToField() {
        return toField;
    }

}
