package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_layout_tab")
public class PageLayoutTab extends BaseDTO {

    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_SELECTED = "selected";
    public static final String FIELD_CLOSEABLE = "closeable";
    public static final String FIELD_DISABLED = "disabled";
    public static final String FIELD_REF = "ref";
    public static final String FIELD_TABSTYLE = "tabstyle";
    public static final String FIELD_BODYSTYLE = "bodystyle";


    @Id
    @Where
    private Long layoutId;//布局组件ID

    @Length(max = 200)
    private String selected;//默认选中

    @Length(max = 200)
    private String closeable;//可关闭

    @Length(max = 200)
    private String disabled;//启用

    @Length(max = 200)
    private String ref;//引用页面地址

    @Length(max = 200)
    private String tabstyle;//Tab样式

    @Length(max = 200)
    private String bodystyle;//内容样式


    public void setLayoutId(Long layoutId) {
        this.layoutId = layoutId;
    }

    public Long getLayoutId() {
        return layoutId;
    }

    public void setSelected(String selected) {
        this.selected = selected;
    }

    public String getSelected() {
        return selected;
    }

    public void setCloseable(String closeable) {
        this.closeable = closeable;
    }

    public String getCloseable() {
        return closeable;
    }

    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }

    public String getDisabled() {
        return disabled;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public String getRef() {
        return ref;
    }

    public void setTabstyle(String tabstyle) {
        this.tabstyle = tabstyle;
    }

    public String getTabstyle() {
        return tabstyle;
    }

    public void setBodystyle(String bodystyle) {
        this.bodystyle = bodystyle;
    }

    public String getBodystyle() {
        return bodystyle;
    }


    public PageLayoutTab() {
    }

    public PageLayoutTab(TpltLayoutTab bpmTpltLayoutTab, Long pageLayoutId) {
        this.setLayoutId(pageLayoutId);
        this.setSelected(bpmTpltLayoutTab.getSelected());
        this.setCloseable(bpmTpltLayoutTab.getCloseable());
        this.setDisabled(bpmTpltLayoutTab.getDisabled());
        this.setRef(bpmTpltLayoutTab.getRef());
        this.setTabstyle(bpmTpltLayoutTab.getTabstyle());
        this.setBodystyle(bpmTpltLayoutTab.getBodystyle());

    }

}
