package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.*;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_basic")
public class PageTagBasic extends BaseDTO {

    public static final String TAG_TYPE_CHECKBOX = "checkBox";
    public static final String TAG_TYPE_COMBOBOX = "comboBox";
    public static final String TAG_TYPE_DATEPICKER = "datePicker";
    public static final String TAG_TYPE_DATETIMEPICKER = "dateTimePicker";
    public static final String TAG_TYPE_LABEL = "label";
    public static final String TAG_TYPE_LOV = "lov";
    public static final String TAG_TYPE_NUMBERFIELD = "numberField";
    public static final String TAG_TYPE_RADIO = "radio";
    public static final String TAG_TYPE_TEXTFIELD = "textField";

    public static final String FIELD_TAG_ID = "tagId";

    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_TAG_SEQUENCE = "tagSequence";
    public static final String FIELD_TAG_CODE = "tagCode";
    public static final String FIELD_TAG_DESC = "tagDesc";
    public static final String FIELD_TAG_TYPE = "tagType";
    public static final String FIELD_TEMPLATE_FLAG = "templateFlag";
    public static final String FIELD_FIELD_ID = "fieldId";
    public static final String FIELD_NAME = "name";
    public static final String FIELD_DEFAULTVALUE = "defaultvalue";
    public static final String FIELD_READONLY = "readonly";
    public static final String FIELD_REQUIRED = "required";
    public static final String FIELD_PROMPT = "prompt";
    public static final String FIELD_VALIDATOR = "validator";
    public static final String FIELD_REQUIREDMESSAGE = "requiredmessage";
    public static final String FIELD_WIDTH = "width";
    public static final String FIELD_ID = "id";
    public static final String FIELD_BINDTARGET = "bindtarget";
    public static final String FIELD_HEIGHT = "height";
    public static final String FIELD_STYLE = "style";
    public static final String FIELD_COLSPAN = "colspan";
    public static final String FIELD_ROWSPAN = "rowspan";
    public static final String FIELD_HIDDEN = "hidden";
    public static final String FIELD_PARENT_TAG_ID = "parentTagId";
    public static final String FIELD_ALIGN = "align";
    public static final String FIELD_EDITOR = "editor";
    public static final String FIELD_EDITORFUNCTION = "editorfunction";
    public static final String FIELD_FOOTERRENDERER = "footerrenderer";
    public static final String FIELD_LOCK_FLAG = "lockFlag";
    public static final String FIELD_RENDERER = "renderer";
    public static final String FIELD_RESIZABLE = "resizable";
    public static final String FIELD_SORTABLE = "sortable";
    public static final String FIELD_FOOTERRENDERER_JS = "footerrendererJs";
    public static final String FIELD_PRINTABLE = "printable";
    public static final String FIELD_FIELD_SOURCE = "fieldSource";
    public static final String FIELD_APP_HIDE_FLAG = "appHideFlag";

    public static final String FIELD_PARENT_NAME = "parentName";


    @Id
    @GeneratedValue
    @Where
    private Long tagId;//标签ID

    @Where
    private Long layoutId;//所属布局组件ID

    private Long tagSequence;//标签顺序

    @NotEmpty
    @Length(max = 200)
    @Where
    private String tagCode;//标签代码

    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String tagDesc;//标签描述

    @Length(max = 200)
    @Where
    private String tagType;//标签类型

    @Length(max = 200)
    private String templateFlag;//模板标志

    @Where
    private Long fieldId;//字段ID

    @Length(max = 200)
    private String name;//标签对应字段名称，数据源属性

    @Length(max = 200)
    private String defaultvalue;//标签对应字段默认值，数据源属性

    @Length(max = 200)
    private String readonly;//标签对应字段是否只读，数据源属性

    @Length(max = 200)
    private String required;//标签对应字段是否必输，数据源属性

    @Length(max = 200)
    private String prompt;//标签对应字段的描述，数据源属性

    @Length(max = 200)
    private String validator;//标签对应字段的校验逻辑，数据源属性

    @Length(max = 200)
    private String requiredmessage;//标签对应字段的必输提示信息，数据源属性

    private Long width;//宽度，Form类标签和Grid类标签通用

    @Length(max = 200)
    private String id;//id，From类标签

    @Length(max = 200)
    private String bindtarget;//绑定对象，From类标签

    private Long height;//高度，From类标签

    @Length(max = 200)
    private String style;//样式，From类标签

    private Long colspan;//所占列数，From类标签

    private Long rowspan;//所占行数，From类标签

    @Length(max = 200)
    private String hidden;//是否隐藏，From类标签

    private Long parentTagId;//上级标签ID，Grid类标签在做复杂表头时使用

    @Length(max = 200)
    private String align;//居中，Grid类标签专用

    @Length(max = 200)
    private String editor;//编辑器，Grid类标签专用

    @Length(max = 200)
    private String editorfunction;//编辑器方法，Grid类标签专用

    @Length(max = 200)
    private String footerrenderer;//列脚渲染器，Grid类标签专用

    @Length(max = 200)
    private String lockFlag;//列锁定，Grid类标签专用

    @Length(max = 200)
    private String renderer;//渲染，Grid类标签专用

    @Length(max = 200)
    private String resizable;//大小可调整，Grid类标签专用

    @Length(max = 200)
    private String sortable;//是否可排序，Grid类标签专用

    @Length(max = 200)
    private String footerrendererJs;//列合计函数js，取自js模板

    @Length(max = 200)
    private String printable;//是否可打印

    @Length(max = 200)
    private String fieldSource;//隐藏域对应标签

    @Length(max = 200)
    private String appHideFlag;//是否APP隐藏

    @Length(max = 200)
    @Transient
    private String parentName;


    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setLayoutId(Long layoutId) {
        this.layoutId = layoutId;
    }

    public Long getLayoutId() {
        return layoutId;
    }

    public void setTagSequence(Long tagSequence) {
        this.tagSequence = tagSequence;
    }

    public Long getTagSequence() {
        return tagSequence;
    }

    public void setTagCode(String tagCode) {
        this.tagCode = tagCode;
    }

    public String getTagCode() {
        return tagCode;
    }

    public void setTagDesc(String tagDesc) {
        this.tagDesc = tagDesc;
    }

    public String getTagDesc() {
        return tagDesc;
    }

    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    public String getTagType() {
        return tagType;
    }

    public void setTemplateFlag(String templateFlag) {
        this.templateFlag = templateFlag;
    }

    public String getTemplateFlag() {
        return templateFlag;
    }

    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }

    public Long getFieldId() {
        return fieldId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    public String getDefaultvalue() {
        return defaultvalue;
    }

    public void setReadonly(String readonly) {
        this.readonly = readonly;
    }

    public String getReadonly() {
        return readonly;
    }

    public void setRequired(String required) {
        this.required = required;
    }

    public String getRequired() {
        return required;
    }

    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }

    public String getPrompt() {
        return prompt;
    }

    public void setValidator(String validator) {
        this.validator = validator;
    }

    public String getValidator() {
        return validator;
    }

    public void setRequiredmessage(String requiredmessage) {
        this.requiredmessage = requiredmessage;
    }

    public String getRequiredmessage() {
        return requiredmessage;
    }

    public void setWidth(Long width) {
        this.width = width;
    }

    public Long getWidth() {
        return width;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setBindtarget(String bindtarget) {
        this.bindtarget = bindtarget;
    }

    public String getBindtarget() {
        return bindtarget;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getHeight() {
        return height;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public String getStyle() {
        return style;
    }

    public void setColspan(Long colspan) {
        this.colspan = colspan;
    }

    public Long getColspan() {
        return colspan;
    }

    public void setRowspan(Long rowspan) {
        this.rowspan = rowspan;
    }

    public Long getRowspan() {
        return rowspan;
    }

    public void setHidden(String hidden) {
        this.hidden = hidden;
    }

    public String getHidden() {
        return hidden;
    }

    public void setParentTagId(Long parentTagId) {
        this.parentTagId = parentTagId;
    }

    public Long getParentTagId() {
        return parentTagId;
    }

    public void setAlign(String align) {
        this.align = align;
    }

    public String getAlign() {
        return align;
    }

    public void setEditor(String editor) {
        this.editor = editor;
    }

    public String getEditor() {
        return editor;
    }

    public void setEditorfunction(String editorfunction) {
        this.editorfunction = editorfunction;
    }

    public String getEditorfunction() {
        return editorfunction;
    }

    public void setFooterrenderer(String footerrenderer) {
        this.footerrenderer = footerrenderer;
    }

    public String getFooterrenderer() {
        return footerrenderer;
    }

    public void setRenderer(String renderer) {
        this.renderer = renderer;
    }

    public String getRenderer() {
        return renderer;
    }

    public void setResizable(String resizable) {
        this.resizable = resizable;
    }

    public String getResizable() {
        return resizable;
    }

    public void setSortable(String sortable) {
        this.sortable = sortable;
    }

    public String getSortable() {
        return sortable;
    }

    public void setFooterrendererJs(String footerrendererJs) {
        this.footerrendererJs = footerrendererJs;
    }

    public String getFooterrendererJs() {
        return footerrendererJs;
    }

    public void setPrintable(String printable) {
        this.printable = printable;
    }

    public String getPrintable() {
        return printable;
    }

    public void setFieldSource(String fieldSource) {
        this.fieldSource = fieldSource;
    }

    public String getFieldSource() {
        return fieldSource;
    }

    public void setAppHideFlag(String appHideFlag) {
        this.appHideFlag = appHideFlag;
    }

    public String getAppHideFlag() {
        return appHideFlag;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getLockFlag() {
        return lockFlag;
    }

    public void setLockFlag(String lockFlag) {
        this.lockFlag = lockFlag;
    }

    public PageTagBasic() {
    }

    public PageTagBasic(TpltTagBasic tpltTagsBasic, Long layoutId) {
        this.setLayoutId(layoutId);
        this.setTagSequence(tpltTagsBasic.getTagSequence());
        this.setTagCode(tpltTagsBasic.getTagCode());
        this.setTagDesc(tpltTagsBasic.getTagDesc());
        this.setTagType(tpltTagsBasic.getTagType());
        this.setColspan(tpltTagsBasic.getColspan());
        this.setRowspan(tpltTagsBasic.getRowspan());
        this.setHidden(tpltTagsBasic.getHidden());
        this.setParentTagId(tpltTagsBasic.getParentTagId());
        this.setTemplateFlag("Y");
        this.setName(tpltTagsBasic.getName());
        this.setId(tpltTagsBasic.getId());
        this.setDefaultvalue(tpltTagsBasic.getDefaultvalue());
        this.setReadonly(tpltTagsBasic.getReadonly());
        this.setRequired(tpltTagsBasic.getRequired());
        this.setPrompt(tpltTagsBasic.getPrompt());
        this.setValidator(tpltTagsBasic.getValidator());
        this.setRequiredmessage(tpltTagsBasic.getRequiredmessage());
        this.setPrintable("true");
        this.setFieldSource(tpltTagsBasic.getFieldSource());
    }

}
