package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_datetimepicker")
public class PageTagDatetimepicker extends BaseDTO {

    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_DAYRENDERER = "dayrenderer";
    public static final String FIELD_ENABLEBESIDEDAYS = "enablebesidedays";
    public static final String FIELD_ENABLEMONTHBTN = "enablemonthbtn";
    public static final String FIELD_VIEWSIZE = "viewsize";
    public static final String FIELD_RENDERER = "renderer";
    public static final String FIELD_HOUR = "hour";
    public static final String FIELD_MINUTE = "minute";
    public static final String FIELD_SECOND = "second";


    @Id
    private Long tagId;//标签ID

    @Length(max = 200)
    private String dayrenderer;//日期渲染

    @Length(max = 200)
    private String enablebesidedays;//本月始末补齐后月日期

    @Length(max = 200)
    private String enablemonthbtn;//月份按钮选择方式

    private Long viewsize;//日历显示个数

    @Length(max = 200)
    private String renderer;//渲染器

    private Long hour;//默认显示的小时

    private Long minute;//默认显示的分钟

    private Long second;//默认显示的秒钟


    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setDayrenderer(String dayrenderer) {
        this.dayrenderer = dayrenderer;
    }

    public String getDayrenderer() {
        return dayrenderer;
    }

    public void setEnablebesidedays(String enablebesidedays) {
        this.enablebesidedays = enablebesidedays;
    }

    public String getEnablebesidedays() {
        return enablebesidedays;
    }

    public void setEnablemonthbtn(String enablemonthbtn) {
        this.enablemonthbtn = enablemonthbtn;
    }

    public String getEnablemonthbtn() {
        return enablemonthbtn;
    }

    public void setViewsize(Long viewsize) {
        this.viewsize = viewsize;
    }

    public Long getViewsize() {
        return viewsize;
    }

    public void setRenderer(String renderer) {
        this.renderer = renderer;
    }

    public String getRenderer() {
        return renderer;
    }

    public void setHour(Long hour) {
        this.hour = hour;
    }

    public Long getHour() {
        return hour;
    }

    public void setMinute(Long minute) {
        this.minute = minute;
    }

    public Long getMinute() {
        return minute;
    }

    public void setSecond(Long secord) {
        this.second = second;
    }

    public Long getSecond() {
        return second;
    }

}
