package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.system.dto.BaseDTO;
import com.hand.hap.system.dto.Prompt;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Table;
import javax.persistence.criteria.JoinType;

@Component
@ExtensionAttribute(disable = true)
public class PageTag extends BaseDTO {

    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_TAG_SEQUENCE = "tagSequence";
    public static final String FIELD_TAG_CODE = "tagCode";
    public static final String FIELD_TAG_DESC = "tagDesc";
    public static final String FIELD_TAG_TYPE = "tagType";
    public static final String FIELD_TAG_TYPE_DESC = "tagTypeDesc";
    public static final String FIELD_TEMPLATE_FLAG = "templateFlag";
    public static final String FIELD_FIELD_ID = "fieldId";
    public static final String FIELD_FIELD_NAME = "fieldName";
    public static final String FIELD_NAME = "name";
    public static final String FIELD_DEFAULTVALUE = "defaultvalue";
    public static final String FIELD_READONLY = "readonly";
    public static final String FIELD_REQUIRED = "required";
    public static final String FIELD_PROMPT = "prompt";
    public static final String FIELD_PROMPT_DESC = "promptDesc";
    public static final String FIELD_VALIDATOR = "validator";
    public static final String FIELD_REQUIREDMESSAGE = "requiredmessage";
    public static final String FIELD_WIDTH = "width";
    public static final String FIELD_CLOUMNWIDTH = "cloumnwidth";
    public static final String FIELD_ID = "id";
    public static final String FIELD_BINDTARGET = "bindtarget";
    public static final String FIELD_HEIGHT = "height";
    public static final String FIELD_STYLE = "style";
    public static final String FIELD_COLSPAN = "colspan";
    public static final String FIELD_ROWSPAN = "rowspan";
    public static final String FIELD_HIDDEN = "hidden";
    public static final String FIELD_PARENT_TAG_ID = "parentTagId";
    public static final String FIELD_PARENT_TAG_DESC = "parentTagDesc";
    public static final String FIELD_ALIGN = "align";
    public static final String FIELD_EDITOR = "editor";
    public static final String FIELD_EDITORFUNCTION = "editorfunction";
    public static final String FIELD_FOOTERRENDERER = "footerrenderer";
    public static final String FIELD_FOOTERRENDERER_JS = "footerrendererJs";
    public static final String FIELD_LOCK_FLAG = "lockFlag";
    public static final String FIELD_RENDERER = "renderer";
    public static final String FIELD_RESIZABLE = "resizable";
    public static final String FIELD_SORTABLE = "sortable";
    public static final String FIELD_APP_HIDE_FLAG = "appHideFlag";
    public static final String FIELD_TF_TYPECASE = "tfTypecase";
    public static final String FIELD_NF_ALLOWDECIMALS = "nfAllowdecimals";
    public static final String FIELD_NF_DECIMALPRECISION = "nfDecimalprecision";
    public static final String FIELD_NF_ALLOWNEGATIVE = "nfAllownegative";
    public static final String FIELD_NF_ALLOWFORMAT = "nfAllowformat";
    public static final String FIELD_CB_DATASOURCE = "cbDatasource";
    public static final String FIELD_CB_OPTIONS = "cbOptions";
    public static final String FIELD_CB_VALUEFIELD = "cbValuefield";
    public static final String FIELD_CB_RETURNFIELD = "cbReturnfield";
    public static final String FIELD_CB_RETURNFIELD_DESC = "cbReturnfieldDesc";
    public static final String FIELD_CB_DISPLAYFIELD = "cbDisplayfield";
    public static final String FIELD_CB_SYSCODE = "cbSyscode";
    public static final String FIELD_CB_SQLTEXT = "cbSqltext";
    public static final String FIELD_CB_LOVCODE = "cbLovcode";
    public static final String FIELD_LOV_DATASOURCE = "lovDatasource";
    public static final String FIELD_LOV_LOVCODE = "lovLovcode";
    public static final String FIELD_LOV_LOVURL = "lovLovurl";
    public static final String FIELD_LOV_LOVAUTOQUERY = "lovLovautoquery";
    public static final String FIELD_LOV_LOVGRIDHEIGHT = "lovLovgridheight";
    public static final String FIELD_LOV_LOVHEIGHT = "lovLovheight";
    public static final String FIELD_LOV_LOVWIDTH = "lovLovwidth";
    public static final String FIELD_LOV_LOVLABELWIDTH = "lovLovlabelwidth";
    public static final String FIELD_LOV_AUTOCOMPLETE = "lovAutocomplete";
    public static final String FIELD_LOV_AUTOCOMPLETEFIELD = "lovAutocompletefield";
    public static final String FIELD_LOV_TITLE = "lovTitle";
    public static final String FIELD_LOV_SQLTEXT = "lovSqltext";
    public static final String FIELD_LOV_SYSCODE = "lovSyscode";
    public static final String FIELD_LABEL_RENDERER = "labelRenderer";
    public static final String FIELD_RADIO_DATASOURCE = "radioDatasource";
    public static final String FIELD_RADIO_OPTIONS = "radioOptions";
    public static final String FIELD_RADIO_VALUEFIELD = "radioValuefield";
    public static final String FIELD_RADIO_LABELEXPRESSION = "radioLabelexpression";
    public static final String FIELD_RADIO_LABELFIELD = "radioLabelfield";
    public static final String FIELD_RADIO_LAYOUT = "radioLayout";
    public static final String FIELD_RADIO_SYSCODE = "radioSyscode";
    public static final String FIELD_RADIO_SQLTEXT = "radioSqltext";
    public static final String FIELD_CK_CHECKEDVALUE = "ckCheckedvalue";
    public static final String FIELD_CK_UNCHECKEDVALUE = "ckUncheckedvalue";
    public static final String FIELD_CK_LABEL = "ckLabel";
    public static final String FIELD_DP_DAYRENDERER = "dpDayrenderer";
    public static final String FIELD_DP_ENABLEBESIDEDAYS = "dpEnablebesidedays";
    public static final String FIELD_DP_ENABLEMONTHBTN = "dpEnablemonthbtn";
    public static final String FIELD_DP_VIEWSIZE = "dpViewsize";
    public static final String FIELD_DP_RENDERER = "dpRenderer";
    public static final String FIELD_DTP_DAYRENDERER = "dtpDayrenderer";
    public static final String FIELD_DTP_ENABLEBESIDEDAYS = "dtpEnablebesidedays";
    public static final String FIELD_DTP_ENABLEMONTHBTN = "dtpEnablemonthbtn";
    public static final String FIELD_DTP_VIEWSIZE = "dtpViewsize";
    public static final String FIELD_DTP_RENDERER = "dtpRenderer";
    public static final String FIELD_DTP_HOUR = "dtpHour";
    public static final String FIELD_DTP_MINUTE = "dtpMinute";
    public static final String FIELD_DTP_SECOND = "dtpSecond";
    public static final String FIELD_PRINTABLE = "printable";
    public static final String FIELD_FIELD_SOURCE = "fieldSource";
    public static final String FIELD_PARENT_NAME = "parentName";


    private Long tagId;

    private Long layoutId;

    private Long tagSequence;

    @Length(max = 200)
    private String tagCode;

    @Length(max = 200)
    private String tagDesc;

    @Length(max = 200)
    private String tagType;

    @Length(max = 200)
    private String tagTypeDesc;

    @Length(max = 200)
    private String templateFlag;

    private Long fieldId;

    @Length(max = 200)
    private String fieldName;

    @Length(max = 200)
    private String name;

    @Length(max = 200)
    private String defaultvalue;

    @Length(max = 200)
    private String readonly;

    @Length(max = 200)
    private String required;

    @Length(max = 200)
    @JoinTable(name = "employeeField",joinMultiLanguageTable = true, target = Prompt.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Prompt.FIELD_PROMPT_CODE),@JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private String prompt;

    @Length(max = 200)
    @JoinColumn(joinName = "unitField", field = Prompt.FIELD_DESCRIPTION)
    private String promptDesc;

    @Length(max = 200)
    private String validator;

    @Length(max = 200)
    private String requiredmessage;

    private Long width;

    private Long cloumnwidth;

    @Length(max = 200)
    private String id;

    @Length(max = 200)
    private String bindtarget;

    private Long height;

    @Length(max = 200)
    private String style;

    private Long colspan;

    private Long rowspan;

    @Length(max = 200)
    private String hidden;

    private Long parentTagId;

    @Length(max = 200)
    private String parentTagDesc;

    @Length(max = 200)
    private String align;

    @Length(max = 200)
    private String editor;

    @Length(max = 200)
    private String editorfunction;

    @Length(max = 200)
    private String footerrenderer;

    @Length(max = 200)
    private String lockFlag;

    @Length(max = 200)
    private String renderer;

    @Length(max = 200)
    private String resizable;

    @Length(max = 200)
    private String sortable;

    @Length(max = 200)
    private String appHideFlag;

    @Length(max = 200)
    private String tfTypecase;

    @Length(max = 200)
    private String nfAllowdecimals;

    private Long nfDecimalprecision;

    @Length(max = 200)
    private String nfAllownegative;

    @Length(max = 200)
    private String nfAllowformat;

    @Length(max = 200)
    private String cbDatasource;

    @Length(max = 200)
    private String cbOptions;

    @Length(max = 200)
    private String cbValuefield;

    @Length(max = 200)
    private String cbReturnfield;

    @Length(max = 200)
    private String cbReturnfieldDesc;

    @Length(max = 200)
    private String cbDisplayfield;

    @Length(max = 200)
    private String cbSyscode;

    @Length(max = 200)
    private String cbSqltext;


    @Length(max = 200)
    private String cbLovcode;

    @Length(max = 200)
    private String lovDatasource;

    @Length(max = 200)
    private String lovLovcode;

    @Length(max = 200)
    private String lovLovurl;

    @Length(max = 200)
    private String lovLovautoquery;

    private Long lovLovgridheight;

    private Long lovLovheight;

    private Long lovLovwidth;

    private Long lovLovlabelwidth;

    @Length(max = 200)
    private String lovAutocomplete;

    @Length(max = 200)
    private String lovAutocompletefield;

    @Length(max = 200)
    private String lovTitle;

    @Length(max = 200)
    private String lovSqltext;

    @Length(max = 200)
    private String lovSyscode;

    @Length(max = 200)
    private String labelRenderer;

    @Length(max = 200)
    private String radioDatasource;

    @Length(max = 200)
    private String radioOptions;

    @Length(max = 200)
    private String radioValuefield;

    @Length(max = 200)
    private String radioLabelexpression;

    @Length(max = 200)
    private String radioLabelfield;

    @Length(max = 200)
    private String radioLayout;

    @Length(max = 200)
    private String radioSyscode;

    @Length(max = 200)
    private String radioSqltext;

    @Length(max = 200)
    private String ckCheckedvalue;

    @Length(max = 200)
    private String ckUncheckedvalue;

    @Length(max = 200)
    private String ckLabel;

    @Length(max = 200)
    private String dpDayrenderer;

    @Length(max = 200)
    private String dpEnablebesidedays;

    @Length(max = 200)
    private String dpEnablemonthbtn;

    private Long dpViewsize;

    @Length(max = 200)
    private String dpRenderer;

    @Length(max = 200)
    private String dtpDayrenderer;

    @Length(max = 200)
    private String dtpEnablebesidedays;

    @Length(max = 200)
    private String dtpEnablemonthbtn;

    private Long dtpViewsize;

    @Length(max = 200)
    private String dtpRenderer;

    private Long dtpHour;

    private Long dtpMinute;

    private Long dtpSecond;

    @Length(max = 200)
    private String printable;

    @Length(max = 200)
    private String fieldSource;

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    private String parentName;


    @Length(max = 200)
    private String footerrendererJs;//列合计函数js，取自js模板

    public PageTagBasic convertBasic() {
        PageTagBasic basic = new PageTagBasic();
        basic.setTagId(this.getTagId());
        basic.setLayoutId(this.getLayoutId());
        basic.setTagSequence(this.getTagSequence());
        basic.setTagCode(this.getTagCode());
        basic.setTagDesc(this.getTagDesc());
        basic.setTagType(this.getTagType());
        basic.setTemplateFlag(this.getTemplateFlag());
        basic.setFieldId(this.getFieldId());
        basic.setName(this.getName());
        basic.setDefaultvalue(this.getDefaultvalue());
        basic.setReadonly(this.getReadonly());
        basic.setRequired(this.getRequired());
        basic.setPrompt(this.getPrompt());
        basic.setValidator(this.getValidator());
        basic.setRequiredmessage(this.getRequiredmessage());
        basic.setWidth(this.getWidth());
        basic.setId(this.getId());
        basic.setBindtarget(this.getBindtarget());
        basic.setHeight(this.getHeight());
        basic.setStyle(this.getStyle());
        basic.setColspan(this.getColspan());
        basic.setRowspan(this.getRowspan());
        basic.setHidden(this.getHidden());
        basic.setParentTagId(this.getParentTagId());
        basic.setAlign(this.getAlign());
        basic.setEditor(this.getEditor());
        basic.setEditorfunction(this.getEditorfunction());
        basic.setFooterrenderer(this.getFooterrenderer());
        basic.setLockFlag(this.getLockFlag());
        basic.setRenderer(this.getRenderer());
        basic.setResizable(this.getResizable());
        basic.setSortable(this.getSortable());
        basic.setFooterrendererJs(this.getFooterrendererJs());
        basic.setPrintable(this.getPrintable());
        basic.setFieldSource(this.getFieldSource());
        basic.setAppHideFlag(this.getAppHideFlag());
        basic.setParentName(this.getParentName());


        basic.set__id(this.get__id());
        basic.set__status(this.get__status());
        basic.set__tls(this.get__tls());
        basic.setSortname(this.getSortname());
        basic.setSortorder(this.getSortorder());
        basic.set_token(this.get_token());
        basic.setRequestId(this.getRequestId());
        basic.setProgramId(this.getProgramId());
        basic.setObjectVersionNumber(this.getObjectVersionNumber());
        basic.setLastUpdateLogin(this.getLastUpdateLogin());
        basic.setCreatedBy(this.getCreatedBy());
        basic.setCreationDate(this.getCreationDate());
        basic.setLastUpdatedBy(this.getLastUpdatedBy());
        basic.setLastUpdateDate(this.getLastUpdateDate());
        basic.setAttributeCategory(this.getAttributeCategory());
        basic.setAttribute1(this.getAttribute1());
        basic.setAttribute2(this.getAttribute2());
        basic.setAttribute3(this.getAttribute3());
        basic.setAttribute4(this.getAttribute4());
        basic.setAttribute5(this.getAttribute5());
        basic.setAttribute6(this.getAttribute6());
        basic.setAttribute7(this.getAttribute7());
        basic.setAttribute8(this.getAttribute8());
        basic.setAttribute9(this.getAttribute9());
        basic.setAttribute10(this.getAttribute10());
        basic.setAttribute11(this.getAttribute11());
        basic.setAttribute12(this.getAttribute12());
        basic.setAttribute13(this.getAttribute13());
        basic.setAttribute14(this.getAttribute14());
        basic.setAttribute15(this.getAttribute15());

        return basic;
    }

    public PageTagCheckbox convertCheckbox() {
        PageTagCheckbox ck = new PageTagCheckbox();
        ck.setTagId(this.getTagId());
        ck.setCheckedvalue(this.getCkCheckedvalue());
        ck.setUncheckedvalue(this.getCkUncheckedvalue());
        ck.setLabel(this.getCkLabel());

        ck.set__id(this.get__id());
        ck.set__status(this.get__status());
        ck.set__tls(this.get__tls());
        ck.setSortname(this.getSortname());
        ck.setSortorder(this.getSortorder());
        ck.set_token(this.get_token());
        ck.setRequestId(this.getRequestId());
        ck.setProgramId(this.getProgramId());
        ck.setObjectVersionNumber(this.getObjectVersionNumber());
        ck.setLastUpdateLogin(this.getLastUpdateLogin());
        ck.setCreatedBy(this.getCreatedBy());
        ck.setCreationDate(this.getCreationDate());
        ck.setLastUpdatedBy(this.getLastUpdatedBy());
        ck.setLastUpdateDate(this.getLastUpdateDate());
        ck.setAttributeCategory(this.getAttributeCategory());
        ck.setAttribute1(this.getAttribute1());
        ck.setAttribute2(this.getAttribute2());
        ck.setAttribute3(this.getAttribute3());
        ck.setAttribute4(this.getAttribute4());
        ck.setAttribute5(this.getAttribute5());
        ck.setAttribute6(this.getAttribute6());
        ck.setAttribute7(this.getAttribute7());
        ck.setAttribute8(this.getAttribute8());
        ck.setAttribute9(this.getAttribute9());
        ck.setAttribute10(this.getAttribute10());
        ck.setAttribute11(this.getAttribute11());
        ck.setAttribute12(this.getAttribute12());
        ck.setAttribute13(this.getAttribute13());
        ck.setAttribute14(this.getAttribute14());
        ck.setAttribute15(this.getAttribute15());

        return ck;
    }

    public PageTagCombobox convertCombobox() {
        PageTagCombobox cb = new PageTagCombobox();
        cb.setTagId(this.getTagId());
        cb.setOptions(this.getCbOptions());
        cb.setValuefield(this.getCbValuefield());
        cb.setReturnfield(this.getCbReturnfield());
        cb.setDisplayfield(this.getCbDisplayfield());
        cb.setSyscode(this.getCbSyscode());
        cb.setSqltext(this.getCbSqltext());
        cb.setLovcode(this.getCbLovcode());
        cb.setDatasource(this.getCbDatasource());


        cb.set__id(this.get__id());
        cb.set__status(this.get__status());
        cb.set__tls(this.get__tls());
        cb.setSortname(this.getSortname());
        cb.setSortorder(this.getSortorder());
        cb.set_token(this.get_token());
        cb.setRequestId(this.getRequestId());
        cb.setProgramId(this.getProgramId());
        cb.setObjectVersionNumber(this.getObjectVersionNumber());
        cb.setLastUpdateLogin(this.getLastUpdateLogin());
        cb.setCreatedBy(this.getCreatedBy());
        cb.setCreationDate(this.getCreationDate());
        cb.setLastUpdatedBy(this.getLastUpdatedBy());
        cb.setLastUpdateDate(this.getLastUpdateDate());
        cb.setAttributeCategory(this.getAttributeCategory());
        cb.setAttribute1(this.getAttribute1());
        cb.setAttribute2(this.getAttribute2());
        cb.setAttribute3(this.getAttribute3());
        cb.setAttribute4(this.getAttribute4());
        cb.setAttribute5(this.getAttribute5());
        cb.setAttribute6(this.getAttribute6());
        cb.setAttribute7(this.getAttribute7());
        cb.setAttribute8(this.getAttribute8());
        cb.setAttribute9(this.getAttribute9());
        cb.setAttribute10(this.getAttribute10());
        cb.setAttribute11(this.getAttribute11());
        cb.setAttribute12(this.getAttribute12());
        cb.setAttribute13(this.getAttribute13());
        cb.setAttribute14(this.getAttribute14());
        cb.setAttribute15(this.getAttribute15());

        return cb;
    }

    public PageTagDatepicker convertDatepicker() {
        PageTagDatepicker dp = new PageTagDatepicker();
        dp.setTagId(this.getTagId());
        dp.setDayrenderer(this.getDpDayrenderer());
        dp.setEnablebesidedays(this.getDpEnablebesidedays());
        dp.setEnablemonthbtn(this.getDpEnablemonthbtn());
        dp.setViewsize(this.getDpViewsize());
        dp.setRenderer(this.getDpRenderer());


        dp.set__id(this.get__id());
        dp.set__status(this.get__status());
        dp.set__tls(this.get__tls());
        dp.setSortname(this.getSortname());
        dp.setSortorder(this.getSortorder());
        dp.set_token(this.get_token());
        dp.setRequestId(this.getRequestId());
        dp.setProgramId(this.getProgramId());
        dp.setObjectVersionNumber(this.getObjectVersionNumber());
        dp.setLastUpdateLogin(this.getLastUpdateLogin());
        dp.setCreatedBy(this.getCreatedBy());
        dp.setCreationDate(this.getCreationDate());
        dp.setLastUpdatedBy(this.getLastUpdatedBy());
        dp.setLastUpdateDate(this.getLastUpdateDate());
        dp.setAttributeCategory(this.getAttributeCategory());
        dp.setAttribute1(this.getAttribute1());
        dp.setAttribute2(this.getAttribute2());
        dp.setAttribute3(this.getAttribute3());
        dp.setAttribute4(this.getAttribute4());
        dp.setAttribute5(this.getAttribute5());
        dp.setAttribute6(this.getAttribute6());
        dp.setAttribute7(this.getAttribute7());
        dp.setAttribute8(this.getAttribute8());
        dp.setAttribute9(this.getAttribute9());
        dp.setAttribute10(this.getAttribute10());
        dp.setAttribute11(this.getAttribute11());
        dp.setAttribute12(this.getAttribute12());
        dp.setAttribute13(this.getAttribute13());
        dp.setAttribute14(this.getAttribute14());
        dp.setAttribute15(this.getAttribute15());

        return dp;
    }

    public PageTagDatetimepicker convertDatetimepicker() {
        PageTagDatetimepicker dtp = new PageTagDatetimepicker();
        dtp.setTagId(this.getTagId());
        dtp.setDayrenderer(this.getDtpDayrenderer());
        dtp.setEnablebesidedays(this.getDtpEnablebesidedays());
        dtp.setEnablemonthbtn(this.getDtpEnablemonthbtn());
        dtp.setViewsize(this.getDtpViewsize());
        dtp.setRenderer(this.getDtpRenderer());
        dtp.setHour(this.getDtpHour());
        dtp.setMinute(this.getDtpMinute());
        dtp.setSecond(this.getDtpSecond());


        dtp.set__id(this.get__id());
        dtp.set__status(this.get__status());
        dtp.set__tls(this.get__tls());
        dtp.setSortname(this.getSortname());
        dtp.setSortorder(this.getSortorder());
        dtp.set_token(this.get_token());
        dtp.setRequestId(this.getRequestId());
        dtp.setProgramId(this.getProgramId());
        dtp.setObjectVersionNumber(this.getObjectVersionNumber());
        dtp.setLastUpdateLogin(this.getLastUpdateLogin());
        dtp.setCreatedBy(this.getCreatedBy());
        dtp.setCreationDate(this.getCreationDate());
        dtp.setLastUpdatedBy(this.getLastUpdatedBy());
        dtp.setLastUpdateDate(this.getLastUpdateDate());
        dtp.setAttributeCategory(this.getAttributeCategory());
        dtp.setAttribute1(this.getAttribute1());
        dtp.setAttribute2(this.getAttribute2());
        dtp.setAttribute3(this.getAttribute3());
        dtp.setAttribute4(this.getAttribute4());
        dtp.setAttribute5(this.getAttribute5());
        dtp.setAttribute6(this.getAttribute6());
        dtp.setAttribute7(this.getAttribute7());
        dtp.setAttribute8(this.getAttribute8());
        dtp.setAttribute9(this.getAttribute9());
        dtp.setAttribute10(this.getAttribute10());
        dtp.setAttribute11(this.getAttribute11());
        dtp.setAttribute12(this.getAttribute12());
        dtp.setAttribute13(this.getAttribute13());
        dtp.setAttribute14(this.getAttribute14());
        dtp.setAttribute15(this.getAttribute15());

        return dtp;
    }


    public PageTagLabel convertLabel() {
        PageTagLabel label = new PageTagLabel();
        label.setTagId(this.getTagId());
        label.setRenderer(this.getLabelRenderer());


        label.set__id(this.get__id());
        label.set__status(this.get__status());
        label.set__tls(this.get__tls());
        label.setSortname(this.getSortname());
        label.setSortorder(this.getSortorder());
        label.set_token(this.get_token());
        label.setRequestId(this.getRequestId());
        label.setProgramId(this.getProgramId());
        label.setObjectVersionNumber(this.getObjectVersionNumber());
        label.setLastUpdateLogin(this.getLastUpdateLogin());
        label.setCreatedBy(this.getCreatedBy());
        label.setCreationDate(this.getCreationDate());
        label.setLastUpdatedBy(this.getLastUpdatedBy());
        label.setLastUpdateDate(this.getLastUpdateDate());
        label.setAttributeCategory(this.getAttributeCategory());
        label.setAttribute1(this.getAttribute1());
        label.setAttribute2(this.getAttribute2());
        label.setAttribute3(this.getAttribute3());
        label.setAttribute4(this.getAttribute4());
        label.setAttribute5(this.getAttribute5());
        label.setAttribute6(this.getAttribute6());
        label.setAttribute7(this.getAttribute7());
        label.setAttribute8(this.getAttribute8());
        label.setAttribute9(this.getAttribute9());
        label.setAttribute10(this.getAttribute10());
        label.setAttribute11(this.getAttribute11());
        label.setAttribute12(this.getAttribute12());
        label.setAttribute13(this.getAttribute13());
        label.setAttribute14(this.getAttribute14());
        label.setAttribute15(this.getAttribute15());

        return label;
    }

    public PageTagLov convertLov() {
        PageTagLov lov = new PageTagLov();
        lov.setTagId(this.getTagId());
        lov.setLovcode(this.getLovLovcode());
        lov.setLovurl(this.getLovLovurl());
        lov.setLovautoquery(this.getLovLovautoquery());
        lov.setLovgridheight(this.getLovLovgridheight());
        lov.setLovheight(this.getLovLovheight());
        lov.setLovwidth(this.getLovLovwidth());
        lov.setLovlabelwidth(this.getLovLovlabelwidth());
        lov.setAutocomplete(this.getLovAutocomplete());
        lov.setAutocompletefield(this.getLovAutocompletefield());
        lov.setTitle(this.getLovTitle());
        lov.setSqltext(this.getLovSqltext());
        lov.setSyscode(this.getLovSyscode());
        lov.setDatasource(this.getLovDatasource());


        lov.set__id(this.get__id());
        lov.set__status(this.get__status());
        lov.set__tls(this.get__tls());
        lov.setSortname(this.getSortname());
        lov.setSortorder(this.getSortorder());
        lov.set_token(this.get_token());
        lov.setRequestId(this.getRequestId());
        lov.setProgramId(this.getProgramId());
        lov.setObjectVersionNumber(this.getObjectVersionNumber());
        lov.setLastUpdateLogin(this.getLastUpdateLogin());
        lov.setCreatedBy(this.getCreatedBy());
        lov.setCreationDate(this.getCreationDate());
        lov.setLastUpdatedBy(this.getLastUpdatedBy());
        lov.setLastUpdateDate(this.getLastUpdateDate());
        lov.setAttributeCategory(this.getAttributeCategory());
        lov.setAttribute1(this.getAttribute1());
        lov.setAttribute2(this.getAttribute2());
        lov.setAttribute3(this.getAttribute3());
        lov.setAttribute4(this.getAttribute4());
        lov.setAttribute5(this.getAttribute5());
        lov.setAttribute6(this.getAttribute6());
        lov.setAttribute7(this.getAttribute7());
        lov.setAttribute8(this.getAttribute8());
        lov.setAttribute9(this.getAttribute9());
        lov.setAttribute10(this.getAttribute10());
        lov.setAttribute11(this.getAttribute11());
        lov.setAttribute12(this.getAttribute12());
        lov.setAttribute13(this.getAttribute13());
        lov.setAttribute14(this.getAttribute14());
        lov.setAttribute15(this.getAttribute15());

        return lov;
    }

    public PageTagNumberfield convertNumberfield() {
        PageTagNumberfield nf = new PageTagNumberfield();
        nf.setTagId(this.getTagId());
        nf.setAllowdecimals(this.getNfAllowdecimals());
        nf.setDecimalprecision(this.getNfDecimalprecision());
        nf.setAllownegative(this.getNfAllownegative());
        nf.setAllowformat(this.getNfAllowformat());


        nf.set__id(this.get__id());
        nf.set__status(this.get__status());
        nf.set__tls(this.get__tls());
        nf.setSortname(this.getSortname());
        nf.setSortorder(this.getSortorder());
        nf.set_token(this.get_token());
        nf.setRequestId(this.getRequestId());
        nf.setProgramId(this.getProgramId());
        nf.setObjectVersionNumber(this.getObjectVersionNumber());
        nf.setLastUpdateLogin(this.getLastUpdateLogin());
        nf.setCreatedBy(this.getCreatedBy());
        nf.setCreationDate(this.getCreationDate());
        nf.setLastUpdatedBy(this.getLastUpdatedBy());
        nf.setLastUpdateDate(this.getLastUpdateDate());
        nf.setAttributeCategory(this.getAttributeCategory());
        nf.setAttribute1(this.getAttribute1());
        nf.setAttribute2(this.getAttribute2());
        nf.setAttribute3(this.getAttribute3());
        nf.setAttribute4(this.getAttribute4());
        nf.setAttribute5(this.getAttribute5());
        nf.setAttribute6(this.getAttribute6());
        nf.setAttribute7(this.getAttribute7());
        nf.setAttribute8(this.getAttribute8());
        nf.setAttribute9(this.getAttribute9());
        nf.setAttribute10(this.getAttribute10());
        nf.setAttribute11(this.getAttribute11());
        nf.setAttribute12(this.getAttribute12());
        nf.setAttribute13(this.getAttribute13());
        nf.setAttribute14(this.getAttribute14());
        nf.setAttribute15(this.getAttribute15());

        return nf;
    }

    public PageTagRadio convertRadio() {
        PageTagRadio radio = new PageTagRadio();
        radio.setTagId(this.getTagId());
        radio.setOptions(this.getRadioOptions());
        radio.setValuefield(this.getRadioValuefield());
        radio.setLabelexpression(this.getRadioLabelexpression());
        radio.setLabelfield(this.getRadioLabelfield());
        radio.setLayout(this.getRadioLayout());
        radio.setSyscode(this.getRadioSyscode());
        radio.setSqltext(this.getRadioSqltext());
        radio.setDatasource(this.getRadioDatasource());


        radio.set__id(this.get__id());
        radio.set__status(this.get__status());
        radio.set__tls(this.get__tls());
        radio.setSortname(this.getSortname());
        radio.setSortorder(this.getSortorder());
        radio.set_token(this.get_token());
        radio.setRequestId(this.getRequestId());
        radio.setProgramId(this.getProgramId());
        radio.setObjectVersionNumber(this.getObjectVersionNumber());
        radio.setLastUpdateLogin(this.getLastUpdateLogin());
        radio.setCreatedBy(this.getCreatedBy());
        radio.setCreationDate(this.getCreationDate());
        radio.setLastUpdatedBy(this.getLastUpdatedBy());
        radio.setLastUpdateDate(this.getLastUpdateDate());
        radio.setAttributeCategory(this.getAttributeCategory());
        radio.setAttribute1(this.getAttribute1());
        radio.setAttribute2(this.getAttribute2());
        radio.setAttribute3(this.getAttribute3());
        radio.setAttribute4(this.getAttribute4());
        radio.setAttribute5(this.getAttribute5());
        radio.setAttribute6(this.getAttribute6());
        radio.setAttribute7(this.getAttribute7());
        radio.setAttribute8(this.getAttribute8());
        radio.setAttribute9(this.getAttribute9());
        radio.setAttribute10(this.getAttribute10());
        radio.setAttribute11(this.getAttribute11());
        radio.setAttribute12(this.getAttribute12());
        radio.setAttribute13(this.getAttribute13());
        radio.setAttribute14(this.getAttribute14());
        radio.setAttribute15(this.getAttribute15());

        return radio;
    }

    public PageTagTextfield convertTextfield() {
        PageTagTextfield tf = new PageTagTextfield();
        tf.setTagId(this.getTagId());
        tf.setTypecase(this.getTfTypecase());


        tf.set__id(this.get__id());
        tf.set__status(this.get__status());
        tf.set__tls(this.get__tls());
        tf.setSortname(this.getSortname());
        tf.setSortorder(this.getSortorder());
        tf.set_token(this.get_token());
        tf.setRequestId(this.getRequestId());
        tf.setProgramId(this.getProgramId());
        tf.setObjectVersionNumber(this.getObjectVersionNumber());
        tf.setLastUpdateLogin(this.getLastUpdateLogin());
        tf.setCreatedBy(this.getCreatedBy());
        tf.setCreationDate(this.getCreationDate());
        tf.setLastUpdatedBy(this.getLastUpdatedBy());
        tf.setLastUpdateDate(this.getLastUpdateDate());
        tf.setAttributeCategory(this.getAttributeCategory());
        tf.setAttribute1(this.getAttribute1());
        tf.setAttribute2(this.getAttribute2());
        tf.setAttribute3(this.getAttribute3());
        tf.setAttribute4(this.getAttribute4());
        tf.setAttribute5(this.getAttribute5());
        tf.setAttribute6(this.getAttribute6());
        tf.setAttribute7(this.getAttribute7());
        tf.setAttribute8(this.getAttribute8());
        tf.setAttribute9(this.getAttribute9());
        tf.setAttribute10(this.getAttribute10());
        tf.setAttribute11(this.getAttribute11());
        tf.setAttribute12(this.getAttribute12());
        tf.setAttribute13(this.getAttribute13());
        tf.setAttribute14(this.getAttribute14());
        tf.setAttribute15(this.getAttribute15());

        return tf;
    }

    public PageTag convertTag(PageTagBasic basic, PageTagCheckbox ck, PageTagCombobox cb, PageTagDatepicker dp, PageTagDatetimepicker dtp, PageTagLabel label, PageTagLov lov, PageTagNumberfield nf, PageTagRadio radio, PageTagTextfield tf) {
        this.setTagId(basic.getTagId());
        this.setLayoutId(basic.getLayoutId());
        this.setTagSequence(basic.getTagSequence());
        this.setTagCode(basic.getTagCode());
        this.setTagDesc(basic.getTagDesc());
        this.setTagType(basic.getTagType());
        this.setTemplateFlag(basic.getTemplateFlag());
        this.setFieldId(basic.getFieldId());
        this.setName(basic.getName());
        this.setDefaultvalue(basic.getDefaultvalue());
        this.setReadonly(basic.getReadonly());
        this.setRequired(basic.getRequired());
        this.setPrompt(basic.getPrompt());
        this.setValidator(basic.getValidator());
        this.setRequiredmessage(basic.getRequiredmessage());
        this.setWidth(basic.getWidth());
        this.setId(basic.getId());
        this.setBindtarget(basic.getBindtarget());
        this.setHeight(basic.getHeight());
        this.setStyle(basic.getStyle());
        this.setColspan(basic.getColspan());
        this.setRowspan(basic.getRowspan());
        this.setHidden(basic.getHidden());
        this.setParentTagId(basic.getParentTagId());
        this.setAlign(basic.getAlign());
        this.setEditor(basic.getEditor());
        this.setEditorfunction(basic.getEditorfunction());
        this.setFooterrenderer(basic.getFooterrenderer());
        this.setLockFlag(basic.getLockFlag());
        this.setRenderer(basic.getRenderer());
        this.setResizable(basic.getResizable());
        this.setSortable(basic.getSortable());
        this.setFooterrendererJs(basic.getFooterrenderer());
        this.setPrintable(basic.getPrintable());
        this.setFieldSource(basic.getFieldSource());
        this.setAppHideFlag(basic.getAppHideFlag());
        this.setParentName(basic.getParentName());

        this.set__id(basic.get__id());
        this.set__status(basic.get__status());
        this.set__tls(basic.get__tls());
        this.setSortname(basic.getSortname());
        this.setSortorder(basic.getSortorder());
        this.set_token(basic.get_token());
        this.setRequestId(basic.getRequestId());
        this.setProgramId(basic.getProgramId());
//        this.setObjectVersionNumber(basic.getObjectVersionNumber());
        this.setLastUpdateLogin(basic.getLastUpdateLogin());
        this.setCreatedBy(basic.getCreatedBy());
        this.setCreationDate(basic.getCreationDate());
        this.setLastUpdatedBy(basic.getLastUpdatedBy());
        this.setLastUpdateDate(basic.getLastUpdateDate());
        this.setAttributeCategory(basic.getAttributeCategory());
        this.setAttribute1(basic.getAttribute1());
        this.setAttribute2(basic.getAttribute2());
        this.setAttribute3(basic.getAttribute3());
        this.setAttribute4(basic.getAttribute4());
        this.setAttribute5(basic.getAttribute5());
        this.setAttribute6(basic.getAttribute6());
        this.setAttribute7(basic.getAttribute7());
        this.setAttribute8(basic.getAttribute8());
        this.setAttribute9(basic.getAttribute9());
        this.setAttribute10(basic.getAttribute10());
        this.setAttribute11(basic.getAttribute11());
        this.setAttribute12(basic.getAttribute12());
        this.setAttribute13(basic.getAttribute13());
        this.setAttribute14(basic.getAttribute14());
        this.setAttribute15(basic.getAttribute15());


        if (ck != null) {
            this.setCkCheckedvalue(ck.getCheckedvalue());
            this.setCkUncheckedvalue(ck.getUncheckedvalue());
            this.setCkLabel(ck.getLabel());
        }

        if (cb != null) {
            this.setCbOptions(cb.getOptions());
            this.setCbValuefield(cb.getValuefield());
            this.setCbReturnfield(cb.getReturnfield());
            this.setCbDisplayfield(cb.getDisplayfield());
            this.setCbSyscode(cb.getSyscode());
            this.setCbLovcode(cb.getLovcode());
            this.setCbSqltext(cb.getSqltext());
            this.setCbDatasource(cb.getDatasource());
        }

        if (dp != null) {
            this.setDpDayrenderer(dp.getDayrenderer());
            this.setDpEnablebesidedays(dp.getEnablebesidedays());
            this.setDpEnablemonthbtn(dp.getEnablemonthbtn());
            this.setDpViewsize(dp.getViewsize());
            this.setDpRenderer(dp.getRenderer());
        }

        if (dtp != null) {
            this.setDtpDayrenderer(dtp.getDayrenderer());
            this.setDtpEnablebesidedays(dtp.getEnablebesidedays());
            this.setDtpEnablemonthbtn(dtp.getEnablemonthbtn());
            this.setDtpViewsize(dtp.getViewsize());
            this.setDtpRenderer(dtp.getRenderer());
            this.setDtpHour(dtp.getHour());
            this.setDtpMinute(dtp.getMinute());
            this.setDtpSecond(dtp.getSecond());
        }

        if (label != null) {
            this.setLabelRenderer(label.getRenderer());
        }

        if (lov != null) {
            this.setLovLovcode(lov.getLovcode());
            this.setLovLovurl(lov.getLovurl());
            this.setLovLovautoquery(lov.getLovautoquery());
            this.setLovLovgridheight(lov.getLovgridheight());
            this.setLovLovheight(lov.getLovheight());
            this.setLovLovwidth(lov.getLovwidth());
            this.setLovLovlabelwidth(lov.getLovlabelwidth());
            this.setLovAutocomplete(lov.getAutocomplete());
            this.setLovAutocompletefield(lov.getAutocompletefield());
            this.setLovTitle(lov.getTitle());
            this.setLovSqltext(lov.getSqltext());
            this.setLovSyscode(lov.getSyscode());
            this.setLovDatasource(lov.getDatasource());
        }

        if (nf != null) {
            this.setNfAllowdecimals(nf.getAllowdecimals());
            this.setNfDecimalprecision(nf.getDecimalprecision());
            this.setNfAllownegative(nf.getAllownegative());
            this.setNfAllowformat(nf.getAllowformat());
        }

        if (radio != null) {
            this.setRadioOptions(radio.getOptions());
            this.setRadioValuefield(radio.getValuefield());
            this.setRadioLabelexpression(radio.getLabelexpression());
            this.setRadioLabelfield(radio.getLabelfield());
            this.setRadioLayout(radio.getLayout());
            this.setRadioSyscode(radio.getSyscode());
            this.setRadioSqltext(radio.getSqltext());
            this.setRadioDatasource(radio.getDatasource());
        }

        if (tf != null) {
            this.setTfTypecase(tf.getTypecase());
        }

        return this;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getLayoutId() {
        return layoutId;
    }

    public void setLayoutId(Long layoutId) {
        this.layoutId = layoutId;
    }

    public Long getTagSequence() {
        return tagSequence;
    }

    public void setTagSequence(Long tagSequence) {
        this.tagSequence = tagSequence;
    }

    public String getTagCode() {
        return tagCode;
    }

    public void setTagCode(String tagCode) {
        this.tagCode = tagCode;
    }

    public String getTagDesc() {
        return tagDesc;
    }

    public void setTagDesc(String tagDesc) {
        this.tagDesc = tagDesc;
    }

    public String getTagType() {
        return tagType;
    }

    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    public String getTagTypeDesc() {
        return tagTypeDesc;
    }

    public void setTagTypeDesc(String tagTypeDesc) {
        this.tagTypeDesc = tagTypeDesc;
    }

    public String getTemplateFlag() {
        return templateFlag;
    }

    public void setTemplateFlag(String templateFlag) {
        this.templateFlag = templateFlag;
    }

    public Long getFieldId() {
        return fieldId;
    }

    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDefaultvalue() {
        return defaultvalue;
    }

    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    public String getReadonly() {
        return readonly;
    }

    public void setReadonly(String readonly) {
        this.readonly = readonly;
    }

    public String getRequired() {
        return required;
    }

    public void setRequired(String required) {
        this.required = required;
    }

    public String getPrompt() {
        return prompt;
    }

    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }

    public String getPromptDesc() {
        return promptDesc;
    }

    public void setPromptDesc(String promptDesc) {
        this.promptDesc = promptDesc;
    }

    public String getValidator() {
        return validator;
    }

    public void setValidator(String validator) {
        this.validator = validator;
    }

    public String getRequiredmessage() {
        return requiredmessage;
    }

    public void setRequiredmessage(String requiredmessage) {
        this.requiredmessage = requiredmessage;
    }

    public Long getWidth() {
        return width;
    }

    public void setWidth(Long width) {
        this.width = width;
    }

    public Long getCloumnwidth() {
        return cloumnwidth;
    }

    public void setCloumnwidth(Long cloumnwidth) {
        this.cloumnwidth = cloumnwidth;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBindtarget() {
        return bindtarget;
    }

    public void setBindtarget(String bindtarget) {
        this.bindtarget = bindtarget;
    }

    public Long getHeight() {
        return height;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public Long getColspan() {
        return colspan;
    }

    public void setColspan(Long colspan) {
        this.colspan = colspan;
    }

    public Long getRowspan() {
        return rowspan;
    }

    public void setRowspan(Long rowspan) {
        this.rowspan = rowspan;
    }

    public String getHidden() {
        return hidden;
    }

    public void setHidden(String hidden) {
        this.hidden = hidden;
    }

    public Long getParentTagId() {
        return parentTagId;
    }

    public void setParentTagId(Long parentTagId) {
        this.parentTagId = parentTagId;
    }

    public String getParentTagDesc() {
        return parentTagDesc;
    }

    public void setParentTagDesc(String parentTagDesc) {
        this.parentTagDesc = parentTagDesc;
    }

    public String getAlign() {
        return align;
    }

    public void setAlign(String align) {
        this.align = align;
    }

    public String getEditor() {
        return editor;
    }

    public void setEditor(String editor) {
        this.editor = editor;
    }

    public String getEditorfunction() {
        return editorfunction;
    }

    public void setEditorfunction(String editorfunction) {
        this.editorfunction = editorfunction;
    }

    public String getFooterrenderer() {
        return footerrenderer;
    }

    public void setFooterrenderer(String footerrenderer) {
        this.footerrenderer = footerrenderer;
    }

    public String getLockFlag() {
        return lockFlag;
    }

    public void setLockFlag(String lockFlag) {
        this.lockFlag = lockFlag;
    }

    public String getRenderer() {
        return renderer;
    }

    public void setRenderer(String renderer) {
        this.renderer = renderer;
    }

    public String getResizable() {
        return resizable;
    }

    public void setResizable(String resizable) {
        this.resizable = resizable;
    }

    public String getSortable() {
        return sortable;
    }

    public void setSortable(String sortable) {
        this.sortable = sortable;
    }

    public String getAppHideFlag() {
        return appHideFlag;
    }

    public void setAppHideFlag(String appHideFlag) {
        this.appHideFlag = appHideFlag;
    }

    public String getTfTypecase() {
        return tfTypecase;
    }

    public void setTfTypecase(String tfTypecase) {
        this.tfTypecase = tfTypecase;
    }

    public String getNfAllowdecimals() {
        return nfAllowdecimals;
    }

    public void setNfAllowdecimals(String nfAllowdecimals) {
        this.nfAllowdecimals = nfAllowdecimals;
    }

    public Long getNfDecimalprecision() {
        return nfDecimalprecision;
    }

    public void setNfDecimalprecision(Long nfDecimalprecision) {
        this.nfDecimalprecision = nfDecimalprecision;
    }

    public String getNfAllownegative() {
        return nfAllownegative;
    }

    public void setNfAllownegative(String nfAllownegative) {
        this.nfAllownegative = nfAllownegative;
    }

    public String getNfAllowformat() {
        return nfAllowformat;
    }

    public void setNfAllowformat(String nfAllowformat) {
        this.nfAllowformat = nfAllowformat;
    }

    public String getCbDatasource() {
        return cbDatasource;
    }

    public void setCbDatasource(String cbDatasource) {
        this.cbDatasource = cbDatasource;
    }

    public String getCbOptions() {
        return cbOptions;
    }

    public void setCbOptions(String cbOptions) {
        this.cbOptions = cbOptions;
    }

    public String getCbValuefield() {
        return cbValuefield;
    }

    public void setCbValuefield(String cbValuefield) {
        this.cbValuefield = cbValuefield;
    }

    public String getCbReturnfield() {
        return cbReturnfield;
    }

    public void setCbReturnfield(String cbReturnfield) {
        this.cbReturnfield = cbReturnfield;
    }

    public String getCbReturnfieldDesc() {
        return cbReturnfieldDesc;
    }

    public void setCbReturnfieldDesc(String cbReturnfieldDesc) {
        this.cbReturnfieldDesc = cbReturnfieldDesc;
    }

    public String getCbDisplayfield() {
        return cbDisplayfield;
    }

    public void setCbDisplayfield(String cbDisplayfield) {
        this.cbDisplayfield = cbDisplayfield;
    }

    public String getCbSyscode() {
        return cbSyscode;
    }

    public void setCbSyscode(String cbSyscode) {
        this.cbSyscode = cbSyscode;
    }

    public String getCbSqltext() {
        return cbSqltext;
    }

    public void setCbSqltext(String cbSqltext) {
        this.cbSqltext = cbSqltext;
    }

    public String getLovDatasource() {
        return lovDatasource;
    }

    public void setLovDatasource(String lovDatasource) {
        this.lovDatasource = lovDatasource;
    }

    public String getLovLovcode() {
        return lovLovcode;
    }

    public void setLovLovcode(String lovLovcode) {
        this.lovLovcode = lovLovcode;
    }

    public String getLovLovurl() {
        return lovLovurl;
    }

    public void setLovLovurl(String lovLovurl) {
        this.lovLovurl = lovLovurl;
    }

    public String getLovLovautoquery() {
        return lovLovautoquery;
    }

    public void setLovLovautoquery(String lovLovautoquery) {
        this.lovLovautoquery = lovLovautoquery;
    }

    public Long getLovLovgridheight() {
        return lovLovgridheight;
    }

    public void setLovLovgridheight(Long lovLovgridheight) {
        this.lovLovgridheight = lovLovgridheight;
    }

    public Long getLovLovheight() {
        return lovLovheight;
    }

    public void setLovLovheight(Long lovLovheight) {
        this.lovLovheight = lovLovheight;
    }

    public Long getLovLovwidth() {
        return lovLovwidth;
    }

    public void setLovLovwidth(Long lovLovwidth) {
        this.lovLovwidth = lovLovwidth;
    }

    public Long getLovLovlabelwidth() {
        return lovLovlabelwidth;
    }

    public void setLovLovlabelwidth(Long lovLovlabelwidth) {
        this.lovLovlabelwidth = lovLovlabelwidth;
    }

    public String getLovAutocomplete() {
        return lovAutocomplete;
    }

    public void setLovAutocomplete(String lovAutocomplete) {
        this.lovAutocomplete = lovAutocomplete;
    }

    public String getLovAutocompletefield() {
        return lovAutocompletefield;
    }

    public void setLovAutocompletefield(String lovAutocompletefield) {
        this.lovAutocompletefield = lovAutocompletefield;
    }

    public String getLovTitle() {
        return lovTitle;
    }

    public void setLovTitle(String lovTitle) {
        this.lovTitle = lovTitle;
    }

    public String getLovSqltext() {
        return lovSqltext;
    }

    public void setLovSqltext(String lovSqltext) {
        this.lovSqltext = lovSqltext;
    }

    public String getLovSyscode() {
        return lovSyscode;
    }

    public void setLovSyscode(String lovSyscode) {
        this.lovSyscode = lovSyscode;
    }

    public String getLabelRenderer() {
        return labelRenderer;
    }

    public void setLabelRenderer(String labelRenderer) {
        this.labelRenderer = labelRenderer;
    }

    public String getRadioDatasource() {
        return radioDatasource;
    }

    public void setRadioDatasource(String radioDatasource) {
        this.radioDatasource = radioDatasource;
    }

    public String getRadioOptions() {
        return radioOptions;
    }

    public void setRadioOptions(String radioOptions) {
        this.radioOptions = radioOptions;
    }

    public String getRadioValuefield() {
        return radioValuefield;
    }

    public void setRadioValuefield(String radioValuefield) {
        this.radioValuefield = radioValuefield;
    }

    public String getRadioLabelexpression() {
        return radioLabelexpression;
    }

    public void setRadioLabelexpression(String radioLabelexpression) {
        this.radioLabelexpression = radioLabelexpression;
    }

    public String getRadioLabelfield() {
        return radioLabelfield;
    }

    public void setRadioLabelfield(String radioLabelfield) {
        this.radioLabelfield = radioLabelfield;
    }

    public String getRadioLayout() {
        return radioLayout;
    }

    public void setRadioLayout(String radioLayout) {
        this.radioLayout = radioLayout;
    }

    public String getRadioSyscode() {
        return radioSyscode;
    }

    public void setRadioSyscode(String radioSyscode) {
        this.radioSyscode = radioSyscode;
    }

    public String getRadioSqltext() {
        return radioSqltext;
    }

    public void setRadioSqltext(String radioSqltext) {
        this.radioSqltext = radioSqltext;
    }

    public String getCkCheckedvalue() {
        return ckCheckedvalue;
    }

    public void setCkCheckedvalue(String ckCheckedvalue) {
        this.ckCheckedvalue = ckCheckedvalue;
    }

    public String getCkUncheckedvalue() {
        return ckUncheckedvalue;
    }

    public void setCkUncheckedvalue(String ckUncheckedvalue) {
        this.ckUncheckedvalue = ckUncheckedvalue;
    }

    public String getCkLabel() {
        return ckLabel;
    }

    public void setCkLabel(String ckLabel) {
        this.ckLabel = ckLabel;
    }

    public String getDpDayrenderer() {
        return dpDayrenderer;
    }

    public void setDpDayrenderer(String dpDayrenderer) {
        this.dpDayrenderer = dpDayrenderer;
    }

    public String getDpEnablebesidedays() {
        return dpEnablebesidedays;
    }

    public void setDpEnablebesidedays(String dpEnablebesidedays) {
        this.dpEnablebesidedays = dpEnablebesidedays;
    }

    public String getDpEnablemonthbtn() {
        return dpEnablemonthbtn;
    }

    public void setDpEnablemonthbtn(String dpEnablemonthbtn) {
        this.dpEnablemonthbtn = dpEnablemonthbtn;
    }

    public Long getDpViewsize() {
        return dpViewsize;
    }

    public void setDpViewsize(Long dpViewsize) {
        this.dpViewsize = dpViewsize;
    }

    public String getDpRenderer() {
        return dpRenderer;
    }

    public void setDpRenderer(String dpRenderer) {
        this.dpRenderer = dpRenderer;
    }

    public String getDtpDayrenderer() {
        return dtpDayrenderer;
    }

    public void setDtpDayrenderer(String dtpDayrenderer) {
        this.dtpDayrenderer = dtpDayrenderer;
    }

    public String getDtpEnablebesidedays() {
        return dtpEnablebesidedays;
    }

    public void setDtpEnablebesidedays(String dtpEnablebesidedays) {
        this.dtpEnablebesidedays = dtpEnablebesidedays;
    }

    public String getDtpEnablemonthbtn() {
        return dtpEnablemonthbtn;
    }

    public void setDtpEnablemonthbtn(String dtpEnablemonthbtn) {
        this.dtpEnablemonthbtn = dtpEnablemonthbtn;
    }

    public Long getDtpViewsize() {
        return dtpViewsize;
    }

    public void setDtpViewsize(Long dtpViewsize) {
        this.dtpViewsize = dtpViewsize;
    }

    public String getDtpRenderer() {
        return dtpRenderer;
    }

    public void setDtpRenderer(String dtpRenderer) {
        this.dtpRenderer = dtpRenderer;
    }

    public Long getDtpHour() {
        return dtpHour;
    }

    public void setDtpHour(Long dtpHour) {
        this.dtpHour = dtpHour;
    }

    public Long getDtpMinute() {
        return dtpMinute;
    }

    public void setDtpMinute(Long dtpMinute) {
        this.dtpMinute = dtpMinute;
    }

    public Long getDtpSecond() {
        return dtpSecond;
    }

    public void setDtpSecond(Long dtpSecond) {
        this.dtpSecond = dtpSecond;
    }

    public String getPrintable() {
        return printable;
    }

    public void setPrintable(String printable) {
        this.printable = printable;
    }

    public String getFieldSource() {
        return fieldSource;
    }

    public void setFieldSource(String fieldSource) {
        this.fieldSource = fieldSource;
    }

    public String getFooterrendererJs() {
        return footerrendererJs;
    }

    public void setFooterrendererJs(String footerrendererJs) {
        this.footerrendererJs = footerrendererJs;
    }


    public String getCbLovcode() {
        return cbLovcode;
    }

    public void setCbLovcode(String cbLovcode) {
        this.cbLovcode = cbLovcode;
    }
}
