package com.hand.hec.bpm.dto;

/**Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_combobox_field")
public class PageTagComboboxField extends BaseDTO {

    public static final String FIELD_COMBOBOX_FIELD_ID = "comboboxFieldId";
    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_COMBOBOX_FIELD = "comboboxField";


    @Id
    @GeneratedValue
    @Where
    private Long comboboxFieldId;//PK

    @Where
    private Long tagId;//标签ID

    @NotEmpty
    @Length(max = 23)
    private String comboboxField;//字段


    public void setComboboxFieldId(Long comboboxFieldId){
        this.comboboxFieldId = comboboxFieldId;
    }

    public Long getComboboxFieldId(){
        return comboboxFieldId;
    }

    public void setTagId(Long tagId){
        this.tagId = tagId;
    }

    public Long getTagId(){
        return tagId;
    }

    public void setComboboxField(String comboboxField){
        this.comboboxField = comboboxField;
    }

    public String getComboboxField(){
        return comboboxField;
    }

}
