package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_radio")
public class PageTagRadio extends BaseDTO {

    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_OPTIONS = "options";
    public static final String FIELD_VALUEFIELD = "valuefield";
    public static final String FIELD_LABELEXPRESSION = "labelexpression";
    public static final String FIELD_LABELFIELD = "labelfield";
    public static final String FIELD_LAYOUT = "layout";
    public static final String FIELD_SYSCODE = "syscode";
    public static final String FIELD_SQLTEXT = "sqltext";
    public static final String FIELD_DATASOURCE = "datasource";


    @Id
    private Long tagId;//标签ID

    @Length(max = 200)
    private String options;//指定选项集的model地址

    @Length(max = 200)
    private String valuefield;//选项集的dataset中用来定义选项被选中后的值的field

    @Length(max = 200)
    private String labelexpression;//选项的描述

    @Length(max = 200)
    private String labelfield;//选项集的dataset中用来显示选项描述的field

    @Length(max = 200)
    private String layout;//选项布局

    @Length(max = 200)
    private String syscode;//指定SYSCODE系列

    @Length(max = 200)
    private String sqltext;//SQL语句自动生成系列

    @Length(max = 200)
    private String datasource;//取数来源 SYS_CODE/OPTIONS


    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setOptions(String options) {
        this.options = options;
    }

    public String getOptions() {
        return options;
    }

    public void setValuefield(String valuefield) {
        this.valuefield = valuefield;
    }

    public String getValuefield() {
        return valuefield;
    }

    public void setLabelexpression(String labelexpression) {
        this.labelexpression = labelexpression;
    }

    public String getLabelexpression() {
        return labelexpression;
    }

    public void setLabelfield(String labelfield) {
        this.labelfield = labelfield;
    }

    public String getLabelfield() {
        return labelfield;
    }

    public void setLayout(String layout) {
        this.layout = layout;
    }

    public String getLayout() {
        return layout;
    }

    public void setSyscode(String syscode) {
        this.syscode = syscode;
    }

    public String getSyscode() {
        return syscode;
    }

    public void setSqltext(String sqltext) {
        this.sqltext = sqltext;
    }

    public String getSqltext() {
        return sqltext;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    public String getDatasource() {
        return datasource;
    }

}
