package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_numberfield")
public class PageTagNumberfield extends BaseDTO {

    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_ALLOWDECIMALS = "allowdecimals";
    public static final String FIELD_DECIMALPRECISION = "decimalprecision";
    public static final String FIELD_ALLOWNEGATIVE = "allownegative";
    public static final String FIELD_ALLOWFORMAT = "allowformat";


    @Id
    private Long tagId;//标签ID

    @Length(max = 200)
    private String allowdecimals;//允许小数输入

    private Long decimalprecision;//小数精度

    @Length(max = 200)
    private String allownegative;//允许负数输入

    @Length(max = 200)
    private String allowformat;//允许格式化


    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setAllowdecimals(String allowdecimals) {
        this.allowdecimals = allowdecimals;
    }

    public String getAllowdecimals() {
        return allowdecimals;
    }

    public void setDecimalprecision(Long decimalprecision) {
        this.decimalprecision = decimalprecision;
    }

    public Long getDecimalprecision() {
        return decimalprecision;
    }

    public void setAllownegative(String allowengative) {
        this.allownegative = allownegative;
    }

    public String getAllownegative() {
        return allownegative;
    }

    public void setAllowformat(String allowformat) {
        this.allowformat = allowformat;
    }

    public String getAllowformat() {
        return allowformat;
    }

}
