package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_layout_form")
public class PageLayoutForm extends BaseDTO {

    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_PROMPT = "prompt";
    public static final String FIELD_TITLE = "title";
    public static final String FIELD_COLUMN_NUM = "columnNum";
    public static final String FIELD_ROW_NUM = "rowNum";
    public static final String FIELD_LABELWIDTH = "labelwidth";
    public static final String FIELD_LABELSEPARATOR = "labelseparator";


    @Id
    @Where
    private Long layoutId;//布局组件ID

    @Length(max = 200)
    private String prompt;//描述

    @Length(max = 200)
    private String title;//标题

    private Long columnNum;//列数

    private Long rowNum;//行数

    private Long labelwidth;//标签宽度

    @Length(max = 200)
    private String labelseparator;//标签分割符

    public void setLayoutId(Long layoutId) {
        this.layoutId = layoutId;
    }

    public Long getLayoutId() {
        return layoutId;
    }

    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }

    public String getPrompt() {
        return prompt;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setColumnNum(Long columnNum) {
        this.columnNum = columnNum;
    }

    public Long getColumnNum() {
        return columnNum;
    }

    public void setRowNum(Long rowNum) {
        this.rowNum = rowNum;
    }

    public Long getRowNum() {
        return rowNum;
    }

    public void setLabelwidth(Long labelwidth) {
        this.labelwidth = labelwidth;
    }

    public Long getLabelwidth() {
        return labelwidth;
    }

    public void setLabelseparator(String labelseparator) {
        this.labelseparator = labelseparator;
    }

    public String getLabelseparator() {
        return labelseparator;
    }

    public PageLayoutForm() {
    }

    public PageLayoutForm(TpltLayoutForm bpmTpltLayoutForm, Long pageLayoutId) {
        this.setLayoutId(pageLayoutId);
        this.setPrompt(bpmTpltLayoutForm.getPrompt());
        this.setTitle(bpmTpltLayoutForm.getTitle());
        this.setColumnNum(bpmTpltLayoutForm.getColumnNum());
        this.setRowNum(bpmTpltLayoutForm.getRowNum());
        this.setLabelwidth(bpmTpltLayoutForm.getLabelwidth());
        this.setLabelseparator(bpmTpltLayoutForm.getLabelseparator());
    }

}
