package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_layout_basic")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class PageLayoutBasic extends BaseDTO {

    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_PAGE_ID = "pageId";
    public static final String FIELD_LAYOUT_SEQUENCE = "layoutSequence";
    public static final String FIELD_LAYOUT_CODE = "layoutCode";
    public static final String FIELD_LAYOUT_DESC = "layoutDesc";
    public static final String FIELD_LAYOUT_TYPE = "layoutType";
    public static final String FIELD_ENTITY_ID = "entityId";
    public static final String FIELD_PARENT_LAYOUT_ID = "parentLayoutId";
    public static final String FIELD_LAYOUT_LEVEL = "layoutLevel";
    public static final String FIELD_TEMPLATE_FLAG = "templateFlag";
    public static final String FIELD_DATASET = "dataset";
    public static final String FIELD_TAB_GROUP_NUMBER = "tabGroupNumber";
    public static final String FIELD_ID = "id";
    public static final String FIELD_WIDTH = "width";
    public static final String FIELD_HEIGHT = "height";
    public static final String FIELD_MARGINWIDTH = "marginwidth";
    public static final String FIELD_MARGINHEIGHT = "marginheight";
    public static final String FIELD_STYLE = "style";
    public static final String FIELD_HIDDEN = "hidden";
    public static final String FIELD_BUSINESS_CATEGORY = "businessCategory";
    public static final String FIELD_PARENT_BUSINESS_CATEGORY = "parentBusinessCategory";
    public static final String FIELD_REF_TABLE = "refTable";
    public static final String FIELD_REF_FIELD = "refField";
    public static final String FIELD_WRITE_BACK_PROGRAM = "writeBackProgram";

    /**
     * 布局组件ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long layoutId;

    /**
     * 所属模板ID
     */
    @Where
    private Long pageId;

    /**
     * 布局组件顺序
     */
    private Long layoutSequence;

    /**
     * 布局组件代码
     */
    @NotEmpty
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String layoutCode;

    /**
     * 布局组件描述
     */
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String layoutDesc;

    /**
     * 布局组件类型，form ieldSetoxvBoxhBoxgrid able abPanel ab
     */
    @Length(max = 200)
    private String layoutType;

    @JoinTable(name = "entityJoin", target = PageGroupEntity.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = PageGroupEntity.FIELD_ENTITY_ID)})
    @Where
    private Long entityId;

    @Transient
    @JoinColumn(joinName = "entityJoin", field = PageGroupEntity.FIELD_ENTITY_NAME)
    private String entityName;

    /**
     * 上级布局组件ID
     */
    private Long parentLayoutId;

    /**
     * 布局组件级别
     */
    private Long layoutLevel;

    /**
     * 模板标志，是否从模板中带出
     */
    @Length(max = 200)
    private String templateFlag;

    /**
     * 所属数据源
     */
    @Length(max = 200)
    private String dataset;

    /**
     * Tab页分组编码
     */
    private Long tabGroupNumber;

    /**
     * ID
     */
    @Length(max = 200)
    private String id;

    /**
     * 宽度
     */
    private Long width;

    /**
     * 高度
     */
    private Long height;

    /**
     * 自适应宽度
     */
    private Long marginwidth;

    /**
     * 自适应高度
     */
    private Long marginheight;

    /**
     * 样式
     */
    @Length(max = 200)
    private String style;

    /**
     * 是否隐藏
     */
    @Length(max = 200)
    private String hidden;

    /**
     * 业务规则代码
     */
    @Length(max = 200)
    private String businessCategory;

    /**
     * 父级业务规则代码
     */
    @Length(max = 200)
    private String parentBusinessCategory;

    /**
     * 关联表
     */
    @Length(max = 200)
    private String refTable;

    /**
     * 关联字段
     */
    @Length(max = 200)
    private String refField;


    private String writeBackProgram;

    public PageLayoutBasic(TpltLayoutBasic bpmTpltLayoutBasic) {
        this.setLayoutSequence(bpmTpltLayoutBasic.getLayoutSequence());
        this.setLayoutCode(bpmTpltLayoutBasic.getLayoutCode());
        this.setLayoutDesc(bpmTpltLayoutBasic.getLayoutDesc());
        this.setLayoutType(bpmTpltLayoutBasic.getLayoutType());
        this.setParentLayoutId(bpmTpltLayoutBasic.getParentLayoutId());
        this.setLayoutLevel(bpmTpltLayoutBasic.getLayoutLevel());
        this.setTemplateFlag("Y");
        this.setDataset(bpmTpltLayoutBasic.getDataset());
        this.setTabGroupNumber(bpmTpltLayoutBasic.getTabGroupNumber());
        this.setId(bpmTpltLayoutBasic.getId());
        this.setWidth(bpmTpltLayoutBasic.getWidth());
        this.setHeight(bpmTpltLayoutBasic.getHeight());
        this.setMarginwidth(bpmTpltLayoutBasic.getMarginwidth());
        this.setMarginheight(bpmTpltLayoutBasic.getMarginheight());
        this.setStyle(bpmTpltLayoutBasic.getStyle());
        this.setHidden(bpmTpltLayoutBasic.getHidden());
    }
}
