package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_group")
public class PageGroup extends BaseDTO {

    public static final String FIELD_GROUP_ID = "groupId";
    public static final String FIELD_GROUP_TYPE = "groupType";
    public static final String FIELD_GROUP_CODE = "groupCode";
    public static final String FIELD_TEMPLATE_ID = "templateId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_OA_FLOW_CATEGORY = "oaFlowCategory";
    public static final String FIELD_OA_FLOW_SUB_CATEGORY = "oaFlowSubCategory";
    public static final String FIELD_INTERFACE_FLAG = "interfaceFlag";
    public static final String FIELD_AUTO_APPROVE_FLAG = "autoApproveFlag";
    public static final String FIELD_TEMPLATE_DESC = "templateDesc";
    public static final String FIELD_TEMPLATE_SCREEN = "templateScreen";
    public static final String FIELD_OA_FLOW_SUB_CATEGORY_DESC = "oaFlowSubCategoryDesc";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_OA_FLOW_CATEGORY_DESC = "oaFlowCategoryDesc";
    public static final String FIELD_GROUP_DESC = "groupDesc";


    @Id
    @GeneratedValue
    @Where
    private Long groupId;//组ID，主键

    @NotEmpty
    @Length(max = 200)
    @Where
    private String groupType;//页面组归属业务类型

    @NotEmpty
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String groupCode;//页面组代码

    @JoinTable(name = "templateJoin", joinMultiLanguageTable = false, target = Template.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Template.FIELD_TEMPLATE_ID)})
    @Where
    private Long templateId;//引用模板

    @Length(max = 200)
    private String enabledFlag;//启用

    private String oaFlowCategory;//OA类别ID

    private String oaFlowSubCategory;//子分类ID

    @Length(max = 200)
    private String interfaceFlag;//接口标志

    @Length(max = 200)
    private String autoApproveFlag;//自审批

    @Length(max = 200)
    @Transient
    @JoinColumn(joinName = "templateJoin", field = Template.FIELD_TEMPLATE_DESC)
    private String templateDesc;

    @Length(max = 200)
    @Transient
    @JoinColumn(joinName = "templateJoin", field = Template.FIELD_SCREEN)
    private String templateScreen;

    @Length(max = 200)
    @Transient
    @JoinCode(code = "BPM.OA_FLOW_CATEGORY", joinKey = PageGroup.FIELD_OA_FLOW_CATEGORY)
    private String oaFlowCategoryDesc;

    @Length(max = 200)
    @Transient
    @JoinCode(code = "BPM.OA_FLOW_SUB_CATEGORY", joinKey = PageGroup.FIELD_OA_FLOW_SUB_CATEGORY)
    private String oaFlowSubCategoryDesc;

    @Length(max = 200)
    private String groupDesc;

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getGroupType() {
        return groupType;
    }

    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    public String getGroupCode() {
        return groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getOaFlowCategory() {
        return oaFlowCategory;
    }

    public void setOaFlowCategory(String oaFlowCategory) {
        this.oaFlowCategory = oaFlowCategory;
    }

    public String getOaFlowSubCategory() {
        return oaFlowSubCategory;
    }

    public void setOaFlowSubCategory(String oaFlowSubCategory) {
        this.oaFlowSubCategory = oaFlowSubCategory;
    }

    public String getInterfaceFlag() {
        return interfaceFlag;
    }

    public void setInterfaceFlag(String interfaceFlag) {
        this.interfaceFlag = interfaceFlag;
    }

    public String getAutoApproveFlag() {
        return autoApproveFlag;
    }

    public void setAutoApproveFlag(String autoApproveFlag) {
        this.autoApproveFlag = autoApproveFlag;
    }

    public String getTemplateDesc() {
        return templateDesc;
    }

    public void setTemplateDesc(String templateDesc) {
        this.templateDesc = templateDesc;
    }

    public String getTemplateScreen() {
        return templateScreen;
    }

    public void setTemplateScreen(String templateScreen) {
        this.templateScreen = templateScreen;
    }

    public String getOaFlowSubCategoryDesc() {
        return oaFlowSubCategoryDesc;
    }

    public void setOaFlowSubCategoryDesc(String oaFlowSubCategoryDesc) {
        this.oaFlowSubCategoryDesc = oaFlowSubCategoryDesc;
    }

    public String getOaFlowCategoryDesc() {
        return oaFlowCategoryDesc;
    }

    public void setOaFlowCategoryDesc(String oaFlowCategoryDesc) {
        this.oaFlowCategoryDesc = oaFlowCategoryDesc;
    }

    public String getGroupDesc() {
        return groupDesc;
    }

    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }
}
