package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.stereotype.Component;

import javax.persistence.Id;
import javax.persistence.Table;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_page_tag_treegrid")
public class PageTagTreegrid extends BaseDTO {

    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_SHOWCHECKBOX = "showcheckbox";
    public static final String FIELD_DISPLAYFIELD = "displayfield";
    public static final String FIELD_IDFIELD = "idfield";
    public static final String FIELD_PARENTFIELD = "parentfield";
    public static final String FIELD_SEQUENCEFIELD = "sequencefield";
    public static final String FIELD_RENDERER = "renderer";


    @Id
    private Long tagId;//标签ID

    @Length(max = 200)
    private String showcheckbox;//是否显示checkBox

    @Length(max = 200)
    private String displayfield;//显示的Field

    @Length(max = 200)
    private String idfield;//id的field

    @Length(max = 200)
    private String parentfield;//父字段

    @Length(max = 200)
    private String sequencefield;//排序字段

    @Length(max = 200)
    private String renderer;//渲染


    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setShowcheckbox(String showcheckbox) {
        this.showcheckbox = showcheckbox;
    }

    public String getShowcheckbox() {
        return showcheckbox;
    }

    public void setDisplayfield(String displayfield) {
        this.displayfield = displayfield;
    }

    public String getDisplayfield() {
        return displayfield;
    }

    public void setIdfield(String idfield) {
        this.idfield = idfield;
    }

    public String getIdfield() {
        return idfield;
    }

    public void setParentfield(String parentfield) {
        this.parentfield = parentfield;
    }

    public String getParentfield() {
        return parentfield;
    }

    public void setSequencefield(String sequencefield) {
        this.sequencefield = sequencefield;
    }

    public String getSequencefield() {
        return sequencefield;
    }

    public void setRenderer(String renderer) {
        this.renderer = renderer;
    }

    public String getRenderer() {
        return renderer;
    }

}
