package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.GeneratedValue;

import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import org.springframework.stereotype.Component;
import org.hibernate.validator.constraints.Length;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_template_ref_table")
public class TemplateRefTable extends BaseDTO {

    public static final String FIELD_BPM_REF_TABLE_ID = "bpmRefTableId";
    public static final String FIELD_TEMPLATE_ID = "templateId";
    public static final String FIELD_TABLE_NAME = "tableName";
    public static final String FIELD_TABLE_DESCRIPTION = "tableDescription";


    @Id
    @GeneratedValue
    @Where
    private Long refId;//PK

    @Where
    private Long templateId;//模板ID

    @NotEmpty
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String tableName;//存储表（视图）名

    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String tableDescription;//描述


    public void setRefId(Long bpmRefTableId) {
        this.refId = bpmRefTableId;
    }

    public Long getRefId() {
        return refId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableDescription(String tableDescription) {
        this.tableDescription = tableDescription;
    }

    public String getTableDescription() {
        return tableDescription;
    }

}
