package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.GeneratedValue;

import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import org.springframework.stereotype.Component;
import org.hibernate.validator.constraints.Length;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_tplt_layout_basic")
public class TpltLayoutBasic extends BaseDTO {

    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_TEMPLATE_ID = "templateId";
    public static final String FIELD_LAYOUT_SEQUENCE = "layoutSequence";
    public static final String FIELD_LAYOUT_CODE = "layoutCode";
    public static final String FIELD_LAYOUT_DESC = "layoutDesc";
    public static final String FIELD_LAYOUT_TYPE = "layoutType";
    public static final String FIELD_PARENT_LAYOUT_ID = "parentLayoutId";
    public static final String FIELD_LAYOUT_LEVEL = "layoutLevel";
    public static final String FIELD_DATASET = "dataset";
    public static final String FIELD_ID = "id";
    public static final String FIELD_TAB_GROUP_NUMBER = "tabGroupNumber";
    public static final String FIELD_WIDTH = "width";
    public static final String FIELD_HEIGHT = "height";
    public static final String FIELD_MARGINWIDTH = "marginwidth";
    public static final String FIELD_MARGINHEIGHT = "marginheight";
    public static final String FIELD_STYLE = "style";
    public static final String FIELD_HIDDEN = "hidden";
    public static final String FIELD_BUSINESS_CATEGORY = "businessCategory";
    public static final String FIELD_PARENT_BUSINESS_CATEGORY = "parentBusinessCategory";
    public static final String FIELD_REF_TABLE = "refTable";
    public static final String FIELD_REF_FIELD = "refField";


    @Id
    @GeneratedValue
    @Where
    private Long layoutId;//布局组件ID

    @Where
    private Long templateId;//所属模板ID

    private Long layoutSequence;//布局组件顺序

    @NotEmpty
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String layoutCode;//布局组件代码

    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String layoutDesc;//布局组件描述

    @Length(max = 200)
    private String layoutType;//布局组件类型，formieldSetoxvBoxhBoxgrid	able	abPanel	ab

    private Long parentLayoutId;//上级布局组件ID

    private Long layoutLevel;//布局组件级别

    @Length(max = 200)
    private String dataset;//所属数据源

    @Length(max = 200)
    private String id;//ID

    private Long tabGroupNumber;//Tab页分组编码

    private Long width;//宽度

    private Long height;//高度

    private Long marginwidth;//自适应宽度

    private Long marginheight;//自适应高度

    @Length(max = 200)
    private String style;//样式

    @Length(max = 200)
    private String hidden;//是否隐藏

    @Length(max = 200)
    private String businessCategory;//业务规则代码

    @Length(max = 200)
    private String parentBusinessCategory;//父级业务规则代码

    @Length(max = 200)
    private String refTable;//关联表

    @Length(max = 200)
    private String refField;//关联字段


    public void setLayoutId(Long layoutId) {
        this.layoutId = layoutId;
    }

    public Long getLayoutId() {
        return layoutId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setLayoutSequence(Long layoutSequence) {
        this.layoutSequence = layoutSequence;
    }

    public Long getLayoutSequence() {
        return layoutSequence;
    }

    public void setLayoutCode(String layoutCode) {
        this.layoutCode = layoutCode;
    }

    public String getLayoutCode() {
        return layoutCode;
    }

    public void setLayoutDesc(String layoutDesc) {
        this.layoutDesc = layoutDesc;
    }

    public String getLayoutDesc() {
        return layoutDesc;
    }

    public void setLayoutType(String layoutType) {
        this.layoutType = layoutType;
    }

    public String getLayoutType() {
        return layoutType;
    }

    public void setParentLayoutId(Long parentLayoutId) {
        this.parentLayoutId = parentLayoutId;
    }

    public Long getParentLayoutId() {
        return parentLayoutId;
    }

    public void setLayoutLevel(Long layoutLevel) {
        this.layoutLevel = layoutLevel;
    }

    public Long getLayoutLevel() {
        return layoutLevel;
    }

    public void setDataset(String dataset) {
        this.dataset = dataset;
    }

    public String getDataset() {
        return dataset;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setTabGroupNumber(Long tabGroupNumber) {
        this.tabGroupNumber = tabGroupNumber;
    }

    public Long getTabGroupNumber() {
        return tabGroupNumber;
    }

    public void setWidth(Long width) {
        this.width = width;
    }

    public Long getWidth() {
        return width;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getHeight() {
        return height;
    }

    public void setMarginwidth(Long marginwidth) {
        this.marginwidth = marginwidth;
    }

    public Long getMarginwidth() {
        return marginwidth;
    }

    public void setMarginheight(Long marginheight) {
        this.marginheight = marginheight;
    }

    public Long getMarginheight() {
        return marginheight;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public String getStyle() {
        return style;
    }

    public void setHidden(String hidden) {
        this.hidden = hidden;
    }

    public String getHidden() {
        return hidden;
    }

    public void setBusinessCategory(String businessCategory) {
        this.businessCategory = businessCategory;
    }

    public String getBusinessCategory() {
        return businessCategory;
    }

    public void setParentBusinessCategory(String parentBusinessCategory) {
        this.parentBusinessCategory = parentBusinessCategory;
    }

    public String getParentBusinessCategory() {
        return parentBusinessCategory;
    }

    public void setRefTable(String refTable) {
        this.refTable = refTable;
    }

    public String getRefTable() {
        return refTable;
    }

    public void setRefField(String refField) {
        this.refField = refField;
    }

    public String getRefField() {
        return refField;
    }

}
