package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;

/**
 * @author xxx@hand-china.com
 */

@ExtensionAttribute(disable = true)
@Table(name = "bpm_tplt001_line")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Tplt001Line extends TpltDataLine {

    public static final String FIELD_LINE_ID = "lineId";
    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_LINE_NUM = "lineNum";

    public static final String BUSINESS_CATEGORY = "TPLT001_LINE";
    public static final String PARENT_BUSINESS_CATEGORY = "TPLT001_HEADER";

    /**
     * 单据头ID
     */
    @Id
    @GeneratedValue
    @Where
    @JoinTable(name = "dynamicJoin", joinMultiLanguageTable = false, target = DynamicDataLine.class,
                    type = JoinType.LEFT, on = {@JoinOn(joinField = DynamicDataLine.FIELD_DOC_ID,
                                    joinExpression = " line_id and business_category = 'TPLT001_LINE'")})
    private Long lineId;

    /**
     * 模板头ID
     */
    @Where
    private Long headerId;

    /**
     * 行号
     */
    private Long lineNum;

}
