package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.GeneratedValue;

import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.JoinCode;
import com.hand.hap.mybatis.common.query.Where;
import org.springframework.stereotype.Component;
import org.hibernate.validator.constraints.Length;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_tplt_tag_basic")
public class TpltTagBasic extends BaseDTO {

    public static final String FIELD_TAG_ID = "tagId";
    public static final String FIELD_LAYOUT_ID = "layoutId";
    public static final String FIELD_TAG_SEQUENCE = "tagSequence";
    public static final String FIELD_TAG_CODE = "tagCode";
    public static final String FIELD_TAG_DESC = "tagDesc";
    public static final String FIELD_TAG_TYPE = "tagType";
    public static final String FIELD_TAG_TYPE_DESC = "tagTypeDesc";
    public static final String FIELD_COLSPAN = "colspan";
    public static final String FIELD_ROWSPAN = "rowspan";
    public static final String FIELD_HIDDEN = "hidden";
    public static final String FIELD_PARENT_TAG_ID = "parentTagId";
    public static final String FIELD_PARENT_TAG_DESC = "parentTagDesc";
    public static final String FIELD_NAME = "name";
    public static final String FIELD_DEFAULTVALUE = "defaultvalue";
    public static final String FIELD_READONLY = "readonly";
    public static final String FIELD_REQUIRED = "required";
    public static final String FIELD_PROMPT = "prompt";
    public static final String FIELD_VALIDATOR = "validator";
    public static final String FIELD_REQUIREDMESSAGE = "requiredmessage";
    public static final String FIELD_ID = "id";
    public static final String FIELD_FIELD_SOURCE = "fieldSource";
    public static final String FIELD_BINDTARGET = "bindtarget";


    @Id
    @GeneratedValue
    @Where
    private Long tagId;//标签ID

    @Where
    private Long layoutId;//所属布局组件ID

    private Long tagSequence;//标签顺序

    @NotEmpty
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String tagCode;//标签代码

    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String tagDesc;//标签描述

    @Length(max = 200)
    private String tagType;//标签类型，textField

    @Length(max = 300)
    @Transient
    @JoinCode(code = "BPM.TAG_TYPE",joinKey = TpltTagBasic.FIELD_TAG_TYPE)
    private String tagTypeDesc;//标签类型描述

    private Long colspan;//所占列数，From类标签

    private Long rowspan;//所占行数，From类标签

    @Length(max = 200)
    private String hidden;//是否隐藏，From类标签

    private Long parentTagId;//上级标签ID，Grid类标签在做复杂表头时使用

    @Length(max = 300)
    @Transient
    private String parentTagDesc;//上级标签描述

    @Length(max = 200)
    private String name;//标签对应字段名称

    @Length(max = 200)
    private String defaultvalue;//标签对应字段默认值

    @Length(max = 200)
    private String readonly;//标签对应字段是否只读

    @Length(max = 200)
    private String required;//标签对应字段是否必输

    @Length(max = 200)
    private String prompt;//标签对应字段的描述

    @Length(max = 200)
    private String validator;//标签对应字段的校验逻辑

    @Length(max = 200)
    private String requiredmessage;//标签对应字段的必输提示信息

    @Length(max = 200)
    private String id;//ID，Form类标签

    @Length(max = 200)
    private String fieldSource;//ID，Form类标签

    @Length(max = 200)
    private String bindtarget;//ID，Form类标签


    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    public Long getTagId() {
        return tagId;
    }

    public void setLayoutId(Long layoutId) {
        this.layoutId = layoutId;
    }

    public Long getLayoutId() {
        return layoutId;
    }

    public void setTagSequence(Long tagSequence) {
        this.tagSequence = tagSequence;
    }

    public Long getTagSequence() {
        return tagSequence;
    }

    public void setTagCode(String tagCode) {
        this.tagCode = tagCode;
    }

    public String getTagCode() {
        return tagCode;
    }

    public void setTagDesc(String tagDesc) {
        this.tagDesc = tagDesc;
    }

    public String getTagDesc() {
        return tagDesc;
    }

    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    public String getTagType() {
        return tagType;
    }

    public void setColspan(Long colspan) {
        this.colspan = colspan;
    }

    public Long getColspan() {
        return colspan;
    }

    public void setRowspan(Long rowspan) {
        this.rowspan = rowspan;
    }

    public Long getRowspan() {
        return rowspan;
    }

    public void setHidden(String hidden) {
        this.hidden = hidden;
    }

    public String getHidden() {
        return hidden;
    }

    public void setParentTagId(Long parentTagId) {
        this.parentTagId = parentTagId;
    }

    public Long getParentTagId() {
        return parentTagId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    public String getDefaultvalue() {
        return defaultvalue;
    }

    public void setReadonly(String readonly) {
        this.readonly = readonly;
    }

    public String getReadonly() {
        return readonly;
    }

    public void setRequired(String required) {
        this.required = required;
    }

    public String getRequired() {
        return required;
    }

    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }

    public String getPrompt() {
        return prompt;
    }

    public void setValidator(String validator) {
        this.validator = validator;
    }

    public String getValidator() {
        return validator;
    }

    public void setRequiredmessage(String requiredmessage) {
        this.requiredmessage = requiredmessage;
    }

    public String getRequiredmessage() {
        return requiredmessage;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public String getTagTypeDesc() {
        return tagTypeDesc;
    }

    public void setTagTypeDesc(String tagTypeDesc) {
        this.tagTypeDesc = tagTypeDesc;
    }

    public String getParentTagDesc() {
        return parentTagDesc;
    }

    public void setParentTagDesc(String parentTagDesc) {
        this.parentTagDesc = parentTagDesc;
    }

    public String getFieldSource() {
        return fieldSource;
    }

    public void setFieldSource(String fieldSource) {
        this.fieldSource = fieldSource;
    }

    public String getBindtarget() {
        return bindtarget;
    }

    public void setBindtarget(String bindtarget) {
        this.bindtarget = bindtarget;
    }
}
