package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;

import java.util.List;

/**
 * @author xxx@hand-china.com
 */

@ExtensionAttribute(disable = true)
@Table(name = "bpm_tplt001_header")
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Tplt001Header extends TpltDataLine {

    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_DOC_HEADER_ID = "docHeaderId";

    public static final String BUSINESS_CATEGORY = "TPLT001_HEADER";


    /**
     * 单据头ID
     */
    @Id
    @GeneratedValue
    @Where
    @JoinTable(name = "dynamicJoin", joinMultiLanguageTable = false, target = DynamicDataLine.class,
                    type = JoinType.LEFT, on = {@JoinOn(joinField = DynamicDataLine.FIELD_DOC_ID,
                                    joinExpression = " header_id and business_category = 'TPLT001_HEADER'")})
    private Long headerId;

    /**
     * 单据头ID
     */
    @Where
    private Long docHeaderId;

    @Transient
    private List<Tplt001Line> tplt001Lines;

    public List<Tplt001Line> getTplt001Lines() {
        return tplt001Lines;
    }

    public void setTplt001Lines(List<Tplt001Line> tplt001Lines) {
        this.tplt001Lines = tplt001Lines;
    }

}
