package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.GeneratedValue;

import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import org.springframework.stereotype.Component;
import org.hibernate.validator.constraints.Length;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_tplt_dataset")
public class TpltDataset extends BaseDTO {

    public static final String FIELD_DATASET_ID = "datasetId";
    public static final String FIELD_DATASET_USAGE = "datasetUsage";
    public static final String FIELD_DATASOURCE_TYPE = "datasourceType";
    public static final String FIELD_MODEL = "model";
    public static final String FIELD_AUTO_QUERY = "autoQuery";
    public static final String FIELD_QUERY_URL = "queryUrl";
    public static final String FIELD_AUTO_CREATE = "autoCreate";
    public static final String FIELD_SUBMIT_URL = "submitUrl";
    public static final String FIELD_BIND_NAME = "bindName";
    public static final String FIELD_BIND_TARGET = "bindTarget";
    public static final String FIELD_SELECTABLE = "selectable";
    public static final String FIELD_SELECTION_MODEL = "selectionModel";
    public static final String FIELD_LOAD_DATA = "loadData";
    public static final String FIELD_LOOKUP_CODE = "lookupCode";
    public static final String FIELD_QUERY_DATASET = "queryDataset";
    public static final String FIELD_FETCHALL = "fetchall";
    public static final String FIELD_PAGE_SIZE = "pageSize";
    public static final String FIELD_AUTO_COUNT = "autoCount";
    public static final String FIELD_AUTO_PAGESIZE = "autoPagesize";
    public static final String FIELD_MAX_PAGESIZE = "maxPagesize";
    public static final String FIELD_MODIFIED_CHECK = "modifiedCheck";
    public static final String FIELD_NOTIFICATION = "notification";
    public static final String FIELD_TEMPLATE_ID = "templateId";

    private Long datasetId;//数据集ID

    @Length(max = 200)
    private String datasetUsage;//数据集用途

    @Length(max = 200)
    private String datasourceType;//数据来源

    @Length(max = 200)
    private String model;//数据源路径

    @Length(max = 200)
    private String autoQuery;//自动查询

    @Length(max = 200)
    private String queryUrl;//查询URL

    @Length(max = 200)
    private String autoCreate;//自动创建

    @Length(max = 200)
    private String submitUrl;//提交URL

    @Length(max = 200)
    private String bindName;//绑定名

    @Length(max = 200)
    private String bindTarget;//绑定dataset

    @Length(max = 200)
    private String selectable;//可选择

    @Length(max = 200)
    private String selectionModel;//选择模式

    @Length(max = 200)
    private String loadData;//服务器端加载

    @Length(max = 200)
    private String lookupCode;//值列表的CODE

    @Length(max = 200)
    private String queryDataset;//查询的dataset的ID

    @Length(max = 200)
    private String fetchall;//查询所有

    private Long pageSize;//查询分页大小

    @Length(max = 200)
    private String autoCount;//自动计数

    private Long autoPagesize;//自适应分页大小

    private Long maxPagesize;//查询分页的最大值

    @Length(max = 200)
    private String modifiedCheck;//是否检查dataset未保存

    @Length(max = 200)
    private String notification;//未保存提示信息

    private Long templateId;//模版ID


    public void setDatasetId(Long datasetId) {
        this.datasetId = datasetId;
    }

    public Long getDatasetId() {
        return datasetId;
    }

    public void setDatasetUsage(String datasetUsage) {
        this.datasetUsage = datasetUsage;
    }

    public String getDatasetUsage() {
        return datasetUsage;
    }

    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType;
    }

    public String getDatasourceType() {
        return datasourceType;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getModel() {
        return model;
    }

    public void setAutoQuery(String autoQuery) {
        this.autoQuery = autoQuery;
    }

    public String getAutoQuery() {
        return autoQuery;
    }

    public void setQueryUrl(String queryUrl) {
        this.queryUrl = queryUrl;
    }

    public String getQueryUrl() {
        return queryUrl;
    }

    public void setAutoCreate(String autoCreate) {
        this.autoCreate = autoCreate;
    }

    public String getAutoCreate() {
        return autoCreate;
    }

    public void setSubmitUrl(String submitUrl) {
        this.submitUrl = submitUrl;
    }

    public String getSubmitUrl() {
        return submitUrl;
    }

    public void setBindName(String bindName) {
        this.bindName = bindName;
    }

    public String getBindName() {
        return bindName;
    }

    public void setBindTarget(String bindTarget) {
        this.bindTarget = bindTarget;
    }

    public String getBindTarget() {
        return bindTarget;
    }

    public void setSelectable(String selectable) {
        this.selectable = selectable;
    }

    public String getSelectable() {
        return selectable;
    }

    public void setSelectionModel(String selectionModel) {
        this.selectionModel = selectionModel;
    }

    public String getSelectionModel() {
        return selectionModel;
    }

    public void setLoadData(String loadData) {
        this.loadData = loadData;
    }

    public String getLoadData() {
        return loadData;
    }

    public void setLookupCode(String lookupCode) {
        this.lookupCode = lookupCode;
    }

    public String getLookupCode() {
        return lookupCode;
    }

    public void setQueryDataset(String queryDataset) {
        this.queryDataset = queryDataset;
    }

    public String getQueryDataset() {
        return queryDataset;
    }

    public void setFetchall(String fetchall) {
        this.fetchall = fetchall;
    }

    public String getFetchall() {
        return fetchall;
    }

    public void setPageSize(Long pageSize) {
        this.pageSize = pageSize;
    }

    public Long getPageSize() {
        return pageSize;
    }

    public void setAutoCount(String autoCount) {
        this.autoCount = autoCount;
    }

    public String getAutoCount() {
        return autoCount;
    }

    public void setAutoPagesize(Long autoPagesize) {
        this.autoPagesize = autoPagesize;
    }

    public Long getAutoPagesize() {
        return autoPagesize;
    }

    public void setMaxPagesize(Long maxPagesize) {
        this.maxPagesize = maxPagesize;
    }

    public Long getMaxPagesize() {
        return maxPagesize;
    }

    public void setModifiedCheck(String modifiedCheck) {
        this.modifiedCheck = modifiedCheck;
    }

    public String getModifiedCheck() {
        return modifiedCheck;
    }

    public void setNotification(String notification) {
        this.notification = notification;
    }

    public String getNotification() {
        return notification;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getTemplateId() {
        return templateId;
    }

}
