package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.fnd.dto.Company;
import com.hand.hap.hr.dto.HrOrgUnit;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;
import java.math.BigDecimal;
import java.util.Date;

/**
 * @author xxx@hand-china.com
 */
@Getter
@Setter
@ToString
@NoArgsConstructor
public class TpltDataLine extends BaseDTO {

    public static final String FIELD_DATA_LINE_ID = "dataLineId";
    public static final String FIELD_BUSINESS_CATEGORY = "businessCategory";
    public static final String FIELD_DOC_ID = "docId";
    public static final String FIELD_DOC_HEADER_ID = "docHeaderId";
    public static final String FIELD_PARENT_BUSINESS_CATEGORY = "parentBusinessCategory";
    public static final String FIELD_PARENT_DOC_ID = "parentDocId";
    public static final String FIELD_N001 = "n001";
    public static final String FIELD_N002 = "n002";
    public static final String FIELD_N003 = "n003";
    public static final String FIELD_N004 = "n004";
    public static final String FIELD_N005 = "n005";
    public static final String FIELD_N006 = "n006";
    public static final String FIELD_N007 = "n007";
    public static final String FIELD_N008 = "n008";
    public static final String FIELD_N009 = "n009";
    public static final String FIELD_N010 = "n010";
    public static final String FIELD_N011 = "n011";
    public static final String FIELD_N012 = "n012";
    public static final String FIELD_N013 = "n013";
    public static final String FIELD_N014 = "n014";
    public static final String FIELD_N015 = "n015";
    public static final String FIELD_N016 = "n016";
    public static final String FIELD_N017 = "n017";
    public static final String FIELD_N018 = "n018";
    public static final String FIELD_N019 = "n019";
    public static final String FIELD_N020 = "n020";
    public static final String FIELD_N021 = "n021";
    public static final String FIELD_N022 = "n022";
    public static final String FIELD_N023 = "n023";
    public static final String FIELD_N024 = "n024";
    public static final String FIELD_N025 = "n025";
    public static final String FIELD_N026 = "n026";
    public static final String FIELD_N027 = "n027";
    public static final String FIELD_N028 = "n028";
    public static final String FIELD_N029 = "n029";
    public static final String FIELD_N030 = "n030";
    public static final String FIELD_N031 = "n031";
    public static final String FIELD_N032 = "n032";
    public static final String FIELD_N033 = "n033";
    public static final String FIELD_N034 = "n034";
    public static final String FIELD_N035 = "n035";
    public static final String FIELD_N036 = "n036";
    public static final String FIELD_N037 = "n037";
    public static final String FIELD_N038 = "n038";
    public static final String FIELD_N039 = "n039";
    public static final String FIELD_N040 = "n040";
    public static final String FIELD_N041 = "n041";
    public static final String FIELD_N042 = "n042";
    public static final String FIELD_N043 = "n043";
    public static final String FIELD_N044 = "n044";
    public static final String FIELD_N045 = "n045";
    public static final String FIELD_N046 = "n046";
    public static final String FIELD_N047 = "n047";
    public static final String FIELD_N048 = "n048";
    public static final String FIELD_N049 = "n049";
    public static final String FIELD_N050 = "n050";
    public static final String FIELD_N051 = "n051";
    public static final String FIELD_N052 = "n052";
    public static final String FIELD_N053 = "n053";
    public static final String FIELD_N054 = "n054";
    public static final String FIELD_N055 = "n055";
    public static final String FIELD_N056 = "n056";
    public static final String FIELD_N057 = "n057";
    public static final String FIELD_N058 = "n058";
    public static final String FIELD_N059 = "n059";
    public static final String FIELD_N060 = "n060";
    public static final String FIELD_N061 = "n061";
    public static final String FIELD_N062 = "n062";
    public static final String FIELD_N063 = "n063";
    public static final String FIELD_N064 = "n064";
    public static final String FIELD_N065 = "n065";
    public static final String FIELD_N066 = "n066";
    public static final String FIELD_N067 = "n067";
    public static final String FIELD_N068 = "n068";
    public static final String FIELD_N069 = "n069";
    public static final String FIELD_N070 = "n070";
    public static final String FIELD_N071 = "n071";
    public static final String FIELD_N072 = "n072";
    public static final String FIELD_N073 = "n073";
    public static final String FIELD_N074 = "n074";
    public static final String FIELD_N075 = "n075";
    public static final String FIELD_N076 = "n076";
    public static final String FIELD_N077 = "n077";
    public static final String FIELD_N078 = "n078";
    public static final String FIELD_N079 = "n079";
    public static final String FIELD_N080 = "n080";
    public static final String FIELD_C001 = "c001";
    public static final String FIELD_C002 = "c002";
    public static final String FIELD_C003 = "c003";
    public static final String FIELD_C004 = "c004";
    public static final String FIELD_C005 = "c005";
    public static final String FIELD_C006 = "c006";
    public static final String FIELD_C007 = "c007";
    public static final String FIELD_C008 = "c008";
    public static final String FIELD_C009 = "c009";
    public static final String FIELD_C010 = "c010";
    public static final String FIELD_C011 = "c011";
    public static final String FIELD_C012 = "c012";
    public static final String FIELD_C013 = "c013";
    public static final String FIELD_C014 = "c014";
    public static final String FIELD_C015 = "c015";
    public static final String FIELD_C016 = "c016";
    public static final String FIELD_C017 = "c017";
    public static final String FIELD_C018 = "c018";
    public static final String FIELD_C019 = "c019";
    public static final String FIELD_C020 = "c020";
    public static final String FIELD_C021 = "c021";
    public static final String FIELD_C022 = "c022";
    public static final String FIELD_C023 = "c023";
    public static final String FIELD_C024 = "c024";
    public static final String FIELD_C025 = "c025";
    public static final String FIELD_C026 = "c026";
    public static final String FIELD_C027 = "c027";
    public static final String FIELD_C028 = "c028";
    public static final String FIELD_C029 = "c029";
    public static final String FIELD_C030 = "c030";
    public static final String FIELD_C031 = "c031";
    public static final String FIELD_C032 = "c032";
    public static final String FIELD_C033 = "c033";
    public static final String FIELD_C034 = "c034";
    public static final String FIELD_C035 = "c035";
    public static final String FIELD_C036 = "c036";
    public static final String FIELD_C037 = "c037";
    public static final String FIELD_C038 = "c038";
    public static final String FIELD_C039 = "c039";
    public static final String FIELD_C040 = "c040";
    public static final String FIELD_C041 = "c041";
    public static final String FIELD_C042 = "c042";
    public static final String FIELD_C043 = "c043";
    public static final String FIELD_C044 = "c044";
    public static final String FIELD_C045 = "c045";
    public static final String FIELD_C046 = "c046";
    public static final String FIELD_C047 = "c047";
    public static final String FIELD_C048 = "c048";
    public static final String FIELD_C049 = "c049";
    public static final String FIELD_C050 = "c050";
    public static final String FIELD_C051 = "c051";
    public static final String FIELD_C052 = "c052";
    public static final String FIELD_C053 = "c053";
    public static final String FIELD_C054 = "c054";
    public static final String FIELD_C055 = "c055";
    public static final String FIELD_C056 = "c056";
    public static final String FIELD_C057 = "c057";
    public static final String FIELD_C058 = "c058";
    public static final String FIELD_C059 = "c059";
    public static final String FIELD_C060 = "c060";
    public static final String FIELD_C061 = "c061";
    public static final String FIELD_C062 = "c062";
    public static final String FIELD_C063 = "c063";
    public static final String FIELD_C064 = "c064";
    public static final String FIELD_C065 = "c065";
    public static final String FIELD_C066 = "c066";
    public static final String FIELD_C067 = "c067";
    public static final String FIELD_C068 = "c068";
    public static final String FIELD_C069 = "c069";
    public static final String FIELD_C070 = "c070";
    public static final String FIELD_C071 = "c071";
    public static final String FIELD_C072 = "c072";
    public static final String FIELD_C073 = "c073";
    public static final String FIELD_C074 = "c074";
    public static final String FIELD_C075 = "c075";
    public static final String FIELD_C076 = "c076";
    public static final String FIELD_C077 = "c077";
    public static final String FIELD_C078 = "c078";
    public static final String FIELD_C079 = "c079";
    public static final String FIELD_C080 = "c080";
    public static final String FIELD_C081 = "c081";
    public static final String FIELD_C082 = "c082";
    public static final String FIELD_C083 = "c083";
    public static final String FIELD_C084 = "c084";
    public static final String FIELD_C085 = "c085";
    public static final String FIELD_C086 = "c086";
    public static final String FIELD_C087 = "c087";
    public static final String FIELD_C088 = "c088";
    public static final String FIELD_C089 = "c089";
    public static final String FIELD_C090 = "c090";
    public static final String FIELD_C091 = "c091";
    public static final String FIELD_C092 = "c092";
    public static final String FIELD_C093 = "c093";
    public static final String FIELD_C094 = "c094";
    public static final String FIELD_C095 = "c095";
    public static final String FIELD_C096 = "c096";
    public static final String FIELD_C097 = "c097";
    public static final String FIELD_C098 = "c098";
    public static final String FIELD_C099 = "c099";
    public static final String FIELD_C100 = "c100";
    public static final String FIELD_D001 = "d001";
    public static final String FIELD_D002 = "d002";
    public static final String FIELD_D003 = "d003";
    public static final String FIELD_D004 = "d004";
    public static final String FIELD_D005 = "d005";
    public static final String FIELD_D006 = "d006";
    public static final String FIELD_D007 = "d007";
    public static final String FIELD_D008 = "d008";
    public static final String FIELD_D009 = "d009";
    public static final String FIELD_D010 = "d010";
    public static final String FIELD_D011 = "d011";
    public static final String FIELD_D012 = "d012";
    public static final String FIELD_D013 = "d013";
    public static final String FIELD_D014 = "d014";
    public static final String FIELD_D015 = "d015";
    public static final String FIELD_D016 = "d016";
    public static final String FIELD_D017 = "d017";
    public static final String FIELD_D018 = "d018";
    public static final String FIELD_D019 = "d019";
    public static final String FIELD_D020 = "d020";
    public static final String FIELD_D021 = "d021";
    public static final String FIELD_D022 = "d022";
    public static final String FIELD_D023 = "d023";
    public static final String FIELD_D024 = "d024";
    public static final String FIELD_D025 = "d025";
    public static final String FIELD_D026 = "d026";
    public static final String FIELD_D027 = "d027";
    public static final String FIELD_D028 = "d028";
    public static final String FIELD_D029 = "d029";
    public static final String FIELD_D030 = "d030";
    public static final String FIELD_D031 = "d031";
    public static final String FIELD_D032 = "d032";
    public static final String FIELD_D033 = "d033";
    public static final String FIELD_D034 = "d034";
    public static final String FIELD_D035 = "d035";
    public static final String FIELD_D036 = "d036";
    public static final String FIELD_D037 = "d037";
    public static final String FIELD_D038 = "d038";
    public static final String FIELD_D039 = "d039";
    public static final String FIELD_D040 = "d040";
    public static final String FIELD_D041 = "d041";
    public static final String FIELD_D042 = "d042";
    public static final String FIELD_D043 = "d043";
    public static final String FIELD_D044 = "d044";
    public static final String FIELD_D045 = "d045";
    public static final String FIELD_D046 = "d046";
    public static final String FIELD_D047 = "d047";
    public static final String FIELD_D048 = "d048";
    public static final String FIELD_D049 = "d049";
    public static final String FIELD_D050 = "d050";
    public static final String FIELD_CLOB001 = "clob001";
    public static final String FIELD_CLOB002 = "clob002";
    public static final String FIELD_CLOB003 = "clob003";
    public static final String FIELD_CLOB004 = "clob004";
    public static final String FIELD_CLOB005 = "clob005";
    public static final String FIELD_CLOB006 = "clob006";
    public static final String FIELD_CLOB007 = "clob007";
    public static final String FIELD_CLOB008 = "clob008";
    public static final String FIELD_CLOB009 = "clob009";
    public static final String FIELD_CLOB010 = "clob010";

    public static final String FIELD_TRANSACTION_DATE = "transactionDate";
    public static final String FIELD_PERIOD_NAME = "periodName";
    public static final String FIELD_CURRENCY_CODE = "currencyCode";
    public static final String FIELD_CURRENCY_NAME = "currencyName";
    public static final String FIELD_EXCHANGE_RATE_TYPE = "exchangeRateType";
    public static final String FIELD_EXCHANGE_RATE_TYPE_NAME = "exchangeRateTypeName";
    public static final String FIELD_EXCHANGE_RATE = "exchangeRate";
    public static final String FIELD_PRICE = "price";
    public static final String FIELD_QUANTITY = "quantity";
    public static final String FIELD_AMOUNT = "amount";
    public static final String FIELD_FUNCTIONAL_AMOUNT = "functionalAmount";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_COMPANY_NAME = "companyName";
    public static final String FIELD_UNIT_ID = "unitId";
    public static final String FIELD_UNIT_NAME = "unitName";
    public static final String FIELD_POSITION_ID = "positionId";
    public static final String FIELD_POSITION_NAME = "positionName";
    public static final String FIELD_EMPLOYEE_ID = "employeeId";
    public static final String FIELD_EMPLOYEE_NAME = "employeeName";
    public static final String FIELD_SET_OF_BOOKS_ID = "setOfBooksId";
    public static final String FIELD_SET_OF_BOOKS_NAME = "setOfBooksName";
    public static final String FIELD_ACCOUNTING_ENTITY_ID = "accountingEntityId";
    public static final String FIELD_ACCOUNTING_ENTITY_NAME = "accountingEntityName";
    public static final String FIELD_RESP_CENTER_ID = "respCenterId";
    public static final String FIELD_RESP_CENTER_NAME = "respCenterName";
    public static final String FIELD_ACCOUNT_ID = "accountId";
    public static final String FIELD_ACCOUNT_NAME = "accountName";
    public static final String FIELD_PAYEE_CATEGORY = "payeeCategory";
    public static final String FIELD_PAYEE_CATEGORY_NAME = "payeeCategoryName";
    public static final String FIELD_PAYEE_ID = "payeeId";
    public static final String FIELD_PAYEE_NAME = "payeeName";
    public static final String FIELD_BANK_ACCOUNT_ID = "bankAccountId";
    public static final String FIELD_BANK_ACCOUNT_NUMBER = "bankAccountNumber";
    public static final String FIELD_BANK_ACCOUNT_NAME = "bankAccountName";


    /**
     * 行ID
     */
    @Where
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_DATA_LINE_ID)
    private Long dataLineId;


    /**
     * BPM单据ID
     */
    @Where
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_DOC_HEADER_ID)
    private Long docHeaderId;

    /**
     * 业务类别
     */
    @Where
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_BUSINESS_CATEGORY)
    private String businessCategory;

    /**
     * 单据ID
     */
    @Where
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_DOC_ID)
    private Long docId;

    /**
     * 父业务类别
     */
    @Where
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PARENT_BUSINESS_CATEGORY)
    private String parentBusinessCategory;

    /**
     * 父单据ID
     */
    @Where
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PARENT_DOC_ID)
    private Long parentDocId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_TRANSACTION_DATE)
    private Date transactionDate;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PERIOD_NAME)
    private String periodName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CURRENCY_CODE)
    private String currencyCode;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CURRENCY_NAME)
    private String currencyName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_EXCHANGE_RATE_TYPE)
    private String exchangeRateType;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_EXCHANGE_RATE_TYPE_NAME)
    private String exchangeRateTypeName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_EXCHANGE_RATE)
    private BigDecimal exchangeRate;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PRICE)
    private BigDecimal price;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_QUANTITY)
    private BigDecimal quantity;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_AMOUNT)
    private BigDecimal amount;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_FUNCTIONAL_AMOUNT)
    private BigDecimal functionalAmount;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_COMPANY_ID)
    private Long companyId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_COMPANY_NAME)
    private String companyName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_UNIT_ID)
    private Long unitId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_UNIT_NAME)
    private String unitName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_POSITION_ID)
    private Long positionId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_POSITION_NAME)
    private String positionName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_EMPLOYEE_ID)
    private Long employeeId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_EMPLOYEE_NAME)
    private String employeeName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_SET_OF_BOOKS_ID)
    private Long setOfBooksId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_SET_OF_BOOKS_NAME)
    private String setOfBooksName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_ACCOUNTING_ENTITY_ID)
    private Long accountingEntityId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_ACCOUNTING_ENTITY_NAME)
    private String accountingEntityName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_RESP_CENTER_ID)
    private Long respCenterId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_RESP_CENTER_NAME)
    private String respCenterName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_ACCOUNT_ID)
    private Long accountId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_ACCOUNT_NAME)
    private String accountName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PAYEE_CATEGORY)
    private String payeeCategory;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PAYEE_CATEGORY_NAME)
    private String payeeCategoryName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PAYEE_ID)
    private Long payeeId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_PAYEE_NAME)
    private String payeeName;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_BANK_ACCOUNT_ID)
    private Long bankAccountId;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_BANK_ACCOUNT_NUMBER)
    private String bankAccountNumber;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_BANK_ACCOUNT_NAME)
    private String bankAccountName;


    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N001)
    private BigDecimal n001;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N002)
    private BigDecimal n002;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N003)
    private BigDecimal n003;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N004)
    private BigDecimal n004;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N005)
    private BigDecimal n005;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N006)
    private BigDecimal n006;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N007)
    private BigDecimal n007;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N008)
    private BigDecimal n008;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N009)
    private BigDecimal n009;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N010)
    private BigDecimal n010;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N011)
    private BigDecimal n011;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N012)
    private BigDecimal n012;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N013)
    private BigDecimal n013;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N014)
    private BigDecimal n014;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N015)
    private BigDecimal n015;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N016)
    private BigDecimal n016;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N017)
    private BigDecimal n017;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N018)
    private BigDecimal n018;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N019)
    private BigDecimal n019;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N020)
    private BigDecimal n020;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N021)
    private BigDecimal n021;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N022)
    private BigDecimal n022;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N023)
    private BigDecimal n023;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N024)
    private BigDecimal n024;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N025)
    private BigDecimal n025;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N026)
    private BigDecimal n026;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N027)
    private BigDecimal n027;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N028)
    private BigDecimal n028;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N029)
    private BigDecimal n029;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N030)
    private BigDecimal n030;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N031)
    private BigDecimal n031;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N032)
    private BigDecimal n032;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N033)
    private BigDecimal n033;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N034)
    private BigDecimal n034;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N035)
    private BigDecimal n035;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N036)
    private BigDecimal n036;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N037)
    private BigDecimal n037;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N038)
    private BigDecimal n038;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N039)
    private BigDecimal n039;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N040)
    private BigDecimal n040;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N041)
    private BigDecimal n041;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N042)
    private BigDecimal n042;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N043)
    private BigDecimal n043;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N044)
    private BigDecimal n044;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N045)
    private BigDecimal n045;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N046)
    private BigDecimal n046;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N047)
    private BigDecimal n047;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N048)
    private BigDecimal n048;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N049)
    private BigDecimal n049;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N050)
    private BigDecimal n050;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N051)
    private BigDecimal n051;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N052)
    private BigDecimal n052;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N053)
    private BigDecimal n053;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N054)
    private BigDecimal n054;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N055)
    private BigDecimal n055;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N056)
    private BigDecimal n056;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N057)
    private BigDecimal n057;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N058)
    private BigDecimal n058;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N059)
    private BigDecimal n059;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N060)
    private BigDecimal n060;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N061)
    private BigDecimal n061;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N062)
    private BigDecimal n062;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N063)
    private BigDecimal n063;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N064)
    private BigDecimal n064;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N065)
    private BigDecimal n065;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N066)
    private BigDecimal n066;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N067)
    private BigDecimal n067;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N068)
    private BigDecimal n068;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N069)
    private BigDecimal n069;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N070)
    private BigDecimal n070;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N071)
    private BigDecimal n071;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N072)
    private BigDecimal n072;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N073)
    private BigDecimal n073;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N074)
    private BigDecimal n074;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N075)
    private BigDecimal n075;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N076)
    private BigDecimal n076;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N077)
    private BigDecimal n077;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N078)
    private BigDecimal n078;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N079)
    private BigDecimal n079;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_N080)
    private BigDecimal n080;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C001)
    private String c001;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C002)
    private String c002;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C003)
    private String c003;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C004)
    private String c004;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C005)
    private String c005;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C006)
    private String c006;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C007)
    private String c007;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C008)
    private String c008;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C009)
    private String c009;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C010)
    private String c010;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C011)
    private String c011;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C012)
    private String c012;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C013)
    private String c013;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C014)
    private String c014;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C015)
    private String c015;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C016)
    private String c016;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C017)
    private String c017;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C018)
    private String c018;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C019)
    private String c019;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C020)
    private String c020;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C021)
    private String c021;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C022)
    private String c022;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C023)
    private String c023;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C024)
    private String c024;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C025)
    private String c025;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C026)
    private String c026;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C027)
    private String c027;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C028)
    private String c028;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C029)
    private String c029;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C030)
    private String c030;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C031)
    private String c031;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C032)
    private String c032;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C033)
    private String c033;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C034)
    private String c034;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C035)
    private String c035;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C036)
    private String c036;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C037)
    private String c037;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C038)
    private String c038;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C039)
    private String c039;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C040)
    private String c040;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C041)
    private String c041;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C042)
    private String c042;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C043)
    private String c043;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C044)
    private String c044;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C045)
    private String c045;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C046)
    private String c046;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C047)
    private String c047;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C048)
    private String c048;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C049)
    private String c049;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C050)
    private String c050;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C051)
    private String c051;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C052)
    private String c052;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C053)
    private String c053;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C054)
    private String c054;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C055)
    private String c055;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C056)
    private String c056;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C057)
    private String c057;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C058)
    private String c058;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C059)
    private String c059;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C060)
    private String c060;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C061)
    private String c061;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C062)
    private String c062;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C063)
    private String c063;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C064)
    private String c064;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C065)
    private String c065;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C066)
    private String c066;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C067)
    private String c067;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C068)
    private String c068;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C069)
    private String c069;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C070)
    private String c070;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C071)
    private String c071;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C072)
    private String c072;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C073)
    private String c073;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C074)
    private String c074;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C075)
    private String c075;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C076)
    private String c076;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C077)
    private String c077;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C078)
    private String c078;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C079)
    private String c079;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C080)
    private String c080;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C081)
    private String c081;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C082)
    private String c082;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C083)
    private String c083;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C084)
    private String c084;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C085)
    private String c085;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C086)
    private String c086;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C087)
    private String c087;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C088)
    private String c088;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C089)
    private String c089;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C090)
    private String c090;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C091)
    private String c091;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C092)
    private String c092;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C093)
    private String c093;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C094)
    private String c094;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C095)
    private String c095;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C096)
    private String c096;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C097)
    private String c097;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C098)
    private String c098;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C099)
    private String c099;

    @Length(max = 2000)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_C100)
    private String c100;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D001)
    private Date d001;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D002)
    private Date d002;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D003)
    private Date d003;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D004)
    private Date d004;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D005)
    private Date d005;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D006)
    private Date d006;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D007)
    private Date d007;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D008)
    private Date d008;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D009)
    private Date d009;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D010)
    private Date d010;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D011)
    private Date d011;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D012)
    private Date d012;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D013)
    private Date d013;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D014)
    private Date d014;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D015)
    private Date d015;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D016)
    private Date d016;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D017)
    private Date d017;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D018)
    private Date d018;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D019)
    private Date d019;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D020)
    private Date d020;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D021)
    private Date d021;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D022)
    private Date d022;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D023)
    private Date d023;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D024)
    private Date d024;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D025)
    private Date d025;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D026)
    private Date d026;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D027)
    private Date d027;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D028)
    private Date d028;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D029)
    private Date d029;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D030)
    private Date d030;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D031)
    private Date d031;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D032)
    private Date d032;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D033)
    private Date d033;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D034)
    private Date d034;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D035)
    private Date d035;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D036)
    private Date d036;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D037)
    private Date d037;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D038)
    private Date d038;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D039)
    private Date d039;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D040)
    private Date d040;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D041)
    private Date d041;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D042)
    private Date d042;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D043)
    private Date d043;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D044)
    private Date d044;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D045)
    private Date d045;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D046)
    private Date d046;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D047)
    private Date d047;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D048)
    private Date d048;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D049)
    private Date d049;

    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_D050)
    private Date d050;


    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB001)
    private String clob001;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB002)
    private String clob002;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB003)
    private String clob003;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB004)
    private String clob004;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB005)
    private String clob005;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB006)
    private String clob006;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB007)
    private String clob007;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB008)
    private String clob008;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB009)
    private String clob009;

    @Length(max = 2147483647)
    @Transient
    @JoinColumn(joinName = "dynamicJoin", field = DynamicDataLine.FIELD_CLOB010)
    private String clob010;

    public DynamicDataLine convertDynamicDataLine() {
        DynamicDataLine dataLine = new DynamicDataLine();
        dataLine.setDataLineId(this.getDataLineId());
        dataLine.setDocHeaderId(this.getDocHeaderId());
        dataLine.setBusinessCategory(this.getBusinessCategory());
        dataLine.setDocId(this.getDocId());
        dataLine.setParentBusinessCategory(this.getParentBusinessCategory());
        dataLine.setParentDocId(this.getParentDocId());

        dataLine.setTransactionDate(this.getTransactionDate());
        dataLine.setPeriodName(this.getPeriodName());
        dataLine.setCurrencyCode(this.getCurrencyCode());
        dataLine.setCurrencyName(this.getCurrencyName());
        dataLine.setExchangeRateType(this.getExchangeRateType());
        dataLine.setExchangeRateTypeName(this.getExchangeRateTypeName());
        dataLine.setExchangeRate(this.getExchangeRate());
        dataLine.setPrice(this.getPrice());
        dataLine.setQuantity(this.getQuantity());
        dataLine.setAmount(this.getAmount());
        dataLine.setFunctionalAmount(this.getFunctionalAmount());
        dataLine.setCompanyId(this.getCompanyId());
        dataLine.setCompanyName(this.getCompanyName());
        dataLine.setUnitId(this.getUnitId());
        dataLine.setUnitName(this.getUnitName());
        dataLine.setPositionId(this.getPositionId());
        dataLine.setPositionName(this.getPositionName());
        dataLine.setEmployeeId(this.getEmployeeId());
        dataLine.setEmployeeName(this.getEmployeeName());
        dataLine.setSetOfBooksId(this.getSetOfBooksId());
        dataLine.setSetOfBooksName(this.getSetOfBooksName());
        dataLine.setAccountingEntityId(this.getAccountingEntityId());
        dataLine.setAccountingEntityName(this.getAccountingEntityName());
        dataLine.setRespCenterId(this.getRespCenterId());
        dataLine.setRespCenterName(this.getRespCenterName());
        dataLine.setAccountId(this.getAccountId());
        dataLine.setAccountName(this.getAccountName());
        dataLine.setPayeeCategory(this.getPayeeCategory());
        dataLine.setPayeeCategoryName(this.getPayeeCategoryName());
        dataLine.setPayeeId(this.getPayeeId());
        dataLine.setPayeeName(this.getPayeeName());
        dataLine.setBankAccountId(this.getBankAccountId());
        dataLine.setBankAccountNumber(this.getBankAccountNumber());
        dataLine.setBankAccountName(this.getBankAccountName());

        dataLine.setN001(this.getN001());
        dataLine.setN002(this.getN002());
        dataLine.setN003(this.getN003());
        dataLine.setN004(this.getN004());
        dataLine.setN005(this.getN005());
        dataLine.setN006(this.getN006());
        dataLine.setN007(this.getN007());
        dataLine.setN008(this.getN008());
        dataLine.setN009(this.getN009());
        dataLine.setN010(this.getN010());
        dataLine.setN011(this.getN011());
        dataLine.setN012(this.getN012());
        dataLine.setN013(this.getN013());
        dataLine.setN014(this.getN014());
        dataLine.setN015(this.getN015());
        dataLine.setN016(this.getN016());
        dataLine.setN017(this.getN017());
        dataLine.setN018(this.getN018());
        dataLine.setN019(this.getN019());
        dataLine.setN020(this.getN020());
        dataLine.setN021(this.getN021());
        dataLine.setN022(this.getN022());
        dataLine.setN023(this.getN023());
        dataLine.setN024(this.getN024());
        dataLine.setN025(this.getN025());
        dataLine.setN026(this.getN026());
        dataLine.setN027(this.getN027());
        dataLine.setN028(this.getN028());
        dataLine.setN029(this.getN029());
        dataLine.setN030(this.getN030());
        dataLine.setN031(this.getN031());
        dataLine.setN032(this.getN032());
        dataLine.setN033(this.getN033());
        dataLine.setN034(this.getN034());
        dataLine.setN035(this.getN035());
        dataLine.setN036(this.getN036());
        dataLine.setN037(this.getN037());
        dataLine.setN038(this.getN038());
        dataLine.setN039(this.getN039());
        dataLine.setN040(this.getN040());
        dataLine.setN041(this.getN041());
        dataLine.setN042(this.getN042());
        dataLine.setN043(this.getN043());
        dataLine.setN044(this.getN044());
        dataLine.setN045(this.getN045());
        dataLine.setN046(this.getN046());
        dataLine.setN047(this.getN047());
        dataLine.setN048(this.getN048());
        dataLine.setN049(this.getN049());
        dataLine.setN050(this.getN050());
        dataLine.setN051(this.getN051());
        dataLine.setN052(this.getN052());
        dataLine.setN053(this.getN053());
        dataLine.setN054(this.getN054());
        dataLine.setN055(this.getN055());
        dataLine.setN056(this.getN056());
        dataLine.setN057(this.getN057());
        dataLine.setN058(this.getN058());
        dataLine.setN059(this.getN059());
        dataLine.setN060(this.getN060());
        dataLine.setN061(this.getN061());
        dataLine.setN062(this.getN062());
        dataLine.setN063(this.getN063());
        dataLine.setN064(this.getN064());
        dataLine.setN065(this.getN065());
        dataLine.setN066(this.getN066());
        dataLine.setN067(this.getN067());
        dataLine.setN068(this.getN068());
        dataLine.setN069(this.getN069());
        dataLine.setN070(this.getN070());
        dataLine.setN071(this.getN071());
        dataLine.setN072(this.getN072());
        dataLine.setN073(this.getN073());
        dataLine.setN074(this.getN074());
        dataLine.setN075(this.getN075());
        dataLine.setN076(this.getN076());
        dataLine.setN077(this.getN077());
        dataLine.setN078(this.getN078());
        dataLine.setN079(this.getN079());
        dataLine.setN080(this.getN080());

        dataLine.setC001(this.getC001());
        dataLine.setC002(this.getC002());
        dataLine.setC003(this.getC003());
        dataLine.setC004(this.getC004());
        dataLine.setC005(this.getC005());
        dataLine.setC006(this.getC006());
        dataLine.setC007(this.getC007());
        dataLine.setC008(this.getC008());
        dataLine.setC009(this.getC009());
        dataLine.setC010(this.getC010());
        dataLine.setC011(this.getC011());
        dataLine.setC012(this.getC012());
        dataLine.setC013(this.getC013());
        dataLine.setC014(this.getC014());
        dataLine.setC015(this.getC015());
        dataLine.setC016(this.getC016());
        dataLine.setC017(this.getC017());
        dataLine.setC018(this.getC018());
        dataLine.setC019(this.getC019());
        dataLine.setC020(this.getC020());
        dataLine.setC021(this.getC021());
        dataLine.setC022(this.getC022());
        dataLine.setC023(this.getC023());
        dataLine.setC024(this.getC024());
        dataLine.setC025(this.getC025());
        dataLine.setC026(this.getC026());
        dataLine.setC027(this.getC027());
        dataLine.setC028(this.getC028());
        dataLine.setC029(this.getC029());
        dataLine.setC030(this.getC030());
        dataLine.setC031(this.getC031());
        dataLine.setC032(this.getC032());
        dataLine.setC033(this.getC033());
        dataLine.setC034(this.getC034());
        dataLine.setC035(this.getC035());
        dataLine.setC036(this.getC036());
        dataLine.setC037(this.getC037());
        dataLine.setC038(this.getC038());
        dataLine.setC039(this.getC039());
        dataLine.setC040(this.getC040());
        dataLine.setC041(this.getC041());
        dataLine.setC042(this.getC042());
        dataLine.setC043(this.getC043());
        dataLine.setC044(this.getC044());
        dataLine.setC045(this.getC045());
        dataLine.setC046(this.getC046());
        dataLine.setC047(this.getC047());
        dataLine.setC048(this.getC048());
        dataLine.setC049(this.getC049());
        dataLine.setC050(this.getC050());
        dataLine.setC051(this.getC051());
        dataLine.setC052(this.getC052());
        dataLine.setC053(this.getC053());
        dataLine.setC054(this.getC054());
        dataLine.setC055(this.getC055());
        dataLine.setC056(this.getC056());
        dataLine.setC057(this.getC057());
        dataLine.setC058(this.getC058());
        dataLine.setC059(this.getC059());
        dataLine.setC060(this.getC060());
        dataLine.setC061(this.getC061());
        dataLine.setC062(this.getC062());
        dataLine.setC063(this.getC063());
        dataLine.setC064(this.getC064());
        dataLine.setC065(this.getC065());
        dataLine.setC066(this.getC066());
        dataLine.setC067(this.getC067());
        dataLine.setC068(this.getC068());
        dataLine.setC069(this.getC069());
        dataLine.setC070(this.getC070());
        dataLine.setC071(this.getC071());
        dataLine.setC072(this.getC072());
        dataLine.setC073(this.getC073());
        dataLine.setC074(this.getC074());
        dataLine.setC075(this.getC075());
        dataLine.setC076(this.getC076());
        dataLine.setC077(this.getC077());
        dataLine.setC078(this.getC078());
        dataLine.setC079(this.getC079());
        dataLine.setC080(this.getC080());
        dataLine.setC081(this.getC081());
        dataLine.setC082(this.getC082());
        dataLine.setC083(this.getC083());
        dataLine.setC084(this.getC084());
        dataLine.setC085(this.getC085());
        dataLine.setC086(this.getC086());
        dataLine.setC087(this.getC087());
        dataLine.setC088(this.getC088());
        dataLine.setC089(this.getC089());
        dataLine.setC090(this.getC090());
        dataLine.setC091(this.getC091());
        dataLine.setC092(this.getC092());
        dataLine.setC093(this.getC093());
        dataLine.setC094(this.getC094());
        dataLine.setC095(this.getC095());
        dataLine.setC096(this.getC096());
        dataLine.setC097(this.getC097());
        dataLine.setC098(this.getC098());
        dataLine.setC099(this.getC099());
        dataLine.setC100(this.getC100());


        dataLine.setD001(this.getD001());
        dataLine.setD002(this.getD002());
        dataLine.setD003(this.getD003());
        dataLine.setD004(this.getD004());
        dataLine.setD005(this.getD005());
        dataLine.setD006(this.getD006());
        dataLine.setD007(this.getD007());
        dataLine.setD008(this.getD008());
        dataLine.setD009(this.getD009());
        dataLine.setD010(this.getD010());
        dataLine.setD011(this.getD011());
        dataLine.setD012(this.getD012());
        dataLine.setD013(this.getD013());
        dataLine.setD014(this.getD014());
        dataLine.setD015(this.getD015());
        dataLine.setD016(this.getD016());
        dataLine.setD017(this.getD017());
        dataLine.setD018(this.getD018());
        dataLine.setD019(this.getD019());
        dataLine.setD020(this.getD020());
        dataLine.setD021(this.getD021());
        dataLine.setD022(this.getD022());
        dataLine.setD023(this.getD023());
        dataLine.setD024(this.getD024());
        dataLine.setD025(this.getD025());
        dataLine.setD026(this.getD026());
        dataLine.setD027(this.getD027());
        dataLine.setD028(this.getD028());
        dataLine.setD029(this.getD029());
        dataLine.setD030(this.getD030());
        dataLine.setD031(this.getD031());
        dataLine.setD032(this.getD032());
        dataLine.setD033(this.getD033());
        dataLine.setD034(this.getD034());
        dataLine.setD035(this.getD035());
        dataLine.setD036(this.getD036());
        dataLine.setD037(this.getD037());
        dataLine.setD038(this.getD038());
        dataLine.setD039(this.getD039());
        dataLine.setD040(this.getD040());
        dataLine.setD041(this.getD041());
        dataLine.setD042(this.getD042());
        dataLine.setD043(this.getD043());
        dataLine.setD044(this.getD044());
        dataLine.setD045(this.getD045());
        dataLine.setD046(this.getD046());
        dataLine.setD047(this.getD047());
        dataLine.setD048(this.getD048());
        dataLine.setD049(this.getD049());
        dataLine.setD050(this.getD050());


        dataLine.setClob001(this.getClob001());
        dataLine.setClob002(this.getClob002());
        dataLine.setClob003(this.getClob003());
        dataLine.setClob004(this.getClob004());
        dataLine.setClob005(this.getClob005());
        dataLine.setClob006(this.getClob006());
        dataLine.setClob007(this.getClob007());
        dataLine.setClob008(this.getClob008());
        dataLine.setClob009(this.getClob009());
        dataLine.setClob010(this.getClob010());


        dataLine.set__id(this.get__id());
        dataLine.set__status(this.get__status());
        dataLine.set__tls(this.get__tls());
        dataLine.setSortname(this.getSortname());
        dataLine.setSortorder(this.getSortorder());
        dataLine.set_token(this.get_token());
        dataLine.setRequestId(this.getRequestId());
        dataLine.setProgramId(this.getProgramId());
        dataLine.setLastUpdateLogin(this.getLastUpdateLogin());
        dataLine.setCreatedBy(this.getCreatedBy());
        dataLine.setCreationDate(this.getCreationDate());
        dataLine.setLastUpdatedBy(this.getLastUpdatedBy());
        dataLine.setLastUpdateDate(this.getLastUpdateDate());
        dataLine.setAttributeCategory(this.getAttributeCategory());
        dataLine.setAttribute1(this.getAttribute1());
        dataLine.setAttribute2(this.getAttribute2());
        dataLine.setAttribute3(this.getAttribute3());
        dataLine.setAttribute4(this.getAttribute4());
        dataLine.setAttribute5(this.getAttribute5());
        dataLine.setAttribute6(this.getAttribute6());
        dataLine.setAttribute7(this.getAttribute7());
        dataLine.setAttribute8(this.getAttribute8());
        dataLine.setAttribute9(this.getAttribute9());
        dataLine.setAttribute10(this.getAttribute10());
        dataLine.setAttribute11(this.getAttribute11());
        dataLine.setAttribute12(this.getAttribute12());
        dataLine.setAttribute13(this.getAttribute13());
        dataLine.setAttribute14(this.getAttribute14());
        dataLine.setAttribute15(this.getAttribute15());

        return dataLine;
    }

}
