package com.hand.hec.bpm.dto;

/**
 * Auto Generated By Code Generator
 * Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.JoinCode;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Component
@ExtensionAttribute(disable = true)
@Table(name = "bpm_tplt_button")
public class TpltButton extends BaseDTO {

    public static final String FIELD_BUTTON_ID = "buttonId";
    public static final String FIELD_TEMPLATE_ID = "templateId";
    public static final String FIELD_BUTTON_SEQUENCE = "buttonSequence";
    public static final String FIELD_BUTTON_CODE = "buttonCode";
    public static final String FIELD_BUTTON_DESC = "buttonDesc";
    public static final String FIELD_ID = "id";
    public static final String FIELD_TEXT = "text";
    public static final String FIELD_CLICK = "click";
    public static final String FIELD_BUTTON_TYPE = "buttonType";
    public static final String FIELD_BUTTON_TYPE_DESC = "buttonTypeDesc";
    public static final String FIELD_WIDTH = "width";
    public static final String FIELD_HEIGHT = "height";
    public static final String FIELD_ICON = "icon";
    public static final String FIELD_DISABLED = "disabled";
    public static final String FIELD_HIDDEN = "hidden";
    public static final String FIELD_STYLE = "style";
    public static final String FIELD_BTNSTYLE = "btnstyle";
    public static final String FIELD_OPERATION_TYPE = "operationType";
    public static final String FIELD_TEXT_DISPLAY = "textDisplay";
    public static final String FIELD_OPERATION_TYPE_DESC = "operationTypeDesc";

    @Id
    @GeneratedValue
    @Where
    private Long buttonId;//按钮ID

    @Where
    private Long templateId;//所属模板ID

    private Long buttonSequence;//按钮顺序

    @NotEmpty
    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String buttonCode;//按钮代码

    @Length(max = 200)
    @Where(comparison = Comparison.LIKE)
    private String buttonDesc;//按钮描述

    @Length(max = 200)
    private String id;//ID

    @Length(max = 200)
    private String text;//按钮文本

    @Length(max = 200)
    private String click;//点击触发方法

    @Length(max = 200)
    private String buttonType;//按钮类型

    @JoinCode(code = "BPM.BUTTON_TYPE", joinKey = TpltButton.FIELD_BUTTON_TYPE)
    @Transient
    private String buttonTypeDesc;

    private Long width;//宽度

    private Long height;//高度

    @Length(max = 200)
    private String icon;//图标地址

    @Length(max = 200)
    private String disabled;//失效

    @Length(max = 200)
    private String hidden;//隐藏

    @Length(max = 200)
    private String style;//样式

    @Length(max = 200)
    private String btnstyle;//按钮样式

    @NotEmpty
    @Length(max = 200)
    private String operationType;//操作类别 按钮的操作属性（操作/查看）

    @Transient
    private String textDisplay; //描述

    @Transient
    @JoinCode(code = "BPM.BUTTON_OPERATOR_TYPE", joinKey = TpltButton.FIELD_OPERATION_TYPE)
    private String operationTypeDesc;


    public void setButtonId(Long buttonId) {
        this.buttonId = buttonId;
    }

    public Long getButtonId() {
        return buttonId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getTemplateId() {
        return templateId;
    }

    public void setButtonSequence(Long buttonSequence) {
        this.buttonSequence = buttonSequence;
    }

    public Long getButtonSequence() {
        return buttonSequence;
    }

    public void setButtonCode(String buttonCode) {
        this.buttonCode = buttonCode;
    }

    public String getButtonCode() {
        return buttonCode;
    }

    public void setButtonDesc(String buttonDesc) {
        this.buttonDesc = buttonDesc;
    }

    public String getButtonDesc() {
        return buttonDesc;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setClick(String click) {
        this.click = click;
    }

    public String getClick() {
        return click;
    }

    public void setButtonType(String buttonType) {
        this.buttonType = buttonType;
    }

    public String getButtonType() {
        return buttonType;
    }

    public void setWidth(Long width) {
        this.width = width;
    }

    public Long getWidth() {
        return width;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getHeight() {
        return height;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getIcon() {
        return icon;
    }

    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }

    public String getDisabled() {
        return disabled;
    }

    public void setHidden(String hidden) {
        this.hidden = hidden;
    }

    public String getHidden() {
        return hidden;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public String getStyle() {
        return style;
    }

    public void setBtnstyle(String btnstyle) {
        this.btnstyle = btnstyle;
    }

    public String getBtnstyle() {
        return btnstyle;
    }

    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    public String getOperationType() {
        return operationType;
    }

    public String getTextDisplay() {
        return textDisplay;
    }

    public void setTextDisplay(String textDisplay) {
        this.textDisplay = textDisplay;
    }

    public String getOperationTypeDesc() {
        return operationTypeDesc;
    }

    public void setOperationTypeDesc(String operationTypeDesc) {
        this.operationTypeDesc = operationTypeDesc;
    }

    public String getButtonTypeDesc() {
        return buttonTypeDesc;
    }

    public void setButtonTypeDesc(String buttonTypeDesc) {
        this.buttonTypeDesc = buttonTypeDesc;
    }
}
