package com.hand.hec.fnd.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "fnd_business_rule")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class FndBusinessRule extends BaseDTO {

    public static final String FIELD_BUSINESS_RULE_ID = "businessRuleId";
    public static final String FIELD_BUSINESS_RULE_CODE = "businessRuleCode";
    public static final String FIELD_BUSINESS_RULE_NAME = "businessRuleName";
    public static final String FIELD_DOC_CATEGORY = "docCategory";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";


    /**
     * 权限规则ID
     */
    @Id
    @GeneratedValue
    private Long businessRuleId;

    /**
     * 权限规则代码
     */
    @NotEmpty
    @Length(max = 30)
    private String businessRuleCode;

    /**
     * 权限规则名称
     */
    @Length(max = 240)
    @MultiLanguageField
    private String businessRuleName;

    /**
     * 单据类别
     */
    @NotEmpty
    @Length(max = 30)
    private String docCategory;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;
}
