package com.hand.hec.fnd.dto;

/**
 * Auto Generated By Code Generator Description:
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable = true)
@Table(name = "fnd_doc_info")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
@Component
public class FndDocInfo extends BaseDTO {

    public static final String FIELD_DOC_INFO_ID = "docInfoId";
    public static final String FIELD_DOC_CATEGORY = "docCategory";
    public static final String FIELD_PARENT_DOC_INFO_ID = "parentDocInfoId";
    public static final String FIELD_TABLE_LEVEL_CODE = "tableLevelCode";
    public static final String FIELD_TABLE_NAME = "tableName";
    public static final String FIELD_TABLE_PARAM_NAME = "tableParamName";
    public static final String FIELD_ID_FIELD_NAME = "idFieldName";
    public static final String FIELD_NUMBER_FIELD_NAME = "numberFieldName";
    public static final String FIELD_TYPE_FIELD_NAME = "typeFieldName";
    public static final String FIELD_SQL_CONTENT = "sqlContent";
    public static final String FIELD_AMOUNT_FIELD_NAME = "amountFieldName";

    public static final String TABLE_LEVEL_SUM = "SUM";
    public static final String TABLE_LEVEL_HEAD = "HEAD";
    public static final String TABLE_LEVEL_LINE = "LINE";
    public static final String TABLE_LEVEL_DIST = "DIST";

    public static final String COLUMN_COMPANY_ID = "company_id";
    public static final String COLUMN_UNIT_ID = "unit_id";
    public static final String COLUMN_POSITION_ID = "position_id";
    public static final String COLUMN_EMPLOYEE_ID = "employee_id";
    public static final String COLUMN_CREATED_BY = "created_by";

    public static final String DOC_CATEGORY_BGT_JOURNAL = "06";
    public static final String DOC_CATEGORY_EXP_REPORT = "02";
    public static final String DOC_CATEGORY_EXP_REQUISITION = "01";
    public static final String DOC_CATEGORY_CSH_PAY_REQ = "04";
    public static final String DOC_CATEGORY_CSH_TRANSACTION = "03";
    public static final String DOC_CATEGORY_PAYMENT_BATCH = "36";
    public static final String DOC_CATEGORY_ACP_PAY_REQ = "08";
    public static final String DOC_CATEGORY_REPAYMENT_REGISTER = "17";


    /**
     * 主键
     */
    @Id
    @GeneratedValue
    private Long docInfoId;

    /**
     * 单据类别
     */
    @NotEmpty
    @Length(max = 23)
    private String docCategory;

    /**
     * 父单据信息ID
     */
    private Long parentDocInfoId;

    /**
     * 表级别
     */
    @Length(max = 23)
    private String tableLevelCode;

    /**
     * 表名
     */
    @NotEmpty
    @Length(max = 23)
    private String tableName;

    /**
     * 参数名称
     */
    @NotEmpty
    @Length(max = 23)
    private String tableParamName;

    /**
     * ID字段名称
     */
    @NotEmpty
    @Length(max = 23)
    private String idFieldName;

    /**
     * 编码字段名称
     */
    @Length(max = 23)
    private String numberFieldName;

    /**
     * 类型字段名称
     */
    @Length(max = 23)
    private String typeFieldName;

    /**
     * SQL内容
     */
    @NotEmpty
    @Length(max = 23)
    private String sqlContent;

    /**
     * 金额字段名称
     */
    @Length(max = 23)
    private String amountFieldName;

}
