package com.hand.hec.gld.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import com.hand.hec.bgt.dto.BgtCenter;
import com.hand.hec.bgt.dto.BgtEntity;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;
import javax.validation.constraints.NotNull;

/**
 * <p>
 *核算主体级成本中心关联预算中心表
 * </p>
 *
 * @author rui.shi@hand-china.com 2019/01/08 13:50
 */

@ExtensionAttribute(disable = true)
@Table(name = "gld_resp_center_ref_bc")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class GldRespCenterRefBc extends BaseDTO {

	public static final String FIELD_REF_ID = "refId";
	public static final String FIELD_RESP_CENTER_ID = "respCenterId";
	public static final String FIELD_BGT_ENTITY_ID = "bgtEntityId";
	public static final String FIELD_BGT_CENTER_ID = "bgtCenterId";
	public static final String FIELD_DEFAULT_FLAG = "defaultFlag";
	public static final String FIELD_ENABLED_FLAG = "enabledFlag";
	public static final String FIELD_BGT_ENTITY_NAME = "bgtEntityName";
	public static final String FIELD_BGT_CENTER_NAME = "bgtCenterName";


	@Id
	@GeneratedValue
	private Long refId;

	/**
	 * 成本中心ID
	 */
	@NotNull
	@Where
	private Long respCenterId;

	/**
	 * 预算实体ID
	 */
	@JoinTable(name = "bgtEntityJoin", joinMultiLanguageTable = true, target = BgtEntity.class,
			type = JoinType.LEFT, on = {@JoinOn(joinField = BgtEntity.FIELD_ENTITY_ID)})
	@NotNull
	private Long bgtEntityId;

	/**
	 * 预算中心ID
	 */
	@JoinTable(name = "bgtCenterJoin", joinMultiLanguageTable = true, target = BgtCenter.class,
			type = JoinType.LEFT, on = {@JoinOn(joinField = BgtCenter.FIELD_CENTER_ID)})
	@NotNull
	private Long bgtCenterId;

	/**
	 * 默认标志
	 */
	@Length(max = 1)
	private String defaultFlag;

	/**
	 * 启用标志
	 */
	@Length(max = 1)
	private String enabledFlag;


	/**
	 * 预算实体名称
	 */
	@JoinColumn(joinName = "bgtEntityJoin", field = BgtEntity.FIELD_DESCRIPTION)
	@Transient
	@Length(max = 500)
	private String bgtEntityName;


	/**
	 * 预算中心名称
	 */
	@Transient
	@Length(max = 500)
	@JoinColumn(joinName = "bgtCenterJoin", field = BgtCenter.FIELD_DESCRIPTION)
	private String bgtCenterName;

}
