package com.hand.hec.gld.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hap.system.dto.BaseDTO;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;
import javax.validation.constraints.NotNull;

/**
 * <p>
 * 核算主体级责任中心层级
 * </p>
 *
 * @author rui.shi@hand-china.com 2019/01/08 13:50
 */

@ExtensionAttribute(disable = true)
@Table(name = "gld_resp_center_hierarchy")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class GldRespCenterHierarchy extends BaseDTO {

    public static final String FIELD_HIERARCHY_ID = "hierarchyId";
    public static final String FIELD_PARENT_RESP_CENTER_ID = "parentRespCenterId";
    public static final String FIELD_RESPONSIBILITY_CENTER_ID = "responsibilityCenterId";
    public static final String FIELD_START_PERIOD_NAME = "startPeriodName";
    public static final String FIELD_END_PERIOD_NAME = "endPeriodName";
	public static final String FIELD_RESPONSIBILITY_CENTER_CODE = "responsibilityCenterCode";
	public static final String FIELD_RESPONSIBILITY_CENTER_NAME = "responsibilityCenterName";

    @Id
    @GeneratedValue
    private Long hierarchyId;

    /**
     * 父责任中心ID
     */
    @NotNull
	@JoinTable(name = "respCenterJoin", joinMultiLanguageTable = true, target = GldResponsibilityCenter.class,
			type = JoinType.LEFT, on = {@JoinOn(joinField = GldResponsibilityCenter.FIELD_RESPONSIBILITY_CENTER_ID)})
	@Where
    private Long parentRespCenterId;

    /**
     * 子责任中心ID
     */
    @NotNull
    private Long responsibilityCenterId;

    /**
     * 启用期间
     */
    @NotEmpty
    @Length(max = 30)
    private String startPeriodName;
    
    /**
     * 关闭期间
     */
    @Length(max = 30)
    private String endPeriodName;



    @Transient
	@JoinColumn(joinName = "respCenterJoin", field = GldResponsibilityCenter.FIELD_RESPONSIBILITY_CENTER_CODE)
	@Where
	private String responsibilityCenterCode;

    @Transient
	@JoinColumn(joinName = "respCenterJoin", field = GldResponsibilityCenter.FIELD_RESPONSIBILITY_CENTER_NAME)
	@Where
	private String responsibilityCenterName;
}
