package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.*;

import com.hand.hap.account.dto.User;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.core.annotation.Order;

/**
 * <p>
 * 工作流审批记录
 * </p>
 * 
 * @author mouse 2019/02/18 19:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "wfl_approve_record")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflApproveRecord extends BaseDTO {

    public static final String FIELD_RECORD_ID = "recordId";
    public static final String FIELD_INSTANCE_ID = "instanceId";
    public static final String FIELD_INS_TASK_ID = "insTaskId";
    public static final String FIELD_ACTION_ID = "actionId";
    public static final String FIELD_ACTION_TYPE = "actionType";
    public static final String FIELD_COMMENT_TEXT = "commentText";
    public static final String FIELD_INS_RECIPIENT_ID = "insRecipientId";
    public static final String FIELD_INS_HIERARCHY_ID = "insHierarchyId";
    public static final String FIELD_APPROVER_ID = "approverId";
    public static final String FIELD_APPROVE_DATE = "approveDate";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    @OrderBy(value = "asc")
    private Long recordId;

    /**
     * 实例ID
     */
    @Where
    private Long instanceId;

    /**
     * 任务ID
     */
    @Where
    private Long insTaskId;

    /**
     * 动作ID
     */
    private Long actionId;

    /**
     * 动作类型
     */
    @NotEmpty
    @Length(max = 30)
    private String actionType;

    /**
     * 审批意见
     */
    @Length(max = 2000)
    private String commentText;

    /**
     * 工作流待办事项ID
     */
    private Long insRecipientId;

    /**
     * 工作流接受者层次ID
     */
    private Long insHierarchyId;

    /**
     * 审批者ID
     */
    @JoinTable(name = "approverJoin", target = User.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = User.FIELD_USER_ID)})
    private Long approverId;

    @Transient
    @JoinColumn(joinName = "approverJoin", field = User.FIELD_DESCRIPTION)
    private String approverName;

    @Transient
    @JoinColumn(joinName = "approverJoin", field = User.FIELD_USER_NAME)
    private String approverCode;
    /**
     * 审批日期
     */
    private Date approveDate;

}
