package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hec.fnd.dto.FndBusinessRule;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_deliver_biz_rule_assign")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflDeliverBizRuleAssign extends BaseDTO {

    public static final String FIELD_ASSIGN_ID = "assignId";
    public static final String FIELD_DELIVER_ID = "deliverId";
    public static final String FIELD_BUSINESS_RULE_ID = "businessRuleId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";


    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long assignId;

    /**
     * 接收ID
     */
    @Where
    private Long deliverId;

    /**
     * 权限规则ID
     */
    @JoinTable(name = "businessRuleJoin", type = JoinType.LEFT, target = FndBusinessRule.class,
                    joinMultiLanguageTable = true, on = {@JoinOn(joinField = FndBusinessRule.FIELD_BUSINESS_RULE_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long businessRuleId;

    @Transient
    @JoinColumn(joinName = "businessRuleJoin", field = FndBusinessRule.FIELD_BUSINESS_RULE_NAME)
    private String businessRuleName;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;
}
