package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import com.hand.hec.fnd.dto.FndDocTypeV;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_doc_process_assign")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflDocProcessAssign extends BaseDTO {

    public static final String FIELD_ASSIGN_ID = "assignId";
    public static final String FIELD_PRIORITY = "priority";
    public static final String FIELD_DOC_CATEGORY = "docCategory";
    public static final String FIELD_DOC_TYPE_ID = "docTypeId";
    public static final String FIELD_PROCESS_ID = "processId";
    public static final String FIELD_START_DATE = "startDate";
    public static final String FIELD_END_DATE = "endDate";


    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long assignId;

    /**
     * 优先级
     */
    private Long priority;

    /**
     * 单据类别
     */
    @NotEmpty
    @Length(max = 30)
    @Where
    private String docCategory;

    /**
     * 单据类型ID
     */
    @Where
    @JoinTable(name = "docTypeJoin", type = JoinType.LEFT, target = FndDocTypeV.class,
                    on = {@JoinOn(joinField = FndDocTypeV.FIELD_DOC_TYPE_ID),
                            @JoinOn(joinField = FndDocTypeV.FIELD_DOC_CATEGORY, joinExpression = "a0.doc_category")})
    private Long docTypeId;

    @Transient
    @JoinColumn(joinName = "docTypeJoin", field = FndDocTypeV.FIELD_DOC_TYPE_NAME)
    private String docTypeName;

    /**
     * 流程ID
     */
    @JoinTable(name = "processJoin", target = WflProcess.class, joinMultiLanguageTable = true, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflProcess.FIELD_PROCESS_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    @Where
    private Long processId;

    @Transient
    @JoinColumn(joinName = "processJoin", field = WflProcess.FIELD_PROCESS_NAME)
    private String processName;

    /**
     * 开始日期
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date startDate;

    /**
     * 结束日期
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date endDate;

}
