package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.JoinCode;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;

import java.util.Map;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_event")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflEvent extends BaseDTO {

    public static final String FIELD_EVENT_ID = "eventId";
    public static final String FIELD_PROCESS_ID = "processId";
    public static final String FIELD_EVENT_CODE = "eventCode";
    public static final String FIELD_EVENT_NAME = "eventName";
    public static final String FIELD_EVENT_TYPE = "eventType";


    public static final String ELEMENT_EVENT = "EVENT";

    public static final String EVENT_TYPE_START = "START";
    public static final String EVENT_TYPE_END = "END";

    /**
     * 事件ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long eventId;

    /**
     * 工作流ID
     */
    @Where
    private Long processId;

    /**
     * 事件代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where(comparison = Comparison.LIKE)
    private String eventCode;

    /**
     * 事件名称
     */
    @MultiLanguageField
    @Length(max = 240)
    @Where(comparison = Comparison.LIKE)
    private String eventName;

    /**
     * 事件类型
     */
    @NotEmpty
    @Length(max = 30)
    private String eventType;

    /**
     * ID
     */
    @JoinCode(code = "WFL.EVENT_TYPE", joinKey = FIELD_EVENT_TYPE)
    @Transient
    private String eventTypeName;

    public WflEvent(Map map) {
        this.setEventId(Long.parseLong(map.get("element_id").toString()));
        this.setEventCode(map.get("element_code").toString());
        this.setEventName(map.get("element_name").toString());
    }
}


