package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;

import java.util.Map;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_flow")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflFlow extends BaseDTO {

    public static final String FIELD_FLOW_ID = "flowId";
    public static final String FIELD_PROCESS_ID = "processId";
    public static final String FIELD_FLOW_CODE = "flowCode";
    public static final String FIELD_FLOW_NAME = "flowName";
    public static final String FIELD_FROM_ELEMENT_TYPE = "fromElementType";
    public static final String FIELD_FROM_ELEMENT_ID = "fromElementId";
    public static final String FIELD_TO_ELEMENT_TYPE = "toElementType";
    public static final String FIELD_TO_ELEMENT_ID = "toElementId";
    public static final String FIELD_FLOW_VALUE = "flowValue";
    public static final String FIELD_SEQUENCE = "sequence";


    public static final String ELEMENT_FLOW = "FLOW";

    /**
     * 流转ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long flowId;

    /**
     * 工作流ID
     */
    @Where
    private Long processId;

    /**
     * 流转代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where(comparison = Comparison.LIKE)
    private String flowCode;

    /**
     * 流转名称
     */
    @Length(max = 240)
    @MultiLanguageField
    @Where(comparison = Comparison.LIKE)
    private String flowName;

    /**
     * 输入元素类型
     */
    @NotEmpty
    @Length(max = 30)
    private String fromElementType;

    /**
     * 输入元素ID
     */
    @JoinTable(name = "fromElementJoin", target = WflElement.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflElement.FIELD_ELEMENT_ID),
                            @JoinOn(joinField = WflElement.FIELD_ELEMENT_TYPE, joinExpression = "from_element_type")})
    private Long fromElementId;

    @Transient
    @JoinColumn(joinName = "fromElementJoin", field = WflElement.FIELD_ELEMENT_NAME)
    private String fromElementName;

    /**
     * 输出元素类型
     */
    @NotEmpty
    @Length(max = 30)
    private String toElementType;

    /**
     * 输出元素ID
     */
    @JoinTable(name = "toElementJoin", target = WflElement.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflElement.FIELD_ELEMENT_ID),
                            @JoinOn(joinField = WflElement.FIELD_ELEMENT_TYPE, joinExpression = "to_element_type")})
    private Long toElementId;

    @Transient
    @JoinColumn(joinName = "toElementJoin", field = WflElement.FIELD_ELEMENT_NAME)
    private String toElementName;

    /**
     * 流转判定值
     */
    @Length(max = 2000)
    private String flowValue;

    /**
     * 流转顺序
     */
    private Long sequence;

    @Transient
    @JoinCode(code = "WFL_ELEMENT_TYPE", joinKey = FIELD_FROM_ELEMENT_TYPE)
    private String fromElementTypeName;

    @Transient
    @JoinCode(code = "WFL_ELEMENT_TYPE", joinKey = FIELD_TO_ELEMENT_TYPE)
    private String toElementTypeName;

    @Transient
    private String fromElementCode;

    @Transient
    private String toElementCode;

    public WflFlow(Map map) {
        this.setFlowId(Long.parseLong(map.get("element_id").toString()));
        this.setFlowCode(map.get("element_code").toString());
        this.setFlowName(map.get("element_name").toString());
        this.setFromElementId(Long.parseLong(map.get("from_element_id").toString()));
        this.setFromElementType(map.get("from_element_type").toString());
        this.setToElementId(Long.parseLong(map.get("to_element_id").toString()));
        this.setToElementType(map.get("to_element_type").toString());
        this.setSequence(Long.parseLong(map.get("sequence").toString()));
    }
}
