package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_gateway_biz_rule_group")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflGatewayBizRuleGroup extends BaseDTO {

    public static final String FIELD_GROUP_ID = "groupId";
    public static final String FIELD_GATEWAY_ID = "gatewayId";
    public static final String FIELD_SEQUENCE = "sequence";
    public static final String FIELD_GROUP_CODE = "groupCode";
    public static final String FIELD_GROUP_NAME = "groupName";
    public static final String FIELD_FLOW_ID = "flowId";
    public static final String FIELD_ADJUST_TYPE = "adjustType";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";


    public static final String ADJUST_TYPE_ONE = "ONE";
    public static final String ADJUST_TYPE_ALL = "ALL";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long groupId;

    /**
     * 接收ID
     */
    @Where
    private Long gatewayId;

    /**
     * 序号
     */
    private Long sequence;

    /**
     * 权限组代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where(comparison = Comparison.LIKE)
    private String groupCode;

    /**
     * 权限组名称
     */
    @Length(max = 30)
    @MultiLanguageField
    @Where(comparison = Comparison.LIKE)
    private String groupName;

    /**
     * 流转ID
     */
    @JoinTable(name = "flowJoin", target = WflFlow.class, joinMultiLanguageTable = true, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflFlow.FIELD_FLOW_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    @Where
    private Long flowId;

    @Transient
    @JoinColumn(joinName = "flowJoin", field = WflFlow.FIELD_FLOW_NAME)
    private String flowName;

    /**
     * 权限明细判断类型
     */
    @NotEmpty
    @Length(max = 30)
    private String adjustType;

    @Transient
    @JoinCode(code = "WFL_BUSINESS_RULE_ADJUST_TYPE", joinKey = FIELD_ADJUST_TYPE)
    private String adjustTypeName;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

}
