package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ins_task")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflInsTask extends BaseDTO {

    public static final String FIELD_INS_TASK_ID = "insTaskId";
    public static final String FIELD_INSTANCE_ID = "instanceId";
    public static final String FIELD_TASK_ID = "taskId";
    public static final String FIELD_RESULT = "result";
    public static final String FIELD_ARRIVAL_STATUS = "arrivalStatus";
    public static final String FIELD_ARRIVAL_DATE = "arrivalDate";
    public static final String FIELD_DEPARTURE_DATE = "departureDate";


    public static final String ARRIVAL_STATUS_NOT_ARRIVED = "NOT_ARRIVED";
    public static final String ARRIVAL_STATUS_ARRIVED = "ARRIVED";
    public static final String ARRIVAL_STATUS_PASSED = "PASSED";

    public static final String TASK_RESULT_AGREE = "AGREE";
    public static final String TASK_RESULT_REJECT = "REJECT";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long insTaskId;

    /**
     * 实例ID
     */
    @Where
    private Long instanceId;

    /**
     * 任务ID
     */
    @Where
    @JoinTable(name = "taskJoin", target = WflTask.class, type = JoinType.LEFT, joinMultiLanguageTable = true,
                    on = {@JoinOn(joinField = WflTask.FIELD_TASK_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long taskId;

    @Transient
    @JoinColumn(joinName = "taskJoin", field = WflTask.FIELD_TASK_NAME)
    private String taskName;

    /**
     * 执行结果
     */
    @Length(max = 200)
    private String result;

    /**
     * 抵达状态
     */
    @NotEmpty
    @Length(max = 30)
    private String arrivalStatus;

    /**
     * 抵达日期
     */
    private Date arrivalDate;

    /**
     * 离开日期
     */
    private Date departureDate;


}
