package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ins_flow")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflInsFlow extends BaseDTO {

    public static final String FIELD_INS_FLOW_ID = "insFlowId";
    public static final String FIELD_INSTANCE_ID = "instanceId";
    public static final String FIELD_FLOW_ID = "flowId";
    public static final String FIELD_FROM_ELEMENT_TYPE = "fromElementType";
    public static final String FIELD_FROM_ELEMENT_ID = "fromElementId";
    public static final String FIELD_TO_ELEMENT_TYPE = "toElementType";
    public static final String FIELD_TO_ELEMENT_ID = "toElementId";
    public static final String FIELD_RESULT = "result";
    public static final String FIELD_ARRIVAL_STATUS = "arrivalStatus";
    public static final String FIELD_ARRIVAL_DATE = "arrivalDate";
    public static final String FIELD_DEPARTURE_DATE = "departureDate";
    public static final String FIELD_SEQUENCE = "sequence";

    public static final String ARRIVAL_STATUS_NOT_ARRIVED = "NOT_ARRIVED";
    public static final String ARRIVAL_STATUS_ARRIVED = "ARRIVED";
    public static final String ARRIVAL_STATUS_PASSED = "PASSED";
    public static final String ARRIVAL_STATUS_UNREACHABLE = "UNREACHABLE";



    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long insFlowId;

    /**
     * 实例ID
     */
    @Where
    private Long instanceId;

    /**
     * 流转ID
     */
    @Where
    private Long flowId;

    /**
     * 来源元素类别
     */
    @Length(max = 30)
    private String fromElementType;

    /**
     * 来源元素ID
     */
    private Long fromElementId;

    /**
     * 目标元素类别
     */
    @Length(max = 30)
    private String toElementType;

    /**
     * 目标元素ID
     */
    private Long toElementId;

    /**
     * 执行结果
     */
    @Length(max = 200)
    private String result;

    /**
     * 抵达状态
     */
    @NotEmpty
    @Length(max = 30)
    private String arrivalStatus;

    /**
     * 抵达日期
     */
    private Date arrivalDate;

    /**
     * 离开日期
     */
    private Date departureDate;

    /**
     * 流程顺序，用于网关后的顺序判断
     */
    private Long sequence;

}
