package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ins_task_recipient_ht")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflInsTaskRecipientHt extends BaseDTO {

    public static final String FIELD_INS_RECIPIENT_ID = "insRecipientId";
    public static final String FIELD_INSTANCE_ID = "instanceId";
    public static final String FIELD_INS_TASK_ID = "insTaskId";
    public static final String FIELD_INS_HIERARCHY_ID = "insHierarchyId";
    public static final String FIELD_SEQUENCE = "sequence";
    public static final String FIELD_APPROVER_ID = "approverId";
    public static final String FIELD_COMMISSION_BY = "commissionBy";
    public static final String FIELD_COMMISSION_DATE = "commissionDate";
    public static final String FIELD_LIMITED_DATE = "limitedDate";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long insRecipientId;

    /**
     * 实例ID
     */
    @Where
    private Long instanceId;

    /**
     * 实例任务ID
     */
    @Where
    private Long insTaskId;

    /**
     * 工作流实例审批层次ID
     */
    @Where
    private Long insHierarchyId;

    /**
     * 序号
     */
    private Long sequence;

    /**
     * 审批者ID
     */
    private Long approverId;

    /**
     * 转交来源
     */
    private Long commissionBy;

    /**
     * 转交日期
     */
    private Date commissionDate;

    /**
     * 时限日期
     */
    private Date limitedDate;

    public WflInsTaskRecipientHt(WflInsTaskRecipient insTaskRecipient) {
        this.setApproverId(insTaskRecipient.getApproverId());
        this.setCommissionBy(insTaskRecipient.getCommissionBy());
        this.setCommissionDate(insTaskRecipient.getCommissionDate());
        this.setInsHierarchyId(insTaskRecipient.getInsHierarchyId());
        this.setInsRecipientId(insTaskRecipient.getInsRecipientId());
        this.setInstanceId(insTaskRecipient.getInstanceId());
        this.setInsTaskId(insTaskRecipient.getInsTaskId());
        this.setLimitedDate(insTaskRecipient.getLimitedDate());
        this.setSequence(insTaskRecipient.getSequence());

        this.setCreatedBy(insTaskRecipient.getCreatedBy());
        this.setCreationDate(insTaskRecipient.getCreationDate());
        this.setLastUpdatedBy(insTaskRecipient.getLastUpdatedBy());
        this.setLastUpdateDate(insTaskRecipient.getLastUpdateDate());
        this.setObjectVersionNumber(insTaskRecipient.getObjectVersionNumber());
    }

}
