package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.account.dto.User;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.JoinColumn;
import com.hand.hap.mybatis.common.query.JoinOn;
import com.hand.hap.mybatis.common.query.JoinTable;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ins_task_recipient")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflInsTaskRecipient extends BaseDTO {

    public static final String FIELD_INS_RECIPIENT_ID = "insRecipientId";
    public static final String FIELD_INSTANCE_ID = "instanceId";
    public static final String FIELD_INS_TASK_ID = "insTaskId";
    public static final String FIELD_INS_HIERARCHY_ID = "insHierarchyId";
    public static final String FIELD_SEQUENCE = "sequence";
    public static final String FIELD_APPROVER_ID = "approverId";
    public static final String FIELD_COMMISSION_BY = "commissionBy";
    public static final String FIELD_COMMISSION_DATE = "commissionDate";
    public static final String FIELD_LIMITED_DATE = "limitedDate";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long insRecipientId;

    /**
     * 实例ID
     */
    @Where
    private Long instanceId;

    /**
     * 实例任务ID
     */
    @Where
    private Long insTaskId;

    /**
     * 工作流实例审批层次ID
     */
    @Where
    private Long insHierarchyId;

    /**
     * 序号
     */
    private Long sequence;

    /**
     * 审批者ID
     */
    @JoinTable(name = "approverJoin", target = User.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = User.FIELD_USER_ID)})
    private Long approverId;

    @Transient
    @JoinColumn(joinName = "approverJoin", field = User.FIELD_DESCRIPTION)
    private String approverName;

    @Transient
    @JoinColumn(joinName = "approverJoin", field = User.FIELD_USER_NAME)
    private String approverCode;

    /**
     * 转交来源
     */
    private Long commissionBy;

    /**
     * 转交日期
     */
    private Date commissionDate;

    /**
     * 时限日期
     */
    private Date limitedDate;


}
