package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ins_task_receiver")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflInsTaskReceiver extends BaseDTO {

    public static final String FIELD_INS_RECEIVER_ID = "insReceiverId";
    public static final String FIELD_INSTANCE_ID = "instanceId";
    public static final String FIELD_INS_TASK_ID = "insTaskId";
    public static final String FIELD_RECEIVER_ID = "receiverId";
    public static final String FIELD_SEQUENCE = "sequence";
    public static final String FIELD_RECEIVER_CATEGORY = "receiverCategory";
    public static final String FIELD_RECEIVER_TYPE = "receiverType";
    public static final String FIELD_RECEIVER_PARAM1_ID = "receiverParam1Id";
    public static final String FIELD_RECEIVER_PARAM1_CODE = "receiverParam1Code";
    public static final String FIELD_RECEIVER_PARAM2_ID = "receiverParam2Id";
    public static final String FIELD_RECEIVER_PARAM2_CODE = "receiverParam2Code";
    public static final String FIELD_RECEIVER_PARAM3_ID = "receiverParam3Id";
    public static final String FIELD_RECEIVER_PARAM3_CODE = "receiverParam3Code";
    public static final String FIELD_RECEIVER_PARAM4_ID = "receiverParam4Id";
    public static final String FIELD_RECEIVER_PARAM4_CODE = "receiverParam4Code";
    public static final String FIELD_POST_VALIDATION_FLAG = "postValidationFlag";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long insReceiverId;

    /**
     * 实例ID
     */
    @Where
    private Long instanceId;

    /**
     * 实例任务ID
     */
    @Where
    private Long insTaskId;

    /**
     * 接受者ID
     */
    @Where
    private Long receiverId;

    /**
     * 接受者序号
     */
    private Long sequence;

    /**
     * 接受者类别
     */
    @NotEmpty
    @Length(max = 300)
    private String receiverCategory;

    /**
     * 接受者类型
     */
    @Length(max = 30)
    private String receiverType;

    /**
     * 接收者参数1ID
     */
    private Long receiverParam1Id;

    /**
     * 接收者参数1代码
     */
    @Length(max = 2000)
    private String receiverParam1Code;

    /**
     * 接收者参数2ID
     */
    private Long receiverParam2Id;

    /**
     * 接收者参数2代码
     */
    @Length(max = 2000)
    private String receiverParam2Code;

    /**
     * 接收者参数3ID
     */
    private Long receiverParam3Id;

    /**
     * 接收者参数3代码
     */
    @Length(max = 2000)
    private String receiverParam3Code;

    /**
     * 接收者参数4ID
     */
    private Long receiverParam4Id;

    /**
     * 接收者参数4代码
     */
    @Length(max = 2000)
    private String receiverParam4Code;

    /**
     * 通过校验标志
     */
    @NotEmpty
    @Length(max = 1)
    private String postValidationFlag;

}
