package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_process")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflProcess extends BaseDTO {

    public static final String FIELD_PROCESS_ID = "processId";
    public static final String FIELD_PROCESS_CODE = "processCode";
    public static final String FIELD_PROCESS_NAME = "processName";
    public static final String FIELD_DOC_CATEGORY = "docCategory";
    public static final String FIELD_SUB_PROCESS_FLAG = "subProcessFlag";
    public static final String FIELD_PARENT_PROCESS_ID = "parentProcessId";
    public static final String FIELD_PROCESS_PAGE_ID = "processPageId";
    public static final String FIELD_VIEW_PAGE_ID = "viewPageId";
    public static final String FIELD_START_PROCEDURE_ID = "startProcedureId";
    public static final String FIELD_END_PROCEDURE_ID = "endProcedureId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_CONFIG_TYPE = "configType";
    public static final String FIELD_VERSION = "version";

    public static final String CONFIG_TYPE_SIMPLE = "SIMPLE";
    public static final String CONFIG_TYPE_STANDARD = "STANDARD";

    /**
     * 工作流ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long processId;

    /**
     * 工作流代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where(comparison = Comparison.LIKE)
    private String processCode;

    /**
     * 工作流名称
     */
    @Length(max = 240)
    @MultiLanguageField
    @Where(comparison = Comparison.LIKE)
    private String processName;

    /**
     * 单据类别
     */
    @NotEmpty
    @Length(max = 30)
    @Where
    private String docCategory;

    @Transient
    @JoinCode(code = "FND_DOC_CATEGORY", joinKey = WflProcess.FIELD_DOC_CATEGORY)
    private String docCategoryName;

    /**
     * 子流程标志
     */
    @NotEmpty
    @Length(max = 1)
    private String subProcessFlag;

    /**
     * 父流程ID
     */
    @JoinTable(name = "parentProcessJoin", joinMultiLanguageTable = true, target = WflProcess.class,
                    type = JoinType.LEFT, on = {@JoinOn(joinField = WflProcess.FIELD_PROCESS_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long parentProcessId;

    @Transient
    @JoinColumn(joinName = "parentProcessJoin", field = WflProcess.FIELD_PROCESS_NAME)
    private String parentProcessName;

    /**
     * 操作页面ID
     */
    @JoinTable(name = "processPageJoin", joinMultiLanguageTable = true, target = WflPage.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflPage.FIELD_PAGE_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long processPageId;

    @Transient
    @JoinColumn(joinName = "processPageJoin", field = WflPage.FIELD_PAGE_NAME)
    private String processPageName;

    /**
     * 查看页面ID
     */
    @JoinTable(name = "viewPageJoin", joinMultiLanguageTable = true, target = WflPage.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflPage.FIELD_PAGE_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long viewPageId;

    @Transient
    @JoinColumn(joinName = "viewPageJoin", field = WflPage.FIELD_PAGE_NAME)
    private String viewPageName;

    /**
     * 启动触发过程ID
     */
    @JoinTable(name = "startProcedureJoin", joinMultiLanguageTable = true, target = WflProcedure.class,
                    type = JoinType.LEFT, on = {@JoinOn(joinField = WflProcedure.FIELD_PROCEDURE_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long startProcedureId;

    @Transient
    @JoinColumn(joinName = "startProcedureJoin", field = WflProcedure.FIELD_PROCEDURE_NAME)
    private String startProcedureName;

    /**
     * 结束触发过程ID
     */
    @JoinTable(name = "endProcedureJoin", joinMultiLanguageTable = true, target = WflProcedure.class,
                    type = JoinType.LEFT, on = {@JoinOn(joinField = WflProcedure.FIELD_PROCEDURE_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long endProcedureId;

    @Transient
    @JoinColumn(joinName = "endProcedureJoin", field = WflProcedure.FIELD_PROCEDURE_NAME)
    private String endProcedureName;

    private String enabledFlag;

    private String configType;

    private Long version;
}
