package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.BaseConstants;
import com.hand.hap.function.dto.Resource;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import com.hand.hec.fnd.dto.FndBusinessRuleParameter;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_page")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflPage extends BaseDTO {

    public static final String FIELD_PAGE_ID = "pageId";
    public static final String FIELD_PAGE_CODE = "pageCode";
    public static final String FIELD_PAGE_NAME = "pageName";
    public static final String FIELD_SERVICE_ID = "resourceId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_SSC_FLAG = "sscFlag";
    public static final String FIELD_WFL_FLAG = "wflFlag";
    public static final String FIELD_DOC_CATEGORY = "docCategory";

    /**
     * 页面ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long pageId;

    /**
     * 页面代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where(comparison = Comparison.LIKE)
    private String pageCode;

    /**
     * 页面名称
     */
    @Length(max = 240)
    @MultiLanguageField
    @Where(comparison = Comparison.LIKE)
    private String pageName;

    /**
     * 资源ID
     */
    @JoinTable(name = "resourceJoin", target = Resource.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = Resource.FIELD_RESOURCE_ID)})
    private Long resourceId;

    @Transient
    @JoinColumn(joinName = "resourceJoin", field = Resource.FIELD_URL)
    private String url;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

    /**
     * 工作台标志
     */
    @NotEmpty
    @Length(max = 1)
    private String sscFlag;

    /**
     * 工作流标志
     */
    @NotEmpty
    @Length(max = 1)
    private String wflFlag;

    /**
     * 单据类别
     */
    @NotEmpty
    @Where
    @Length(max = 30)
    private String docCategory;

    @Transient
    @JoinCode(code = "WFL_WORKFLOW_CATEGORY", joinKey = FIELD_DOC_CATEGORY)
    private String docCategoryName;
}
