package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.JoinCode;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_procedure")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflProcedure extends BaseDTO {

    public static final String FIELD_PROCEDURE_ID = "procedureId";
    public static final String FIELD_PROCEDURE_CODE = "procedureCode";
    public static final String FIELD_PROCEDURE_NAME = "procedureName";
    public static final String FIELD_PROCEDURE_CONTENT = "procedureContent";
    public static final String FIELD_PROCEDURE_TYPE = "procedureType";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    /**
     * 过程ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long procedureId;

    /**
     * 过程代码
     */
    @NotEmpty
    @Length(max = 30)
    @Where(comparison = Comparison.LIKE)
    private String procedureCode;

    /**
     * 过程名称
     */
    @Length(max = 240)
    @MultiLanguageField
    @Where(comparison = Comparison.LIKE)
    private String procedureName;

    /**
     * 过程内容
     */
    @NotEmpty
    @Length(max = 2000)
    private String procedureContent;

    /**
     * 过程类型
     */
    @Length(max = 30)
    private String procedureType;

    @Transient
    @JoinCode(code = "WFL_PROCEDURE_TYPE", joinKey = FIELD_PROCEDURE_TYPE)
    private String procedureTypeName;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

}
