package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import lombok.*;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "wfl_process_action")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflProcessAction extends BaseDTO {

    public static final String FIELD_ACTION_ID = "actionId";
    public static final String FIELD_ACTION_TYPE = "actionType";
    public static final String FIELD_PROCESS_ID = "processId";
    public static final String FIELD_ACTION_NAME = "actionName";
    public static final String FIELD_PROCEDURE_ID = "procedureId";
    public static final String FIELD_SEND_TARGET_TASK_ID = "sendTargetTaskId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    public static final String ACTION_TYPE_AGREE = "AGREE";
    public static final String ACTION_TYPE_REJECT = "REJECT";
    public static final String ACTION_TYPE_SEND_TO = "SEND_TO";
    public static final String ACTION_TYPE_DELIVER = "DELIVER";
    public static final String ACTION_TYPE_SEND_BACK = "SEND_BACK";
    public static final String ACTION_TYPE_ADD_APPROVER = "ADD_APPROVER";
    public static final String ACTION_TYPE_ADD_TASK = "ADD_TASK";


    /**
     * 动作ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long actionId;

    /**
     * 动作类型
     */
    @NotEmpty
    @Length(max = 30)
    private String actionType;

    /**
     * 流程ID
     */
    @Where
    private Long processId;

    /**
     * 动作名称
     */
    @NotEmpty
    @Length(max = 64)
    @MultiLanguageField
    private String actionName;

    /**
     * 过程ID
     */
    @JoinTable(name = "procedureJoin", joinMultiLanguageTable = true, target = WflProcedure.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflProcedure.FIELD_PROCEDURE_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long procedureId;

    @Transient
    @JoinColumn(joinName = "procedureJoin", field = WflProcedure.FIELD_PROCEDURE_NAME)
    private String procedureName;

    /**
     * 跳转目标任务ID
     */
    @JoinTable(name = "taskJoin", joinMultiLanguageTable = true, target = WflTask.class, type = JoinType.LEFT,
                    on = {@JoinOn(joinField = WflTask.FIELD_TASK_ID),
                            @JoinOn(joinField = BaseDTO.FIELD_LANG, joinExpression = BaseConstants.PLACEHOLDER_LOCALE)})
    private Long sendTargetTaskId;

    @Transient
    @JoinColumn(joinName = "taskJoin", field = WflTask.FIELD_TASK_NAME)
    private String sendTargetTaskName;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

}
