package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_sub_process_task")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflSubProcessTask extends BaseDTO {

    public static final String FIELD_SUB_PROCESS_FIELD_ID = "subProcessTaskId";
    public static final String FIELD_TASK_ID = "taskId";
    public static final String FIELD_PROCESS_ID = "processId";
    public static final String FIELD_TASK_AUTO_PASS_FLAG = "taskAutoPassFlag";


    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long subProcessTaskId;

    @Where
    private Long taskId;

    /**
     * 流程ID
     */
    @Where
    private Long processId;

    /**
     * 节点自动通过标志
     */
    @NotEmpty
    @Length(max = 1)
    private String taskAutoPassFlag;

}
