package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.*;
import com.hand.hap.system.dto.CodeValue;
import lombok.*;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_task_receiver")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflTaskReceiver extends BaseDTO {

    public static final String FIELD_RECEIVER_ID = "receiverId";
    public static final String FIELD_TASK_ID = "taskId";
    public static final String FIELD_RECEIVER_CATEGORY = "receiverCategory";
    public static final String FIELD_RECEIVER_TYPE = "receiverType";
    public static final String FIELD_SEQUENCE = "sequence";
    public static final String FIELD_RECEIVER_PARAM1_ID = "receiverParam1Id";
    public static final String FIELD_RECEIVER_PARAM1_CODE = "receiverParam1Code";
    public static final String FIELD_RECEIVER_PARAM2_ID = "receiverParam2Id";
    public static final String FIELD_RECEIVER_PARAM2_CODE = "receiverParam2Code";
    public static final String FIELD_RECEIVER_PARAM3_ID = "receiverParam3Id";
    public static final String FIELD_RECEIVER_PARAM3_CODE = "receiverParam3Code";
    public static final String FIELD_RECEIVER_PARAM4_ID = "receiverParam4Id";
    public static final String FIELD_RECEIVER_PARAM4_CODE = "receiverParam4Code";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    /**
     * 接收ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long receiverId;

    /**
     * 任务ID
     */
    @Where
    private Long taskId;

    /**
     * 接收者类别
     */
    @NotEmpty
    @Length(max = 100)
    @JoinTable(name = "receiverCategoryJoin", target = CodeValue.class, type = JoinType.LEFT, on = {
            @JoinOn(joinField = "value"), @JoinOn(joinField = "codeId",
                            joinExpression = "(select code_id from sys_code_b sc where sc.code = \"WFL_RECEIVER_CATEGORY\")")})
    private String receiverCategory;

    @Transient
    @JoinCode(code = "WFL_RECEIVER_CATEGORY", joinKey = FIELD_RECEIVER_CATEGORY)
    private String receiverCategoryName;

    @Transient
    @JoinColumn(joinName = "receiverCategoryJoin", field = "tag")
    private String receiverCategoryTag;

    /**
     * 接收者类型
     */
    @Length(max = 100)
    private String receiverType;

    /**
     * 接收者序号
     */
    private Long sequence;

    /**
     * 接收者参数1ID
     */
    private Long receiverParam1Id;

    /**
     * 接收者参数1代码
     */
    @Length(max = 2000)
    private String receiverParam1Code;

    /**
     * 接收者参数2ID
     */
    private Long receiverParam2Id;

    /**
     * 接收者参数2代码
     */
    @Length(max = 2000)
    private String receiverParam2Code;

    /**
     * 接收者参数3ID
     */
    private Long receiverParam3Id;

    /**
     * 接收者参数3代码
     */
    @Length(max = 2000)
    private String receiverParam3Code;

    /**
     * 接收者参数4ID
     */
    private Long receiverParam4Id;

    /**
     * 接收者参数4代码
     */
    @Length(max = 2000)
    private String receiverParam4Code;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

    @Transient
    @Children
    private List<WflTaskRcvBizDetail> receiverBizRules;

}
