package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import lombok.*;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ver_task_rcv_biz_detail")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflVerTaskRcvBizDetail extends BaseDTO {

    public static final String FIELD_VERSION_DETAIL_ID = "versionDetailId";
    public static final String FIELD_DETAIL_ID = "detailId";
    public static final String FIELD_VERSION = "version";
    public static final String FIELD_RECEIVER_ID = "receiverId";
    public static final String FIELD_BUSINESS_RULE_ID = "businessRuleId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long versionDetailId;

    @Where
    private Long detailId;

    /**
     * 工作流版本
     */
    @Where
    private Long version;

    /**
     * 接收ID
     */
    @Where
    private Long receiverId;

    /**
     * 权限规则ID
     */
    private Long businessRuleId;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

    public WflVerTaskRcvBizDetail(WflTaskRcvBizDetail detail) {
        this.detailId = detail.getDetailId();
        this.receiverId = detail.getReceiverId();
        this.businessRuleId = detail.getBusinessRuleId();
        this.enabledFlag = detail.getEnabledFlag();
    }

}
