package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import lombok.*;


@ExtensionAttribute(disable = true)
@Table(name = "wfl_ver_gtw_biz_rule_detail")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflVerGtwBizRuleDetail extends BaseDTO {

    public static final String FIELD_VERSION_DETAIL_ID = "versionDetailId";
    public static final String FIELD_DETAIL_ID = "detailId";
    public static final String FIELD_VERSION = "version";
    public static final String FIELD_GROUP_ID = "groupId";
    public static final String FIELD_BUSINESS_RULE_ID = "businessRuleId";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    /**
     * ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long versionDetailId;

    /**
     * 网关权限明细ID
     */
    @Where
    private Long detailId;

    /**
     * 工作流版本
     */
    @Where
    private Long version;

    /**
     * 接收ID
     */
    @Where
    private Long groupId;

    /**
     * 权限组ID
     */
    private Long businessRuleId;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

    public WflVerGtwBizRuleDetail(WflGatewayBizRuleDetail detail) {
        this.detailId = detail.getDetailId();
        this.groupId = detail.getGroupId();
        this.businessRuleId = detail.getBusinessRuleId();
        this.enabledFlag = detail.getEnabledFlag();
    }
}
