package com.hand.hec.wfl.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import java.math.BigDecimal;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import lombok.*;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_version_user_task")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflVersionUserTask extends BaseDTO {

    public static final String FIELD_VERSION_TASK_ID = "versionTaskId";
    public static final String FIELD_USER_TASK_ID = "userTaskId";
    public static final String FIELD_TASK_ID = "taskId";
    public static final String FIELD_VERSION = "version";
    public static final String FIELD_APPROVE_TYPE = "approveType";
    public static final String FIELD_APPROVE_TYPE_PARAM = "approveTypeParam";
    public static final String FIELD_CAN_SUBMITTER_RECHECK = "canSubmitterRecheck";
    public static final String FIELD_CAN_REPEATED_APPROVE = "canRepeatedApprove";
    public static final String FIELD_CAN_NO_APPROVER = "canNoApprover";
    public static final String FIELD_CAN_ADD_APPROVER = "canAddApprover";
    public static final String FIELD_CAN_DELIVER = "canDeliver";
    public static final String FIELD_CAN_ADD_NOTIFICATION = "canAddNotification";
    public static final String FIELD_CAN_TAKE_BACK = "canTakeBack";
    public static final String FIELD_CAN_GO_BACK = "canGoBack";
    public static final String FIELD_TIME_LIMITED_FLAG = "timeLimitedFlag";
    public static final String FIELD_LIMITED_HOURS = "limitedHours";
    public static final String FIELD_OVERTIME_NOTIFY_FLAG = "overtimeNotifyFlag";
    public static final String FIELD_OVERTIME_NOTIFY_SCHEDULER_ID = "overtimeNotifySchedulerId";
    public static final String FIELD_OVERTIME_NOTIFY_MSG_TPLT_ID = "overtimeNotifyMsgTpltId";
    public static final String FIELD_ARRIVE_NOTIFY_FLAG = "arriveNotifyFlag";
    public static final String FIELD_ARRIVE_MSG_TPLT_ID = "arriveMsgTpltId";
    public static final String FIELD_POST_NOTIFY_FLAG = "postNotifyFlag";
    public static final String FIELD_POST_MSG_TPLT_ID = "postMsgTpltId";

    /**
     * 一票通过/拒绝
     */
    public static final String APPROVE_TYPE_ONE_AGREE_REJECT = "ONE_AGREE_REJECT";
    /**
     * 任一人同意/全部拒绝
     */
    public static final String APPROVE_TYPE_ANY_AGREE = "ANY_AGREE";
    /**
     * 全部同意/任一人拒绝
     */
    public static final String APPROVE_TYPE_ALL_AGREE = "ALL_AGREE";
    /**
     * 一定比例同意
     */
    public static final String APPROVE_TYPE_RATIO_AGREE = "RATIO_AGREE";
    /**
     * 一定比例的规则同意
     */
    public static final String APPROVE_TYPE_RATIO_RULE_AGREE = "RATIO_RULE_AGREE";
    /**
     * 任一规则同意/全部规则拒绝
     */
    public static final String APPROVE_TYPE_ONE_RULE_AGREE_REJECT = "ONE_RULE_AGREE_REJECT";
    /**
     * 任一审批串同意/任一审批串拒绝
     */
    public static final String APPROVE_TYPE_ONE_LINE_AGREE_REJECT = "ONE_LINE_AGREE_REJECT";

    @Id
    @GeneratedValue
    @Where
    private Long versionTaskId;


    @Where
    private Long userTaskId;

    /**
     * 任务ID
     */
    @Where
    private Long taskId;

    /**
     * 工作流版本
     */
    @Where
    private Long version;

    /**
     * 审批类型
     */
    @NotEmpty
    @Length(max = 30)
    private String approveType;

    /**
     * 审批类型参数
     */
    @NotEmpty
    @Length(max = 30)
    private String approveTypeParam;

    /**
     * 提交人是否需要审批
     */
    @NotEmpty
    @Length(max = 1)
    private String canSubmitterRecheck;

    /**
     * 是否需要重复审批
     */
    @NotEmpty
    @Length(max = 1)
    private String canRepeatedApprove;

    /**
     * 是否可以无审批人
     */
    @NotEmpty
    @Length(max = 1)
    private String canNoApprover;

    /**
     * 是否可以添加审批人
     */
    @NotEmpty
    @Length(max = 1)
    private String canAddApprover;

    /**
     * 是否可以转交
     */
    @NotEmpty
    @Length(max = 1)
    private String canDeliver;

    /**
     * 是否可以添加抄送人
     */
    @NotEmpty
    @Length(max = 1)
    private String canAddNotification;

    /**
     * 是否可以收回
     */
    @NotEmpty
    @Length(max = 1)
    private String canTakeBack;

    /**
     * 是否可以退回上一节点
     */
    @NotEmpty
    @Length(max = 1)
    private String canGoBack;

    /**
     * 是否有时间限制
     */
    @NotEmpty
    @Length(max = 1)
    private String timeLimitedFlag;

    /**
     * 时间限制（小时）
     */
    private BigDecimal limitedHours;

    /**
     * 是否需要超时发送提醒
     */
    @NotEmpty
    @Length(max = 1)
    private String overtimeNotifyFlag;

    /**
     * 超时提醒计划ID
     */
    private Long overtimeNotifySchedulerId;

    /**
     * 超时提醒消息模板ID
     */
    private Long overtimeNotifyMsgTpltId;

    /**
     * 抵达任务是否需要提醒
     */
    @NotEmpty
    @Length(max = 1)
    private String arriveNotifyFlag;

    /**
     * 抵达任务提醒消息模板ID
     */
    private Long arriveMsgTpltId;

    /**
     * 通过任务是否需要提醒
     */
    @NotEmpty
    @Length(max = 1)
    private String postNotifyFlag;

    /**
     * 通过任务提醒消息ID
     */
    private Long postMsgTpltId;

    public WflVersionUserTask(WflUserTask userTask) {
        this.userTaskId = userTask.getUserTaskId();
        this.taskId = userTask.getTaskId();
        this.approveType = userTask.getApproveType();
        this.approveTypeParam = userTask.getApproveTypeParam();
        this.canSubmitterRecheck = userTask.getCanSubmitterRecheck();
        this.canRepeatedApprove = userTask.getCanRepeatedApprove();
        this.canNoApprover = userTask.getCanNoApprover();
        this.canAddApprover = userTask.getCanAddApprover();
        this.canDeliver = userTask.getCanDeliver();
        this.canAddNotification = userTask.getCanAddNotification();
        this.canTakeBack = userTask.getCanTakeBack();
        this.canGoBack = userTask.getCanGoBack();
        this.timeLimitedFlag = userTask.getTimeLimitedFlag();
        this.limitedHours = userTask.getLimitedHours();
        this.overtimeNotifyFlag = userTask.getOvertimeNotifyFlag();
        this.overtimeNotifySchedulerId = userTask.getOvertimeNotifySchedulerId();
        this.overtimeNotifyMsgTpltId = userTask.getOvertimeNotifyMsgTpltId();
        this.arriveNotifyFlag = userTask.getArriveNotifyFlag();
        this.arriveMsgTpltId = userTask.getArriveMsgTpltId();
        this.postNotifyFlag = userTask.getPostNotifyFlag();
        this.postMsgTpltId = userTask.getPostMsgTpltId();
    }

}
