package com.hand.hec.wfl.dto;

/** Auto Generated By Hap Code Generator **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import lombok.*;

import java.util.HashMap;
import java.util.Map;

@ExtensionAttribute(disable = true)
@Table(name = "wfl_ver_task_receiver")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
public class WflVerTaskReceiver extends BaseDTO {

    public static final String FIELD_VERSION_RECEIVER_ID = "versionReceiverId";
    public static final String FIELD_RECEIVER_ID = "receiverId";
    public static final String FIELD_VERSION = "version";
    public static final String FIELD_TASK_ID = "taskId";
    public static final String FIELD_RECEIVER_CATEGORY = "receiverCategory";
    public static final String FIELD_RECEIVER_TYPE = "receiverType";
    public static final String FIELD_SEQUENCE = "sequence";
    public static final String FIELD_RECEIVER_PARAM1_ID = "receiverParam1Id";
    public static final String FIELD_RECEIVER_PARAM1_CODE = "receiverParam1Code";
    public static final String FIELD_RECEIVER_PARAM2_ID = "receiverParam2Id";
    public static final String FIELD_RECEIVER_PARAM2_CODE = "receiverParam2Code";
    public static final String FIELD_RECEIVER_PARAM3_ID = "receiverParam3Id";
    public static final String FIELD_RECEIVER_PARAM3_CODE = "receiverParam3Code";
    public static final String FIELD_RECEIVER_PARAM4_ID = "receiverParam4Id";
    public static final String FIELD_RECEIVER_PARAM4_CODE = "receiverParam4Code";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    /**
     * 接收ID
     */
    @Id
    @GeneratedValue
    @Where
    private Long versionReceiverId;

    @Where
    private Long receiverId;

    /**
     * 工作流版本
     */
    @Where
    private Long version;

    /**
     * 任务ID
     */
    @Where
    private Long taskId;

    /**
     * 接收者类别
     */
    @NotEmpty
    @Length(max = 100)
    private String receiverCategory;

    /**
     * 接收者类型
     */
    @Length(max = 100)
    private String receiverType;

    /**
     * 接收者序号
     */
    private Long sequence;

    /**
     * 接收者参数1ID
     */
    private Long receiverParam1Id;

    /**
     * 接收者参数1代码
     */
    @Length(max = 2000)
    private String receiverParam1Code;

    /**
     * 接收者参数2ID
     */
    private Long receiverParam2Id;

    /**
     * 接收者参数2代码
     */
    @Length(max = 2000)
    private String receiverParam2Code;

    /**
     * 接收者参数3ID
     */
    private Long receiverParam3Id;

    /**
     * 接收者参数3代码
     */
    @Length(max = 2000)
    private String receiverParam3Code;

    /**
     * 接收者参数4ID
     */
    private Long receiverParam4Id;

    /**
     * 接收者参数4代码
     */
    @Length(max = 2000)
    private String receiverParam4Code;

    /**
     * 启用标志
     */
    @Length(max = 1)
    private String enabledFlag;

    @Transient
    @Children
    private Map<String, WflVerTaskRcvBizDetail> rcvBizDetailMap;

    public void addTaskRcvBizDetail(String key, WflVerTaskRcvBizDetail taskRcvBiz) {
        if (rcvBizDetailMap == null) {
            rcvBizDetailMap = new HashMap<String, WflVerTaskRcvBizDetail>();
        }
        rcvBizDetailMap.put(key, taskRcvBiz);
    }

    public WflVerTaskRcvBizDetail getTaskRcvBizDetail(String key) {
        return rcvBizDetailMap == null ? null : rcvBizDetailMap.get(key);
    }

    public WflVerTaskReceiver(WflTaskReceiver receiver) {
        this.receiverId = receiver.getReceiverId();
        this.taskId = receiver.getTaskId();
        this.receiverCategory = receiver.getReceiverCategory();
        this.receiverType = receiver.getReceiverType();
        this.sequence = receiver.getSequence();
        this.receiverParam1Id = receiver.getReceiverParam1Id();
        this.receiverParam1Code = receiver.getReceiverParam1Code();
        this.receiverParam2Id = receiver.getReceiverParam2Id();
        this.receiverParam2Code = receiver.getReceiverParam2Code();
        this.receiverParam3Id = receiver.getReceiverParam3Id();
        this.receiverParam3Code = receiver.getReceiverParam3Code();
        this.receiverParam4Id = receiver.getReceiverParam4Id();
        this.receiverParam4Code = receiver.getReceiverParam4Code();
        this.enabledFlag = receiver.getEnabledFlag();
    }
}
